using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TawGatherMembersInfo
{

    public partial class Person
    {
        /// <summary>
        /// If unit name contains this string it has higher priority.
        /// Higher index means higher priority.
        /// </summary>
        static List<string> inGameUnitNamePriority = new List<string>() { "division", "battalion", "squad" };


        #region Ranks short name, long name, small image, big image

        /// <summary>
        /// Smaller index is smaller rank
        /// </summary>
        static List<string> rankNameShortOrder = new List<string>()
            {
                "",
                "REC",
                "PFC",
                "LCP",
                "CPL",
                "SGT",
                "SSG",
                "GSG",
                "MSG",
                "1SG",
                "MGS",
                "SGM",
                "2LT",
                "1LT",
                "CPT",
                "MAJ",
                "LTC",
                "COL",
            };

        static Dictionary<string, string> rankNameShortToRankImageSmall = new Dictionary<string, string>()
            {
                {"REC", "http://i.imgur.com/jcHvcul.png"},
                {"PFC", "http://i.imgur.com/PGymqkT.png"},
                {"LCP", "http://i.imgur.com/RHkwVzX.png"},
                {"CPL", "http://i.imgur.com/eaA3y9R.png"},
                {"SGT", "http://i.imgur.com/LhxaoN6.png"},
                {"SSG", "http://i.imgur.com/fegTyol.png"},
                {"GSG", "http://i.imgur.com/DK3XX6j.png"},
                {"MSG", "http://i.imgur.com/WieCvYJ.png"},
                {"1SG", "http://i.imgur.com/DKbJkyc.png"},
                {"MGS", "http://i.imgur.com/6Qnsfk6.png"},
                {"SGM", "http://i.imgur.com/ygNvDIP.png"},
                {"2LT", "http://i.imgur.com/CtANpCr.png"},
                {"1LT", "http://i.imgur.com/vm68HEM.png"},
                {"CPT", "http://i.imgur.com/MFhFQ83.png"},
                {"MAJ", "http://i.imgur.com/OLUbVSj.png"},
                {"LTC", "http://i.imgur.com/queFoBA.png"},
                {"COL", "http://i.imgur.com/OHZq8eU.png"},
            };


        static string GetRankImageBigFromRankNameShort(string rankNameShort)
        {
            var rankIndex = rankNameShortOrder.IndexOf(rankNameShort);
            // http://taw.net/Utility/ranks/rank_22.png is REC
            // http://taw.net/Utility/ranks/rank_21.png is PFC
            // http://taw.net/Utility/ranks/rank_20.png is LCP
            return "http://taw.net/Utility/ranks/rank_" + (22 - rankIndex) + ".png";

        }

        #endregion


        public static Dictionary<string, string> rankNameShortToRankNameLong = new Dictionary<string, string>()
            {
                {"REC", "Recruit"},
                {"PFC", "Private First Class"},
                {"LCP", "Lance Corporal"},
                {"CPL", "Corporal"},
                {"SGT", "Sergeant"},
                {"SSG", "Staff Sergeant"},
                {"GSG", "Gunnery Sergeant"},
                {"MSG", "Master Sergeant"},
                {"1SG", "First Sergeant"},
                {"MGS", "Master Gunnery Sergeant"},
                {"SGM", "Sergeant Major"},
                {"2LT", "Second Lieutenant"},
                {"1LT", "First Lieutenant"},
                {"CPT", "Captain"},
                {"MAJ", "Major"},
                {"LTC", "Lieutenant Colonel"},
                {"COL", "Colonel"},
            };

        #region Position name short rank name long, priority order of rank name short

        /// <summary>
        /// Smaller index is smaller priority
        /// </summary>
        public static List<string> positionNameShortTeamSpeakNamePriorityOrder = new List<string>()
            {
                "FL",
                "ST",
                "DI",
                "TI",
                "SL",
                "PL",
                "TS",
                "SA",
                "FS",
                "SO",
                "XO",
                "CO",
                "PIO",
                "DO",
                "SUL",
                "DC",
            };

        /// <summary>
        /// Smaller index is smaller priority
        /// </summary>
        public static List<string> positionNameShortIngamePriorityOrder = new List<string>()
            {
                "FL",
                "SL",
                "PL",
                "FS",
            };



        public static BiDictionary<string, string> positionNameShortToPositionNameLong = new BiDictionary<string, string>
            {
                // Support staff doesnt use these, they just have one and the same behind their names

                {"CIC", "Commander-in-Chief"},
                {"AC", "Army Commander"},
                {"ALC", "Army Lt. Commander"},
                {"CC", "Corps. Commander"},
                {"CLC", "Corps. Lt. Commander"},
                {"VC", "Vanguard Commander"},
                {"VLC", "Vanguard Lt. Commander"},
                {"SC", "Support Commander"},
                {"SLC", "Support Lt. Commander"},
                {"SDC", "Support Division Commander"},
                {"SOM", "Support Operations Member"},
                {"SDO", "Support Division Officer"},
                {"SCC", "Support Corps. Commander"},
                {"SCLC", "Support Corps. Lt. Commander"},
                {"ISC", "Information Security Commander"},
                {"ISLC", "Information Security Lt. Commander"},
                {"TSC", "Treasury Support Commander"},
                {"TSLC", "Treasury Support Lt. Commander"},
                {"TAW", "Board Member"},

                {"DC", "Division Commander"},
                {"SUL", "Spin-Up Leader"},
                {"DO", "Division Officer"},
                {"PIO", "Public Information Officer"},
                {"CO", "Commanding Officer"},
                {"XO", "Executive Officer"},
                {"SO", "Staff Officer"},
                {"FS", "Field Specialist"},
                {"SA", "Server Administrator"},
                {"TS", "Training Specialist"},
                {"PL", "Platoon Leader"},
                {"SL", "Squad Leader"},
                {"TI", "Training Instructor"},
                {"DI", "Drill Instructor"},
                {"ST", "Server Technician"},
                {"FL", "Fire Team Leader"},
            };

        /// <summary>
        /// Positions that do not have division number behind them in teamSpeakName
        /// </summary>
        public static HashSet<string> positionNameShortOwnedByDivision = new HashSet<string>
            {
                "DC",
                "SUL",
                "DO",
                "PIO",
            };

        #endregion


        #region Country codeTwoLetter codeThreeLetter countryFlagImageUrl

        static string GetCountryFlagImageUrl(string countryCodeTwoLetter)
        {
            if (countryCodeTwoLetter.Length > 2) countryCodeTwoLetter = countryCodeTwoLetter.Substring(0, 2);
            if (countryCodeTwoLetter.Length == 2) return @"http://i1028.photobucket.com/albums/y345/judgernaut/TS_flags/" + countryCodeTwoLetter + ".png";
            return "";
        }

        /*
        // redundant and 100% clear, no need to do it
        // better call it with it's standart name like IsoXXXX
        static BiDictionary<string, string> countryCodeIso3166ToCountryCodeThreeLetters = new BiDictionary<string, string>()
        {
            {"af", "AFG"},
            {"al", "ALB"},
            {"dz", "DZA"},
            {"as", "ASM"},
            {"ad", "AND"},
            {"ao", "AGO"},
            {"ai", "AIA"},
            {"aq", "ATA"},
            {"ag", "ATG"},
            {"ar", "ARG"},
            {"am", "ARM"},
            {"aw", "ABW"},
            {"au", "AUS"},
            {"at", "AUT"},
            {"az", "AZE"},
            {"bs", "BHS"},
            {"bh", "BHR"},
            {"bd", "BGD"},
            {"bb", "BRB"},
            {"by", "BLR"},
            {"be", "BEL"},
            {"bz", "BLZ"},
            {"bj", "BEN"},
            {"bm", "BMU"},
            {"bt", "BTN"},
            {"bo", "BOL"},
            {"bq", "BES"},
            {"ba", "BIH"},
            {"bw", "BWA"},
            {"bv", "BVT"},
            {"br", "BRA"},
            {"io", "IOT"},
            {"bn", "BRN"},
            {"bg", "BGR"},
            {"bf", "BFA"},
            {"bi", "BDI"},
            {"kh", "KHM"},
            {"cm", "CMR"},
            {"ca", "CAN"},
            {"cv", "CPV"},
            {"ky", "CYM"},
            {"cf", "CAF"},
            {"td", "TCD"},
            {"cl", "CHL"},
            {"cn", "CHN"},
            {"cx", "CXR"},
            {"cc", "CCK"},
            {"co", "COL"},
            {"km", "COM"},
            {"cg", "COG"},
            {"cd", "COD"},
            {"ck", "COK"},
            {"cr", "CRI"},
            {"hr", "HRV"},
            {"cu", "CUB"},
            {"cw", "CUW"},
            {"cy", "CYP"},
            {"cz", "CZE"},
            {"ci", "CIV"},
            {"dk", "DNK"},
            {"dj", "DJI"},
            {"dm", "DMA"},
            {"do", "DOM"},
            {"ec", "ECU"},
            {"eg", "EGY"},
            {"sv", "SLV"},
            {"gb", "GBR"},
            {"gq", "GNQ"},
            {"er", "ERI"},
            {"ee", "EST"},
            {"et", "ETH"},
            {"fk", "FLK"},
            {"fo", "FRO"},
            {"fj", "FJI"},
            {"fi", "FIN"},
            {"fr", "FRA"},
            {"gf", "GUF"},
            {"pf", "PYF"},
            {"tf", "ATF"},
            {"ga", "GAB"},
            {"gm", "GMB"},
            {"ge", "GEO"},
            {"de", "DEU"},
            {"gh", "GHA"},
            {"gi", "GIB"},
            {"gr", "GRC"},
            {"gl", "GRL"},
            {"gd", "GRD"},
            {"gp", "GLP"},
            {"gu", "GUM"},
            {"gt", "GTM"},
            {"gg", "GGY"},
            {"gn", "GIN"},
            {"gw", "GNB"},
            {"gy", "GUY"},
            {"ht", "HTI"},
            {"hm", "HMD"},
            {"va", "VAT"},
            {"hn", "HND"},
            {"hk", "HKG"},
            {"hu", "HUN"},
            {"is", "ISL"},
            {"in", "IND"},
            {"id", "IDN"},
            {"ir", "IRN"},
            {"iq", "IRQ"},
            {"ie", "IRL"},
            {"im", "IMN"},
            {"il", "ISR"},
            {"it", "ITA"},
            {"jm", "JAM"},
            {"jp", "JPN"},
            {"je", "JEY"},
            {"jo", "JOR"},
            {"kz", "KAZ"},
            {"ke", "KEN"},
            {"ki", "KIR"},
            {"kp", "PRK"},
            {"kr", "KOR"},
            {"kw", "KWT"},
            {"kg", "KGZ"},
            {"la", "LAO"},
            {"lv", "LVA"},
            {"lb", "LBN"},
            {"ls", "LSO"},
            {"lr", "LBR"},
            {"ly", "LBY"},
            {"li", "LIE"},
            {"lt", "LTU"},
            {"lu", "LUX"},
            {"mo", "MAC"},
            {"mk", "MKD"},
            {"mg", "MDG"},
            {"mw", "MWI"},
            {"my", "MYS"},
            {"mv", "MDV"},
            {"ml", "MLI"},
            {"mt", "MLT"},
            {"mh", "MHL"},
            {"mq", "MTQ"},
            {"mr", "MRT"},
            {"mu", "MUS"},
            {"yt", "MYT"},
            {"mx", "MEX"},
            {"fm", "FSM"},
            {"md", "MDA"},
            {"mc", "MCO"},
            {"mn", "MNG"},
            {"me", "MNE"},
            {"ms", "MSR"},
            {"ma", "MAR"},
            {"mz", "MOZ"},
            {"mm", "MMR"},
            {"na", "NAM"},
            {"nr", "NRU"},
            {"np", "NPL"},
            {"nl", "NLD"},
            {"nc", "NCL"},
            {"nz", "NZL"},
            {"ni", "NIC"},
            {"ne", "NER"},
            {"ng", "NGA"},
            {"nu", "NIU"},
            {"nf", "NFK"},
            {"mp", "MNP"},
            {"no", "NOR"},
            {"om", "OMN"},
            {"pk", "PAK"},
            {"pw", "PLW"},
            {"ps", "PSE"},
            {"pa", "PAN"},
            {"pg", "PNG"},
            {"py", "PRY"},
            {"pe", "PER"},
            {"ph", "PHL"},
            {"pn", "PCN"},
            {"pl", "POL"},
            {"pt", "PRT"},
            {"pr", "PRI"},
            {"qa", "QAT"},
            {"ro", "ROU"},
            {"ru", "RUS"},
            {"rw", "RWA"},
            {"re", "REU"},
            {"bl", "BLM"},
            {"sh", "SHN"},
            {"kn", "KNA"},
            {"lc", "LCA"},
            {"mf", "MAF"},
            {"pm", "SPM"},
            {"vc", "VCT"},
            {"ws", "WSM"},
            {"sm", "SMR"},
            {"st", "STP"},
            {"sa", "SAU"},
            {"sn", "SEN"},
            {"rs", "SRB"},
            {"sc", "SYC"},
            {"sl", "SLE"},
            {"sg", "SGP"},
            {"sx", "SXM"},
            {"sk", "SVK"},
            {"si", "SVN"},
            {"sb", "SLB"},
            {"so", "SOM"},
            {"za", "ZAF"},
            {"gs", "SGS"},
            {"ss", "SSD"},
            {"es", "ESP"},
            {"lk", "LKA"},
            {"sd", "SDN"},
            {"sr", "SUR"},
            {"sj", "SJM"},
            {"sz", "SWZ"},
            {"se", "SWE"},
            {"ch", "CHE"},
            {"sy", "SYR"},
            {"tw", "TWN"},
            {"tj", "TJK"},
            {"tz", "TZA"},
            {"th", "THA"},
            {"tl", "TLS"},
            {"tg", "TGO"},
            {"tk", "TKL"},
            {"to", "TON"},
            {"tt", "TTO"},
            {"tn", "TUN"},
            {"tr", "TUR"},
            {"tm", "TKM"},
            {"tc", "TCA"},
            {"tv", "TUV"},
            {"ug", "UGA"},
            {"ua", "UKR"},
            {"ae", "ARE"},
            {"us", "USA"},
            {"um", "UMI"},
            {"uy", "URY"},
            {"uz", "UZB"},
            {"vu", "VUT"},
            {"ve", "VEN"},
            {"vn", "VNM"},
            {"vg", "VGB"},
            {"vi", "VIR"},
            {"wf", "WLF"},
            {"eh", "ESH"},
            {"ye", "YEM"},
            {"zm", "ZMB"},
            {"zw", "ZWE"},
            {"ax", "ALA"},
        };
        */

        static BiDictionary<string, string> countryCodeIso3166ToCountryName = new BiDictionary<string, string>()
            {
                {"af", "Afghanistan"},
                {"al", "Albania"},
                {"dz", "Algeria"},
                {"as", "American Samoa"},
                {"ad", "Andorra"},
                {"ao", "Angola"},
                {"ai", "Anguilla"},
                {"aq", "Antarctica"},
                {"ag", "Antigua and Barbuda"},
                {"ar", "Argentina"},
                {"am", "Armenia"},
                {"aw", "Aruba"},
                {"au", "Australia"},
                {"at", "Austria"},
                {"az", "Azerbaijan"},
                {"bs", "Bahamas"},
                {"bh", "Bahrain"},
                {"bd", "Bangladesh"},
                {"bb", "Barbados"},
                {"by", "Belarus"},
                {"be", "Belgium"},
                {"bz", "Belize"},
                {"bj", "Benin"},
                {"bm", "Bermuda"},
                {"bt", "Bhutan"},
                {"bo", "Bolivia"},
                {"bq", "Bonaire"},
                {"ba", "Bosnia and Herzegovina"},
                {"bw", "Botswana"},
                {"bv", "Bouvet Island"},
                {"br", "Brazil"},
                {"io", "British Indian Ocean Territory"},
                {"bn", "Brunei Darussalam"},
                {"bg", "Bulgaria"},
                {"bf", "Burkina Faso"},
                {"bi", "Burundi"},
                {"kh", "Cambodia"},
                {"cm", "Cameroon"},
                {"ca", "Canada"},
                {"cv", "Cape Verde"},
                {"ky", "Cayman Islands"},
                {"cf", "Central African Republic"},
                {"td", "Chad"},
                {"cl", "Chile"},
                {"cn", "China"},
                {"cx", "Christmas Island"},
                {"cc", "Cocos (Keeling) Islands"},
                {"co", "Colombia"},
                {"km", "Comoros"},
                {"cg", "Congo"},
                {"cd", "Democratic Republic of the Congo"},
                {"ck", "Cook Islands"},
                {"cr", "Costa Rica"},
                {"hr", "Croatia"},
                {"cu", "Cuba"},
                {"cw", "Curacao"},
                {"cy", "Cyprus"},
                {"cz", "Czech Republic"},
                {"ci", "Côte d'Ivoire"},
                {"dk", "Denmark"},
                {"dj", "Djibouti"},
                {"dm", "Dominica"},
                {"do", "Dominican Republic"},
                {"ec", "Ecuador"},
                {"eg", "Egypt"},
                {"sv", "El Salvador"},
                {"gq", "Equatorial Guinea"},
                {"er", "Eritrea"},
                {"ee", "Estonia"},
                {"et", "Ethiopia"},
                {"fk", "Falkland Islands (Malvinas)"},
                {"fo", "Faroe Islands"},
                {"fj", "Fiji"},
                {"fi", "Finland"},
                {"fr", "France"},
                {"gf", "French Guiana"},
                {"pf", "French Polynesia"},
                {"tf", "French Southern Territories"},
                {"ga", "Gabon"},
                {"gm", "Gambia"},
                {"ge", "Georgia"},
                {"de", "Germany"},
                {"gh", "Ghana"},
                {"gi", "Gibraltar"},
                {"gr", "Greece"},
                {"gl", "Greenland"},
                {"gd", "Grenada"},
                {"gp", "Guadeloupe"},
                {"gu", "Guam"},
                {"gt", "Guatemala"},
                {"gg", "Guernsey"},
                {"gn", "Guinea"},
                {"gw", "Guinea-Bissau"},
                {"gy", "Guyana"},
                {"ht", "Haiti"},
                {"hm", "Heard Island and McDonald Mcdonald Islands"},
                {"va", "Holy See (Vatican City State)"},
                {"hn", "Honduras"},
                {"hk", "Hong Kong"},
                {"hu", "Hungary"},
                {"is", "Iceland"},
                {"in", "India"},
                {"id", "Indonesia"},
                {"ir", "Iran, Islamic Republic of"},
                {"iq", "Iraq"},
                {"ie", "Ireland"},
                {"im", "Isle of Man"},
                {"il", "Israel"},
                {"it", "Italy"},
                {"jm", "Jamaica"},
                {"jp", "Japan"},
                {"je", "Jersey"},
                {"jo", "Jordan"},
                {"kz", "Kazakhstan"},
                {"ke", "Kenya"},
                {"ki", "Kiribati"},
                {"kp", "Korea, Democratic People's Republic of"},
                {"kr", "Korea, Republic of"},
                {"kw", "Kuwait"},
                {"kg", "Kyrgyzstan"},
                {"la", "Lao People's Democratic Republic"},
                {"lv", "Latvia"},
                {"lb", "Lebanon"},
                {"ls", "Lesotho"},
                {"lr", "Liberia"},
                {"ly", "Libya"},
                {"li", "Liechtenstein"},
                {"lt", "Lithuania"},
                {"lu", "Luxembourg"},
                {"mo", "Macao"},
                {"mk", "Macedonia, the Former Yugoslav Republic of"},
                {"mg", "Madagascar"},
                {"mw", "Malawi"},
                {"my", "Malaysia"},
                {"mv", "Maldives"},
                {"ml", "Mali"},
                {"mt", "Malta"},
                {"mh", "Marshall Islands"},
                {"mq", "Martinique"},
                {"mr", "Mauritania"},
                {"mu", "Mauritius"},
                {"yt", "Mayotte"},
                {"mx", "Mexico"},
                {"fm", "Micronesia, Federated States of"},
                {"md", "Moldova, Republic of"},
                {"mc", "Monaco"},
                {"mn", "Mongolia"},
                {"me", "Montenegro"},
                {"ms", "Montserrat"},
                {"ma", "Morocco"},
                {"mz", "Mozambique"},
                {"mm", "Myanmar"},
                {"na", "Namibia"},
                {"nr", "Nauru"},
                {"np", "Nepal"},
                {"nl", "Netherlands"},
                {"nc", "New Caledonia"},
                {"nz", "New Zealand"},
                {"ni", "Nicaragua"},
                {"ne", "Niger"},
                {"ng", "Nigeria"},
                {"nu", "Niue"},
                {"nf", "Norfolk Island"},
                {"mp", "Northern Mariana Islands"},
                {"no", "Norway"},
                {"om", "Oman"},
                {"pk", "Pakistan"},
                {"pw", "Palau"},
                {"ps", "Palestine, State of"},
                {"pa", "Panama"},
                {"pg", "Papua New Guinea"},
                {"py", "Paraguay"},
                {"pe", "Peru"},
                {"ph", "Philippines"},
                {"pn", "Pitcairn"},
                {"pl", "Poland"},
                {"pt", "Portugal"},
                {"pr", "Puerto Rico"},
                {"qa", "Qatar"},
                {"ro", "Romania"},
                {"ru", "Russian Federation"},
                {"rw", "Rwanda"},
                {"re", "Reunion"},
                {"bl", "Saint Barthalemy"},
                {"sh", "Saint Helena"},
                {"kn", "Saint Kitts and Nevis"},
                {"lc", "Saint Lucia"},
                {"mf", "Saint Martin (French part)"},
                {"pm", "Saint Pierre and Miquelon"},
                {"vc", "Saint Vincent and the Grenadines"},
                {"ws", "Samoa"},
                {"sm", "San Marino"},
                {"st", "Sao Tome and Principe"},
                {"sa", "Saudi Arabia"},
                {"sn", "Senegal"},
                {"rs", "Serbia"},
                {"sc", "Seychelles"},
                {"sl", "Sierra Leone"},
                {"sg", "Singapore"},
                {"sx", "Sint Maarten (Dutch part)"},
                {"sk", "Slovakia"},
                {"si", "Slovenia"},
                {"sb", "Solomon Islands"},
                {"so", "Somalia"},
                {"za", "South Africa"},
                {"gs", "South Georgia and the South Sandwich Islands"},
                {"ss", "South Sudan"},
                {"es", "Spain"},
                {"lk", "Sri Lanka"},
                {"sd", "Sudan"},
                {"sr", "Suriname"},
                {"sj", "Svalbard and Jan Mayen"},
                {"sz", "Swaziland"},
                {"se", "Sweden"},
                {"ch", "Switzerland"},
                {"sy", "Syrian Arab Republic"},
                {"tw", "Taiwan, Province of China"},
                {"tj", "Tajikistan"},
                {"tz", "United Republic of Tanzania"},
                {"th", "Thailand"},
                {"tl", "Timor-Leste"},
                {"tg", "Togo"},
                {"tk", "Tokelau"},
                {"to", "Tonga"},
                {"tt", "Trinidad and Tobago"},
                {"tn", "Tunisia"},
                {"tr", "Turkey"},
                {"tm", "Turkmenistan"},
                {"tc", "Turks and Caicos Islands"},
                {"tv", "Tuvalu"},
                {"ug", "Uganda"},
                {"ua", "Ukraine"},
                {"ae", "United Arab Emirates"},
                {"gb", "United Kingdom"},
                {"gb-eng", "England"},
                {"us", "United States"},
                {"um", "United States Minor Outlying Islands"},
                {"uy", "Uruguay"},
                {"uz", "Uzbekistan"},
                {"vu", "Vanuatu"},
                {"ve", "Venezuela"},
                {"vn", "Vietnam"},
                {"vg", "British Virgin Islands"},
                {"vi", "US Virgin Islands"},
                {"wf", "Wallis and Futuna"},
                {"eh", "Western Sahara"},
                {"ye", "Yemen"},
                {"zm", "Zambia"},
                {"zw", "Zimbabwe"},
                {"ax", "Aland Islands"},
            };

        #endregion

    }
}