using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TawGatherMembersInfo
{
	public static class Iso3166
	{
		#region ISO 3166

		/// <summary>
		/// Country name to two letter ISO 3166
		/// </summary>
		public readonly static BiDictionary<string, string> countryNameToIso3166 = new BiDictionary<string, string>()
		{
			{"Afghanistan","af"},
			{"Albania","al"},
			{"Algeria","dz"},
			{"American Samoa","as"},
			{"Andorra","ad"},
			{"Angola","ao"},
			{"Anguilla","ai"},
			{"Antarctica","aq"},
			{"Antigua and Barbuda","ag"},
			{"Argentina","ar"},
			{"Armenia","am"},
			{"Aruba","aw"},
			{"Australia","au"},
			{"Austria","at"},
			{"Azerbaijan","az"},
			{"Bahamas","bs"},
			{"Bahrain","bh"},
			{"Bangladesh","bd"},
			{"Barbados","bb"},
			{"Belarus","by"},
			{"Belgium","be"},
			{"Belize","bz"},
			{"Benin","bj"},
			{"Bermuda","bm"},
			{"Bhutan","bt"},
			{"Bolivia","bo"},
			{"Bonaire","bq"},
			{"Bosnia and Herzegovina","ba"},
			{"Botswana","bw"},
			{"Bouvet Island","bv"},
			{"Brazil","br"},
			{"British Indian Ocean Territory","io"},
			{"Brunei Darussalam","bn"},
			{"Bulgaria","bg"},
			{"Burkina Faso","bf"},
			{"Burundi","bi"},
			{"Cambodia","kh"},
			{"Cameroon","cm"},
			{"Canada","ca"},
			{"Cape Verde","cv"},
			{"Cayman Islands","ky"},
			{"Central African Republic","cf"},
			{"Chad","td"},
			{"Chile","cl"},
			{"China","cn"},
			{"Christmas Island","cx"},
			{"Cocos (Keeling) Islands","cc"},
			{"Colombia","co"},
			{"Comoros","km"},
			{"Congo","cg"},
			{"Democratic Republic of the Congo","cd"},
			{"Cook Islands","ck"},
			{"Costa Rica","cr"},
			{"Croatia","hr"},
			{"Cuba","cu"},
			{"Curacao","cw"},
			{"Cyprus","cy"},
			{"Czech Republic","cz"},
			{"Côte d'Ivoire","ci"},
			{"Denmark","dk"},
			{"Djibouti","dj"},
			{"Dominica","dm"},
			{"Dominican Republic","do"},
			{"Ecuador","ec"},
			{"Egypt","eg"},
			{"El Salvador","sv"},
			{"Equatorial Guinea","gq"},
			{"Eritrea","er"},
			{"Estonia","ee"},
			{"Ethiopia","et"},
			{"Falkland Islands (Malvinas)","fk"},
			{"Faroe Islands","fo"},
			{"Fiji","fj"},
			{"Finland","fi"},
			{"France","fr"},
			{"French Guiana","gf"},
			{"French Polynesia","pf"},
			{"French Southern Territories","tf"},
			{"Gabon","ga"},
			{"Gambia","gm"},
			{"Georgia","ge"},
			{"Germany","de"},
			{"Ghana","gh"},
			{"Gibraltar","gi"},
			{"Greece","gr"},
			{"Greenland","gl"},
			{"Grenada","gd"},
			{"Guadeloupe","gp"},
			{"Guam","gu"},
			{"Guatemala","gt"},
			{"Guernsey","gg"},
			{"Guinea","gn"},
			{"Guinea-Bissau","gw"},
			{"Guyana","gy"},
			{"Haiti","ht"},
			{"Heard Island and McDonald Mcdonald Islands","hm"},
			{"Holy See (Vatican City State)","va"},
			{"Honduras","hn"},
			{"Hong Kong","hk"},
			{"Hungary","hu"},
			{"Iceland","is"},
			{"India","in"},
			{"Indonesia","id"},
			{"Iran, Islamic Republic of","ir"},
			{"Iraq","iq"},
			{"Ireland","ie"},
			{"Isle of Man","im"},
			{"Israel","il"},
			{"Italy","it"},
			{"Jamaica","jm"},
			{"Japan","jp"},
			{"Jersey","je"},
			{"Jordan","jo"},
			{"Kazakhstan","kz"},
			{"Kenya","ke"},
			{"Kiribati","ki"},
			{"Korea, Democratic People's Republic of","kp"},
			{"Korea, Republic of","kr"},
			{"Kuwait","kw"},
			{"Kyrgyzstan","kg"},
			{"Lao People's Democratic Republic","la"},
			{"Latvia","lv"},
			{"Lebanon","lb"},
			{"Lesotho","ls"},
			{"Liberia","lr"},
			{"Libya","ly"},
			{"Liechtenstein","li"},
			{"Lithuania","lt"},
			{"Luxembourg","lu"},
			{"Macao","mo"},
			{"Macedonia, the Former Yugoslav Republic of","mk"},
			{"Madagascar","mg"},
			{"Malawi","mw"},
			{"Malaysia","my"},
			{"Maldives","mv"},
			{"Mali","ml"},
			{"Malta","mt"},
			{"Marshall Islands","mh"},
			{"Martinique","mq"},
			{"Mauritania","mr"},
			{"Mauritius","mu"},
			{"Mayotte","yt"},
			{"Mexico","mx"},
			{"Micronesia, Federated States of","fm"},
			{"Moldova, Republic of","md"},
			{"Monaco","mc"},
			{"Mongolia","mn"},
			{"Montenegro","me"},
			{"Montserrat","ms"},
			{"Morocco","ma"},
			{"Mozambique","mz"},
			{"Myanmar","mm"},
			{"Namibia","na"},
			{"Nauru","nr"},
			{"Nepal","np"},
			{"Netherlands","nl"},
			{"New Caledonia","nc"},
			{"New Zealand","nz"},
			{"Nicaragua","ni"},
			{"Niger","ne"},
			{"Nigeria","ng"},
			{"Niue","nu"},
			{"Norfolk Island","nf"},
			{"Northern Mariana Islands","mp"},
			{"Norway","no"},
			{"Oman","om"},
			{"Pakistan","pk"},
			{"Palau","pw"},
			{"Palestine, State of","ps"},
			{"Panama","pa"},
			{"Papua New Guinea","pg"},
			{"Paraguay","py"},
			{"Peru","pe"},
			{"Philippines","ph"},
			{"Pitcairn","pn"},
			{"Poland","pl"},
			{"Portugal","pt"},
			{"Puerto Rico","pr"},
			{"Qatar","qa"},
			{"Romania","ro"},
			{"Russian Federation","ru"},
			{"Rwanda","rw"},
			{"Reunion","re"},
			{"Saint Barthalemy","bl"},
			{"Saint Helena","sh"},
			{"Saint Kitts and Nevis","kn"},
			{"Saint Lucia","lc"},
			{"Saint Martin (French part)","mf"},
			{"Saint Pierre and Miquelon","pm"},
			{"Saint Vincent and the Grenadines","vc"},
			{"Samoa","ws"},
			{"San Marino","sm"},
			{"Sao Tome and Principe","st"},
			{"Saudi Arabia","sa"},
			{"Senegal","sn"},
			{"Serbia","rs"},
			{"Seychelles","sc"},
			{"Sierra Leone","sl"},
			{"Singapore","sg"},
			{"Sint Maarten (Dutch part)","sx"},
			{"Slovakia","sk"},
			{"Slovenia","si"},
			{"Solomon Islands","sb"},
			{"Somalia","so"},
			{"South Africa","za"},
			{"South Georgia and the South Sandwich Islands","gs"},
			{"South Sudan","ss"},
			{"Spain","es"},
			{"Sri Lanka","lk"},
			{"Sudan","sd"},
			{"Suriname","sr"},
			{"Svalbard and Jan Mayen","sj"},
			{"Swaziland","sz"},
			{"Sweden","se"},
			{"Switzerland","ch"},
			{"Syrian Arab Republic","sy"},
			{"Taiwan, Province of China","tw"},
			{"Tajikistan","tj"},
			{"United Republic of Tanzania","tz"},
			{"Thailand","th"},
			{"Timor-Leste","tl"},
			{"Togo","tg"},
			{"Tokelau","tk"},
			{"Tonga","to"},
			{"Trinidad and Tobago","tt"},
			{"Tunisia","tn"},
			{"Turkey","tr"},
			{"Turkmenistan","tm"},
			{"Turks and Caicos Islands","tc"},
			{"Tuvalu","tv"},
			{"Uganda","ug"},
			{"Ukraine","ua"},
			{"United Arab Emirates","ae"},
			{"United Kingdom","gb"},
			{"United States","us"},
			{"United States Minor Outlying Islands","um"},
			{"Uruguay","uy"},
			{"Uzbekistan","uz"},
			{"Vanuatu","vu"},
			{"Venezuela","ve"},
			{"Vietnam","vn"},
			{"British Virgin Islands","vg"},
			{"US Virgin Islands","vi"},
			{"Wallis and Futuna","wf"},
			{"Western Sahara","eh"},
			{"Yemen","ye"},
			{"Zambia","zm"},
			{"Zimbabwe","zw"},
			{"Aland Islands","ax"},
		};

		#endregion ISO 3166

		#region ISO 3166-2

		/// <summary>
		/// Country subdivison name to ISO 3166-2
		/// Taken from: http://www.ip2location.com/free/iso3166-2
		/// </summary>
		public readonly static BiDictionary<string, string> countrySubdivisonNameToIso3166_2 = new BiDictionary<string, string>()
		{
			{"Andorra la Vella","ad-07"},
			{"Canillo","ad-02"},
			{"Encamp","ad-03"},
			{"Escaldes-Engordany","ad-08"},
			{"La Massana","ad-04"},
			{"Ordino","ad-05"},
			{"Sant Julia de Loria","ad-06"},
			{"'Ajman","ae-aj"},
			{"Abu Zaby","ae-az"},
			{"Al Fujayrah","ae-fu"},
			{"Ash Shariqah","ae-sh"},
			{"Dubayy","ae-du"},
			{"Ra's al Khaymah","ae-rk"},
			{"Umm al Qaywayn","ae-uq"},
			{"Badakhshan","af-bds"},
			{"Badghis","af-bdg"},
			{"Baghlan","af-bgl"},
			{"Balkh","af-bal"},
			{"Bamyan","af-bam"},
			{"Daykundi","af-day"},
			{"Farah","af-fra"},
			{"Faryab","af-fyb"},
			{"Ghazni","af-gha"},
			{"Ghor","af-gho"},
			{"Helmand","af-hel"},
			{"Herat","af-her"},
			{"Jowzjan","af-jow"},
			{"Kabul","af-kab"},
			{"Kandahar","af-kan"},
			{"Kapisa","af-kap"},
			{"Khost","af-kho"},
			{"Kunar","af-knr"},
			{"Kunduz","af-kdz"},
			{"Laghman","af-lag"},
			{"Logar","af-log"},
			{"Nangarhar","af-nan"},
			{"Nimroz","af-nim"},
			{"Nuristan","af-nur"},
			{"Paktika","af-pka"},
			{"Paktiya","af-pia"},
			{"Panjshayr","af-pan"},
			{"Parwan","af-par"},
			{"Samangan","af-sam"},
			{"Sar-e pul","af-sar"},
			{"Takhar","af-tak"},
			{"Uruzgan","af-uru"},
			{"Wardak","af-war"},
			{"Zabul","af-zab"},
			{"Saint John","ag-04"},
			{"Saint Mary","ag-05"},
			{"Saint Paul","ag-06"},
			{"Anguilla","ai"},
			{"Berat","al-01"},
			{"Diber","al-09"},
			{"Durres","al-02"},
			{"Elbasan","al-03"},
			{"Fier","al-04"},
			{"Gjirokaster","al-05"},
			{"Korce","al-06"},
			{"Kukes","al-07"},
			{"Lezhe","al-08"},
			{"Shkoder","al-10"},
			{"Tirane","al-11"},
			{"Vlore","al-12"},
			{"Aragacotn","am-ag"},
			{"Ararat","am-ar"},
			{"Armavir","am-av"},
			{"Erevan","am-er"},
			{"Gegark'unik'","am-gr"},
			{"Kotayk'","am-kt"},
			{"Lori","am-lo"},
			{"Sirak","am-sh"},
			{"Syunik'","am-su"},
			{"Tavus","am-tv"},
			{"Vayoc Jor","am-vd"},
			{"Bengo","ao-bgo"},
			{"Benguela","ao-bgu"},
			{"Bie","ao-bie"},
			{"Cabinda","ao-cab"},
			{"Cunene","ao-cnn"},
			{"Huambo","ao-hua"},
			{"Huila","ao-hui"},
			{"Kuando Kubango","ao-ccu"},
			{"Kwanza Norte","ao-cno"},
			{"Kwanza Sul","ao-cus"},
			{"Luanda","ao-lua"},
			{"Lunda Norte","ao-lno"},
			{"Lunda Sul","ao-lsu"},
			{"Malange","ao-mal"},
			{"Moxico","ao-mox"},
			{"Namibe","ao-nam"},
			{"Uige","ao-uig"},
			{"Zaire","ao-zai"},
			{"Antarctica","aq"},
			{"Buenos Aires","ar-b"},
			{"Catamarca","ar-k"},
			{"Chaco","ar-h"},
			{"Chubut","ar-u"},
			{"Ciudad Autonoma de Buenos Aires","ar-c"},
			{"Cordoba","ar-x"},
			{"Corrientes","ar-w"},
			{"Entre Rios","ar-e"},
			{"Formosa","ar-p"},
			{"Jujuy","ar-y"},
			{"La Pampa","ar-l"},
			{"La Rioja","ar-f"},
			{"Mendoza","ar-m"},
			{"Misiones","ar-n"},
			{"Neuquen","ar-q"},
			{"Rio Negro","ar-r"},
			{"Salta","ar-a"},
			{"San Juan","ar-j"},
			{"San Luis","ar-d"},
			{"Santa Cruz","ar-z"},
			{"Santa Fe","ar-s"},
			{"Santiago del Estero","ar-g"},
			{"Tierra del Fuego","ar-v"},
			{"Tucuman","ar-t"},
			{"Burgenland","at-1"},
			{"Karnten","at-2"},
			{"Niederosterreich","at-3"},
			{"Oberosterreich","at-4"},
			{"Salzburg","at-5"},
			{"Steiermark","at-6"},
			{"Tirol","at-7"},
			{"Vorarlberg","at-8"},
			{"Wien","at-9"},
			{"Australian Capital Territory","au-act"},
			{"New South Wales","au-nsw"},
			{"Northern Territory","au-nt"},
			{"Queensland","au-qld"},
			{"South Australia","au-sa"},
			{"Tasmania","au-tas"},
			{"Victoria","au-vic"},
			{"Western Australia","au-wa"},
			{"Abseron","az-abs"},
			{"Agcabadi","az-agc"},
			{"Agdam","az-agm"},
			{"Agdas","az-ags"},
			{"Agstafa","az-aga"},
			{"Agsu","az-agu"},
			{"Astara","az-ast"},
			{"Baki","az-ba"},
			{"Balakan","az-bal"},
			{"Barda","az-bar"},
			{"Beylaqan","az-bey"},
			{"Bilasuvar","az-bil"},
			{"Cabrayil","az-cab"},
			{"Calilabad","az-cal"},
			{"Daskasan","az-das"},
			{"Fuzuli","az-fuz"},
			{"Gadabay","az-gad"},
			{"Ganca","az-ga"},
			{"Goranboy","az-gor"},
			{"Goycay","az-goy"},
			{"Goygol","az-gyg"},
			{"Haciqabul","az-hac"},
			{"Imisli","az-imi"},
			{"Ismayilli","az-ism"},
			{"Kalbacar","az-kal"},
			{"Lacin","az-lac"},
			{"Lankaran","az-lan"},
			{"Lerik","az-ler"},
			{"Masalli","az-mas"},
			{"Mingacevir","az-mi"},
			{"Naftalan","az-na"},
			{"Naxcivan","az-nv"},
			{"Neftcala","az-nef"},
			{"Oguz","az-ogu"},
			{"Qabala","az-qab"},
			{"Qax","az-qax"},
			{"Qazax","az-qaz"},
			{"Qobustan","az-qob"},
			{"Quba","az-qba"},
			{"Qubadli","az-qbi"},
			{"Qusar","az-qus"},
			{"Saatli","az-sat"},
			{"Sabirabad","az-sab"},
			{"Saki","az-sak"},
			{"Salyan","az-sal"},
			{"Samaxi","az-smi"},
			{"Samkir","az-skr"},
			{"Samux","az-smx"},
			{"Sirvan","az-sr"},
			{"Sumqayit","az-sm"},
			{"Susa","az-sus"},
			{"Tartar","az-tar"},
			{"Tovuz","az-tov"},
			{"Ucar","az-uca"},
			{"Xacmaz","az-xac"},
			{"Xankandi","az-xa"},
			{"Xizi","az-xtz"},
			{"Xocali","az-xci"},
			{"Xocavand","az-xvd"},
			{"Yardimli","az-yar"},
			{"Yevlax","az-yev"},
			{"Zangilan","az-zan"},
			{"Zaqatala","az-zaq"},
			{"Zardab","az-zar"},
			{"Federacija Bosna i Hercegovina","ba-bih"},
			{"Republika Srpska","ba-srp"},
			{"Christ Church","bb-01"},
			{"Saint James","bb-04"},
			{"Saint Joseph","bb-06"},
			{"Saint Michael","bb-08"},
			{"Saint Peter","bb-09"},
			{"Barisal","bd-a"},
			{"Chittagong","bd-b"},
			{"Dhaka","bd-c"},
			{"Khulna","bd-d"},
			{"Rajshahi","bd-e"},
			{"Rangpur","bd-f"},
			{"Sylhet","bd-g"},
			{"Antwerpen","be-van"},
			{"Brabant Wallon","be-wbr"},
			{"Brussels Hoofdstedelijk Gewest","be-bru"},
			{"Hainaut","be-wht"},
			{"Liege","be-wlg"},
			{"Limburg","bg-vli"},
			{"Luxembourg","be-wlx"},
			{"Namur","be-wna"},
			{"Oost-Vlaanderen","be-vov"},
			{"Vlaams-Brabant","be-vbr"},
			{"West-Vlaanderen","be-vwv"},
			{"Bale","bf-bal"},
			{"Bam","bf-bam"},
			{"Banwa","bf-abn"},
			{"Bazega","bf-baz"},
			{"Bougouriba","bf-bgr"},
			{"Boulgou","bf-blg"},
			{"Boulkiemde","bf-blk"},
			{"Comoe","bf-com"},
			{"Ganzourgou","bf-gan"},
			{"Gnagna","bf-gna"},
			{"Gourma","bf-gou"},
			{"Houet","bf-hou"},
			{"Ioba","bf-iob"},
			{"Kadiogo","bf-kad"},
			{"Kenedougou","bf-ken"},
			{"Komondjari","bf-kmd"},
			{"Kompienga","bf-kmp"},
			{"Kossi","bf-kos"},
			{"Koulpelogo","bf-kop"},
			{"Kouritenga","bf-kot"},
			{"Kourweogo","bf-kow"},
			{"Leraba","bf-ler"},
			{"Loroum","bf-lor"},
			{"Mouhoun","bf-mou"},
			{"Nahouri","bf-nao"},
			{"Namentenga","bf-nam"},
			{"Nayala","bf-nay"},
			{"Noumbiel","bf-nou"},
			{"Oubritenga","bf-oub"},
			{"Oudalan","bf-oud"},
			{"Passore","bf-pas"},
			{"Poni","bf-pon"},
			{"Sanguie","bf-sng"},
			{"Sanmatenga","bf-smt"},
			{"Seno","bf-sen"},
			{"Sissili","bf-sis"},
			{"Soum","bf-som"},
			{"Sourou","bf-sor"},
			{"Tapoa","bf-tap"},
			{"Tui","bf-tui"},
			{"Yagha","bf-yag"},
			{"Yatenga","bf-yat"},
			{"Ziro","bf-zir"},
			{"Zondoma","bf-zon"},
			{"Zoundweogo","bf-zou"},
			{"Blagoevgrad","bg-01"},
			{"Burgas","bg-02"},
			{"Dobrich","bg-08"},
			{"Gabrovo","bg-07"},
			{"Haskovo","bg-26"},
			{"Kardzhali","bg-09"},
			{"Kyustendil","bg-10"},
			{"Lovech","bg-11"},
			{"Montana","bg-12"},
			{"Pazardzhik","bg-13"},
			{"Pernik","bg-14"},
			{"Pleven","bg-15"},
			{"Plovdiv","bg-16"},
			{"Razgrad","bg-17"},
			{"Ruse","bg-18"},
			{"Shumen","bg-27"},
			{"Silistra","bg-19"},
			{"Sliven","bg-20"},
			{"Smolyan","bg-21"},
			{"Sofia","bg-23"},
			{"Sofia (stolitsa)","bg-22"},
			{"Stara Zagora","bg-24"},
			{"Targovishte","bg-25"},
			{"Varna","bg-03"},
			{"Veliko Tarnovo","bg-04"},
			{"Vidin","bg-05"},
			{"Vratsa","bg-06"},
			{"Yambol","bg-28"},
			{"Al Asimah","bh-13"},
			{"Al Muharraq","bh-15"},
			{"Ash Shamaliyah","bh-17"},
			{"Bubanza","bi-bb"},
			{"Bujumbura Mairie","bi-bm"},
			{"Bururi","bi-br"},
			{"Cankuzo","bi-ca"},
			{"Cibitoke","bi-ci"},
			{"Gitega","bi-gi"},
			{"Karuzi","bi-kr"},
			{"Kayanza","bi-ky"},
			{"Kirundo","bi-ki"},
			{"Makamba","bi-ma"},
			{"Muramvya","bi-mu"},
			{"Muyinga","bi-my"},
			{"Mwaro","bi-mw"},
			{"Ngozi","bi-ng"},
			{"Rutana","bi-rt"},
			{"Ruyigi","bi-ry"},
			{"Alibori","bj-al"},
			{"Atacora","bj-ak"},
			{"Atlantique","bj-aq"},
			{"Borgou","bj-bo"},
			{"Collines","bj-co"},
			{"Couffo","bj-ko"},
			{"Donga","bj-do"},
			{"Littoral","bj-li"},
			{"Mono","bj-mo"},
			{"Oueme","bj-ou"},
			{"Plateau","bj-pl"},
			{"Zou","bj-zo"},
			{"Saint Barthelemy","bl"},
			{"Belait","bn-be"},
			{"Brunei-Muara","bn-bm"},
			{"Temburong","bn-te"},
			{"Tutong","bn-tu"},
			{"Chuquisaca","bo-h"},
			{"Cochabamba","bo-c"},
			{"El Beni","bo-b"},
			{"La Paz","bo-l"},
			{"Oruro","bo-o"},
			{"Pando","bo-n"},
			{"Potosi","bo-p"},
			{"Santa Cruz","ar-z"},
			{"Tarija","bo-t"},
			{"Bonaire","bq-bo"},
			{"Saba","bq-sa"},
			{"Sint Eustatius","bq-se"},
			{"Acre","br-ac"},
			{"Alagoas","br-al"},
			{"Amapa","br-ap"},
			{"Amazonas","br-am"},
			{"Bahia","br-ba"},
			{"Ceara","br-ce"},
			{"Distrito Federal","br-df"},
			{"Espirito Santo","br-es"},
			{"Goias","br-go"},
			{"Maranhao","br-ma"},
			{"Mato Grosso","br-mt"},
			{"Mato Grosso do Sul","br-ms"},
			{"Minas Gerais","br-mg"},
			{"Para","br-pa"},
			{"Paraiba","br-pb"},
			{"Parana","br-pr"},
			{"Pernambuco","br-pe"},
			{"Piaui","br-pi"},
			{"Rio Grande do Norte","br-rn"},
			{"Rio Grande do Sul","br-rs"},
			{"Rio de Janeiro","br-rj"},
			{"Rondonia","br-ro"},
			{"Roraima","br-rr"},
			{"Santa Catarina","br-sc"},
			{"Sao Paulo","br-sp"},
			{"Sergipe","br-se"},
			{"Tocantins","br-to"},
			{"Freeport","bs-fp"},
			{"Fresh Creek","bs-fc"},
			{"Harbour Island","bs-hi"},
			{"High Rock","bs-hr"},
			{"Long Island","bs-li"},
			{"Marsh Harbour","bs-mh"},
			{"New Providence","bs-np"},
			{"Rock Sound","bs-rs"},
			{"Chhukha","bt-12"},
			{"Dagana","bt-22"},
			{"Gasa","bt-ga"},
			{"Ha","bt-13"},
			{"Monggar","bt-42"},
			{"Paro","bt-11"},
			{"Punakha","bt-23"},
			{"Thimphu","bt-15"},
			{"Trashi Yangtse","bt-ty"},
			{"Trongsa","bt-32"},
			{"Zhemgang","bt-34"},
			{"Central","bw-ce"},
			{"Ghanzi","bw-gh"},
			{"Kgalagadi","bw-kg"},
			{"Kgatleng","bw-kl"},
			{"Kweneng","bw-kw"},
			{"North-East","bw-ne"},
			{"North-West","bw-nw"},
			{"South-East","bw-se"},
			{"Southern","bw-so"},
			{"Brestskaya Voblasts'","by-br"},
			{"Homyel'skaya Voblasts'","by-ho"},
			{"Hrodzyenskaya Voblasts'","by-hr"},
			{"Mahilyowskaya Voblasts'","by-ma"},
			{"Minskaya Voblasts'","by-mi"},
			{"Vitsyebskaya Voblasts'","by-vi"},
			{"Belize","bz-bz"},
			{"Cayo","bz-cy"},
			{"Corozal","bz-czl"},
			{"Orange Walk","bz-ow"},
			{"Stann Creek","bz-sc"},
			{"Toledo","bz-tol"},
			{"Alberta","ca-ab"},
			{"British Columbia","ca-bc"},
			{"Manitoba","ca-mb"},
			{"New Brunswick","ca-nb"},
			{"Newfoundland and Labrador","ca-nl"},
			{"Northwest Territories","ca-nt"},
			{"Nova Scotia","ca-ns"},
			{"Nunavut","ca-nu"},
			{"Ontario","ca-on"},
			{"Prince Edward Island","ca-pe"},
			{"Quebec","ca-qc"},
			{"Saskatchewan","ca-sk"},
			{"Yukon","ca-yt"},
			{"Bandundu","cd-bn"},
			{"Bas-Congo","cd-bc"},
			{"Equateur","cd-eq"},
			{"Kasai-Occidental","cd-kw"},
			{"Kasai-Oriental","cd-ke"},
			{"Katanga","cd-ka"},
			{"Kinshasa","cd-kn"},
			{"Maniema","cd-ma"},
			{"Nord-Kivu","cd-nk"},
			{"Orientale","cd-or"},
			{"Sud-Kivu","cd-sk"},
			{"Bamingui-Bangoran","cf-bb"},
			{"Bangui","cf-bgf"},
			{"Basse-Kotto","cf-bk"},
			{"Haut-Mbomou","cf-hm"},
			{"Haute-Kotto","cf-hk"},
			{"Kemo","cf-kg"},
			{"Lobaye","cf-lb"},
			{"Mambere-Kadei","cf-hs"},
			{"Mbomou","cf-mb"},
			{"Nana-Grebizi","cf-kb"},
			{"Nana-Mambere","cf-nm"},
			{"Ombella-Mpoko","cf-mp"},
			{"Ouaka","cf-uk"},
			{"Ouham","cf-ac"},
			{"Ouham-Pende","cf-op"},
			{"Sangha-Mbaere","cf-se"},
			{"Bouenza","cg-11"},
			{"Brazzaville","cg-bzv"},
			{"Cuvette","cg-8"},
			{"Cuvette-Ouest","cg-15"},
			{"Lekoumou","cg-2"},
			{"Likouala","cg-7"},
			{"Niari","cg-9"},
			{"Plateaux","cg-14"},
			{"Pointe-Noire","cg-16"},
			{"Pool","cg-12"},
			{"Sangha","cg-13"},
			{"Aargau","ch-ag"},
			{"Appenzell Ausserrhoden","ch-ar"},
			{"Appenzell Innerrhoden","ch-ai"},
			{"Basel-Landschaft","ch-bl"},
			{"Basel-Stadt","ch-bs"},
			{"Bern","ch-be"},
			{"Fribourg","ch-fr"},
			{"Geneve","ch-ge"},
			{"Glarus","ch-gl"},
			{"Graubunden","ch-gr"},
			{"Jura","ch-ju"},
			{"Luzern","ch-lu"},
			{"Neuchatel","ch-ne"},
			{"Nidwalden","ch-nw"},
			{"Obwalden","ch-ow"},
			{"Sankt Gallen","ch-sg"},
			{"Schaffhausen","ch-sh"},
			{"Schwyz","ch-sz"},
			{"Solothurn","ch-so"},
			{"Thurgau","ch-tg"},
			{"Ticino","ch-ti"},
			{"Uri","ch-ur"},
			{"Valais","ch-vs"},
			{"Vaud","ch-vd"},
			{"Zug","ch-zg"},
			{"Zurich","ch-zh"},
			{"Agneby","ci-16"},
			{"Bafing","ci-17"},
			{"Bas-Sassandra","ci-09"},
			{"Denguele","ci-10"},
			{"Dix-Huit Montagnes","ci-06"},
			{"Fromager","ci-18"},
			{"Haut-Sassandra","ci-02"},
			{"Lacs","ci-07"},
			{"Lagunes","ci-01"},
			{"Marahoue","ci-12"},
			{"Moyen-Cavally","ci-19"},
			{"Moyen-Comoe","ci-05"},
			{"N'zi-Comoe","ci-11"},
			{"Savanes","ci-03"},
			{"Sud-Bandama","ci-15"},
			{"Sud-Comoe","ci-13"},
			{"Vallee du Bandama","ci-04"},
			{"Worodougou","ci-14"},
			{"Zanzan","ci-08"},
			{"Cook Islands","ck"},
			{"Antofagasta","cl-an"},
			{"Araucania","cl-ar"},
			{"Arica y Parinacota","cl-ap"},
			{"Atacama","cl-at"},
			{"Aysen","cl-ai"},
			{"Biobio","cl-bi"},
			{"Coquimbo","cl-co"},
			{"Libertador General Bernardo O'Higgins","cl-li"},
			{"Los Lagos","cl-ll"},
			{"Los Rios","cl-lr"},
			{"Magallanes","cl-ma"},
			{"Maule","cl-ml"},
			{"Region Metropolitana de Santiago","cl-rm"},
			{"Tarapaca","cl-ta"},
			{"Valparaiso","cl-vs"},
			{"Adamaoua","cm-ad"},
			{"Centre","cm-ce"},
			{"Est","cm-es"},
			{"Extreme-Nord","cm-en"},
			{"Littoral","bj-li"},
			{"Nord","cm-no"},
			{"Nord-Ouest","cm-nw"},
			{"Ouest","cm-ou"},
			{"Sud","cm-su"},
			{"Sud-Ouest","cm-sw"},
			{"Anhui","cn-34"},
			{"Beijing","cn-11"},
			{"Chongqing","cn-50"},
			{"Fujian","cn-35"},
			{"Gansu","cn-62"},
			{"Guangdong","cn-44"},
			{"Guangxi","cn-45"},
			{"Guizhou","cn-52"},
			{"Hainan","cn-46"},
			{"Hebei","cn-13"},
			{"Heilongjiang","cn-23"},
			{"Henan","cn-41"},
			{"Hubei","cn-42"},
			{"Hunan","cn-43"},
			{"Jiangsu","cn-32"},
			{"Jiangxi","cn-36"},
			{"Jilin","cn-22"},
			{"Liaoning","cn-21"},
			{"Nei Mongol","cn-15"},
			{"Ningxia","cn-64"},
			{"Qinghai","cn-63"},
			{"Shaanxi","cn-61"},
			{"Shandong","cn-37"},
			{"Shanghai","cn-31"},
			{"Shanxi","cn-14"},
			{"Sichuan","cn-51"},
			{"Tianjin","cn-12"},
			{"Xinjiang","cn-65"},
			{"Xizang","cn-54"},
			{"Yunnan","cn-53"},
			{"Zhejiang","cn-33"},
			{"Amazonas","br-am"},
			{"Antioquia","co-ant"},
			{"Arauca","co-ara"},
			{"Atlantico","co-atl"},
			{"Bolivar","co-bol"},
			{"Boyaca","co-boy"},
			{"Caldas","co-cal"},
			{"Caqueta","co-caq"},
			{"Casanare","co-cas"},
			{"Cauca","co-cau"},
			{"Cesar","co-ces"},
			{"Choco","co-cho"},
			{"Cordoba","ar-x"},
			{"Cundinamarca","co-cun"},
			{"Distrito Capital de Bogota","co-dc"},
			{"Guainia","co-gua"},
			{"Guaviare","co-guv"},
			{"Huila","ao-hui"},
			{"La Guajira","co-lag"},
			{"Magdalena","co-mag"},
			{"Meta","co-met"},
			{"Narino","co-nar"},
			{"Norte de Santander","co-nsa"},
			{"Putumayo","co-put"},
			{"Quindio","co-qui"},
			{"Risaralda","co-ris"},
			{"San Andres, Providencia y Santa Catalina","co-sap"},
			{"Santander","co-san"},
			{"Sucre","co-suc"},
			{"Tolima","co-tol"},
			{"Valle del Cauca","co-vac"},
			{"Vaupes","co-vau"},
			{"Vichada","co-vid"},
			{"Alajuela","cr-a"},
			{"Cartago","cr-c"},
			{"Guanacaste","cr-g"},
			{"Heredia","cr-h"},
			{"Limon","cr-l"},
			{"Puntarenas","cr-p"},
			{"San Jose","cr-sj"},
			{"Artemisa","cu-15"},
			{"Camaguey","cu-09"},
			{"Ciego de Avila","cu-08"},
			{"Cienfuegos","cu-06"},
			{"Granma","cu-12"},
			{"Guantanamo","cu-14"},
			{"Holguin","cu-11"},
			{"Isla de la Juventud","cu-99"},
			{"La Habana","cu-02"},
			{"Las Tunas","cu-10"},
			{"Matanzas","cu-04"},
			{"Mayabeque","cu-16"},
			{"Pinar del Rio","cu-01"},
			{"Sancti Spiritus","cu-07"},
			{"Santiago de Cuba","cu-13"},
			{"Villa Clara","cu-05"},
			{"Boa Vista","cv-bv"},
			{"Brava","cv-br"},
			{"Maio","cv-ma"},
			{"Mosteiros","cv-mo"},
			{"Paul","cv-pa"},
			{"Porto Novo","cv-pn"},
			{"Praia","cv-pr"},
			{"Ribeira Brava","cv-rb"},
			{"Ribeira Grande","cv-rg"},
			{"Ribeira Grande de Santiago","cv-rs"},
			{"Sal","cv-sl"},
			{"Santa Catarina","br-sc"},
			{"Santa Catarina do Fogo","cv-cf"},
			{"Santa Cruz","ar-z"},
			{"Sao Domingos","cv-sd"},
			{"Sao Filipe","cv-sf"},
			{"Sao Miguel","cv-sm"},
			{"Sao Salvador do Mundo","cv-ss"},
			{"Sao Vicente","cv-sv"},
			{"Tarrafal","cv-ta"},
			{"Tarrafal de Sao Nicolau","cv-ts"},
			{"Curacao","cw"},
			{"Christmas Island","cx"},
			{"Ammochostos","cy-04"},
			{"Keryneia","cy-06"},
			{"Larnaka","cy-03"},
			{"Lefkosia","cy-01"},
			{"Lemesos","cy-02"},
			{"Pafos","cy-05"},
			{"Jihocesky kraj","cz-jc"},
			{"Jihomoravsky kraj","cz-jm"},
			{"Karlovarsky kraj","cz-ka"},
			{"Kralovehradecky kraj","cz-kr"},
			{"Liberecky kraj","cz-li"},
			{"Moravskoslezsky kraj","cz-mo"},
			{"Olomoucky kraj","cz-ol"},
			{"Pardubicky kraj","cz-pa"},
			{"Plzensky kraj","cz-pl"},
			{"Praha, hlavni mesto","cz-pr"},
			{"Stredocesky kraj","cz-st"},
			{"Ustecky kraj","cz-us"},
			{"Vysocina kraj","cz-vy"},
			{"Zlinsky kraj","cz-zl"},
			{"Baden-Wurttemberg","de-bw"},
			{"Bayern","de-by"},
			{"Berlin","de-be"},
			{"Brandenburg","de-bb"},
			{"Bremen","de-hb"},
			{"Hamburg","de-hh"},
			{"Hessen","de-he"},
			{"Mecklenburg-Vorpommern","de-mv"},
			{"Niedersachsen","de-ni"},
			{"Nordrhein-Westfalen","de-nw"},
			{"Rheinland-Pfalz","de-rp"},
			{"Saarland","de-sl"},
			{"Sachsen","de-sn"},
			{"Sachsen-Anhalt","de-st"},
			{"Schleswig-Holstein","de-sh"},
			{"Thuringen","de-th"},
			{"Ali Sabieh","dj-as"},
			{"Arta","dj-ar"},
			{"Dikhil","dj-di"},
			{"Djibouti","dj-dj"},
			{"Obock","dj-ob"},
			{"Tadjourah","dj-ta"},
			{"Hovedstaden","dk-84"},
			{"Midtjylland","dk-82"},
			{"Nordjylland","dk-81"},
			{"Sjelland","dk-85"},
			{"Syddanmark","dk-83"},
			{"Saint Andrew","dm-02"},
			{"Saint David","dm-03"},
			{"Saint George","dm-04"},
			{"Saint John","ag-04"},
			{"Saint Joseph","bb-06"},
			{"Saint Luke","dm-07"},
			{"Saint Mark","dm-08"},
			{"Saint Patrick","dm-09"},
			{"Saint Paul","ag-06"},
			{"Azua","do-02"},
			{"Baoruco","do-03"},
			{"Barahona","do-04"},
			{"Dajabon","do-05"},
			{"Distrito Nacional","do-01"},
			{"Duarte","do-06"},
			{"El Seibo","do-08"},
			{"Elias Pina","do-07"},
			{"Espaillat","do-09"},
			{"Hato Mayor","do-30"},
			{"Independencia","do-10"},
			{"La Altagracia","do-11"},
			{"La Romana","do-12"},
			{"La Vega","do-13"},
			{"Maria Trinidad Sanchez","do-14"},
			{"Monsenor Nouel","do-28"},
			{"Monte Cristi","do-15"},
			{"Monte Plata","do-29"},
			{"Pedernales","do-16"},
			{"Peravia","do-17"},
			{"Puerto Plata","do-18"},
			{"Salcedo","do-19"},
			{"Samana","do-20"},
			{"San Cristobal","do-21"},
			{"San Juan","ar-j"},
			{"San Pedro De Macoris","do-23"},
			{"Sanchez Ramirez","do-24"},
			{"Santiago","do-25"},
			{"Santiago Rodriguez","do-26"},
			{"Valverde","do-27"},
			{"Adrar","dz-01"},
			{"Ain Defla","dz-44"},
			{"Ain Temouchent","dz-46"},
			{"Alger","dz-16"},
			{"Annaba","dz-23"},
			{"Batna","dz-05"},
			{"Bechar","dz-08"},
			{"Bejaia","dz-06"},
			{"Biskra","dz-07"},
			{"Blida","dz-09"},
			{"Bordj Bou Arreridj","dz-34"},
			{"Bouira","dz-10"},
			{"Boumerdes","dz-35"},
			{"Chlef","dz-02"},
			{"Constantine","dz-25"},
			{"Djelfa","dz-17"},
			{"El Bayadh","dz-32"},
			{"El Oued","dz-39"},
			{"El Tarf","dz-36"},
			{"Ghardaia","dz-47"},
			{"Guelma","dz-24"},
			{"Illizi","dz-33"},
			{"Khenchela","dz-40"},
			{"Laghouat","dz-03"},
			{"Mascara","dz-29"},
			{"Medea","dz-26"},
			{"Mila","dz-43"},
			{"Mostaganem","dz-27"},
			{"Msila","dz-28"},
			{"Naama","dz-45"},
			{"Oran","dz-31"},
			{"Ouargla","dz-30"},
			{"Oum el Bouaghi","dz-04"},
			{"Relizane","dz-48"},
			{"Saida","dz-20"},
			{"Setif","dz-19"},
			{"Sidi Bel Abbes","dz-22"},
			{"Skikda","dz-21"},
			{"Souk Ahras","dz-41"},
			{"Tamanrasset","dz-11"},
			{"Tebessa","dz-12"},
			{"Tiaret","dz-14"},
			{"Tindouf","dz-37"},
			{"Tipaza","dz-42"},
			{"Tissemsilt","dz-38"},
			{"Tizi Ouzou","dz-15"},
			{"Tlemcen","dz-13"},
			{"Azuay","ec-a"},
			{"Bolivar","co-bol"},
			{"Canar","ec-f"},
			{"Carchi","ec-c"},
			{"Chimborazo","ec-h"},
			{"Cotopaxi","ec-x"},
			{"El Oro","ec-o"},
			{"Esmeraldas","ec-e"},
			{"Galapagos","ec-w"},
			{"Guayas","ec-g"},
			{"Imbabura","ec-i"},
			{"Loja","ec-l"},
			{"Los Rios","cl-lr"},
			{"Manabi","ec-m"},
			{"Morona-Santiago","ec-s"},
			{"Napo","ec-n"},
			{"Orellana","ec-d"},
			{"Pastaza","ec-y"},
			{"Pichincha","ec-p"},
			{"Santa Elena","ec-se"},
			{"Sucumbios","ec-u"},
			{"Tungurahua","ec-t"},
			{"Zamora-Chinchipe","ec-z"},
			{"Harjumaa","ee-37"},
			{"Hiiumaa","ee-39"},
			{"Ida-Virumaa","ee-44"},
			{"Jarvamaa","ee-51"},
			{"Jogevamaa","ee-49"},
			{"Laane-Virumaa","ee-59"},
			{"Laanemaa","ee-57"},
			{"Parnumaa","ee-67"},
			{"Polvamaa","ee-65"},
			{"Raplamaa","ee-70"},
			{"Saaremaa","ee-74"},
			{"Tartumaa","ee-78"},
			{"Valgamaa","ee-82"},
			{"Viljandimaa","ee-84"},
			{"Vorumaa","ee-86"},
			{"Ad Daqahliyah","eg-dk"},
			{"Al Bahr al Ahmar","eg-ba"},
			{"Al Buhayrah","eg-bh"},
			{"Al Fayyum","eg-fym"},
			{"Al Gharbiyah","eg-gh"},
			{"Al Iskandariyah","eg-alx"},
			{"Al Ismailiyah","eg-is"},
			{"Al Jizah","eg-gz"},
			{"Al Minufiyah","eg-mnf"},
			{"Al Minya","eg-mn"},
			{"Al Qahirah","eg-c"},
			{"Al Qalyubiyah","eg-kb"},
			{"Al Uqsur","eg-lx"},
			{"Al Wadi al Jadid","eg-wad"},
			{"As Suways","eg-suz"},
			{"Ash Sharqiyah","eg-shr"},
			{"Aswan","eg-asn"},
			{"Asyut","eg-ast"},
			{"Bani Suwayf","eg-bns"},
			{"Bur Sa'id","eg-pts"},
			{"Dumyat","eg-dt"},
			{"Janub Sina'","eg-js"},
			{"Kafr ash Shaykh","eg-kfs"},
			{"Matruh","eg-mt"},
			{"Qina","eg-kn"},
			{"Shamal Sina'","eg-sin"},
			{"Suhaj","eg-shg"},
			{"Oued Ed-Dahab-Lagouira","ma-16"},
			{"Western Sahara","ma-14"},
			{"Al Awsat","er-ma"},
			{"Al Janubi","er-du"},
			{"Ansaba","er-an"},
			{"Janubi al Bahri al Ahmar","er-dk"},
			{"Qash-Barkah","er-gb"},
			{"Shimali al Bahri al Ahmar","er-sk"},
			{"Andalucia","es-an"},
			{"Aragon","es-ar"},
			{"Asturias, Principado de","es-as"},
			{"Canarias","es-cn"},
			{"Cantabria","es-cb"},
			{"Castilla y Leon","es-cl"},
			{"Castilla-La Mancha","es-cm"},
			{"Catalunya","es-ct"},
			{"Ceuta","es-ce"},
			{"Extremadura","es-ex"},
			{"Galicia","es-ga"},
			{"Illes Balears","es-ib"},
			{"La Rioja","ar-f"},
			{"Madrid, Comunidad de","es-md"},
			{"Melilla","es-ml"},
			{"Murcia, Region de","es-mc"},
			{"Navarra, Comunidad Foral de","es-nc"},
			{"Pais Vasco","es-pv"},
			{"Valenciana, Comunidad","es-vc"},
			{"Adis Abeba","et-aa"},
			{"Afar","et-af"},
			{"Amara","et-am"},
			{"Binshangul Gumuz","et-be"},
			{"Dire Dawa","et-dd"},
			{"Gambela Hizboch","et-ga"},
			{"Hareri Hizb","et-ha"},
			{"Oromiya","et-or"},
			{"Sumale","et-so"},
			{"Tigray","et-ti"},
			{"YeDebub Biheroch Bihereseboch na Hizboch","et-sn"},
			{"Etela-Karjala","fi-02"},
			{"Etela-Pohjanmaa","fi-03"},
			{"Etela-Savo","fi-04"},
			{"Kainuu","fi-05"},
			{"Kanta-Hame","fi-06"},
			{"Keski-Pohjanmaa","fi-07"},
			{"Keski-Suomi","fi-08"},
			{"Kymenlaakso","fi-09"},
			{"Lappi","fi-10"},
			{"Paijat-Hame","fi-16"},
			{"Pirkanmaa","fi-11"},
			{"Pohjanmaa","fi-12"},
			{"Pohjois-Karjala","fi-13"},
			{"Pohjois-Pohjanmaa","fi-14"},
			{"Pohjois-Savo","fi-15"},
			{"Satakunta","fi-17"},
			{"Uusimaa","fi-18"},
			{"Varsinais-Suomi","fi-19"},
			{"Central","bw-ce"},
			{"Northern","fj-n"},
			{"Western","fj-w"},
			{"Chuuk","fm-trk"},
			{"Kosrae","fm-ksa"},
			{"Pohnpei","fm-pni"},
			{"Yap","fm-yap"},
			{"Alsace","fr-a"},
			{"Aquitaine","fr-b"},
			{"Auvergne","fr-c"},
			{"Basse-Normandie","fr-p"},
			{"Bourgogne","fr-d"},
			{"Bretagne","fr-e"},
			{"Centre","cm-ce"},
			{"Champagne-Ardenne","fr-g"},
			{"Corse","fr-h"},
			{"Franche-Comte","fr-i"},
			{"Haute-Normandie","fr-q"},
			{"Ile-de-France","fr-j"},
			{"Languedoc-Roussillon","fr-k"},
			{"Limousin","fr-l"},
			{"Lorraine","fr-m"},
			{"Midi-Pyrenees","fr-n"},
			{"Nord-Pas-de-Calais","fr-o"},
			{"Pays de la Loire","fr-r"},
			{"Picardie","fr-s"},
			{"Poitou-Charentes","fr-t"},
			{"Provence-Alpes-Cote d'Azur","fr-u"},
			{"Rhone-Alpes","fr-v"},
			{"Estuaire","ga-1"},
			{"Haut-Ogooue","ga-2"},
			{"Moyen-Ogooue","ga-3"},
			{"Ngounie","ga-4"},
			{"Nyanga","ga-5"},
			{"Ogooue-Ivindo","ga-6"},
			{"Ogooue-Lolo","ga-7"},
			{"Ogooue-Maritime","ga-8"},
			{"Woleu-Ntem","ga-9"},
			{"England","gb-eng"},
			{"Northern Ireland","gb-nir"},
			{"Scotland","gb-sct"},
			{"Wales","gb-wls"},
			{"Saint Andrew","dm-02"},
			{"Saint David","dm-03"},
			{"Saint George","dm-04"},
			{"Saint John","ag-04"},
			{"Saint Mark","dm-08"},
			{"Saint Patrick","dm-09"},
			{"Abkhazia","ge-ab"},
			{"Ajaria","ge-aj"},
			{"Akhalk'alak'is Raioni","ge-04"},
			{"Baghdat'is Raioni","ge-09"},
			{"Borjomis Raioni","ge-11"},
			{"Goris Raioni","ge-19"},
			{"Guria","ge-gu"},
			{"Imereti","ge-im"},
			{"Javis Raioni","ge-23"},
			{"K'arelis Raioni","ge-24"},
			{"Kakheti","ge-ka"},
			{"Khashuris Raioni","ge-28"},
			{"Kvemo Kartli","ge-kk"},
			{"Mtskheta-Mtianeti","ge-mm"},
			{"Racha-Lechkhumi and Kvemo Svaneti","ge-rl"},
			{"Samegrelo and Zemo Svaneti","ge-sz"},
			{"Samtskhe-Javakheti","ge-sj"},
			{"Shida Kartli","ge-sk"},
			{"T'bilisi","ge-tbs"},
			{"Vanis Raioni","ge-61"},
			{"Ashanti","gh-ah"},
			{"Brong-Ahafo","gh-ba"},
			{"Central","bw-ce"},
			{"Eastern","gh-ep"},
			{"Greater Accra","gh-aa"},
			{"Northern","fj-n"},
			{"Upper East","gh-ue"},
			{"Upper West","gh-uw"},
			{"Volta","gh-tv"},
			{"Western","fj-w"},
			{"Gibraltar","gi"},
			{"Kommune Kujalleq","gl-ku"},
			{"Kommuneqarfik Sermersooq","gl-sm"},
			{"Qaasuitsup Kommunia","gl-qa"},
			{"Qeqqata Kommunia","gl-qe"},
			{"Banjul","gm-b"},
			{"Central River","gm-m"},
			{"Lower River","gm-l"},
			{"North Bank","gm-n"},
			{"Upper River","gm-u"},
			{"Western","fj-w"},
			{"Beyla","gn-be"},
			{"Boffa","gn-bf"},
			{"Boke","gn-bk"},
			{"Conakry","gn-c"},
			{"Coyah","gn-co"},
			{"Dabola","gn-db"},
			{"Dalaba","gn-dl"},
			{"Dinguiraye","gn-di"},
			{"Dubreka","gn-du"},
			{"Faranah","gn-fa"},
			{"Forecariah","gn-fo"},
			{"Fria","gn-fr"},
			{"Gaoual","gn-ga"},
			{"Gueckedou","gn-gu"},
			{"Kankan","gn-ka"},
			{"Kerouane","gn-ke"},
			{"Kindia","gn-kd"},
			{"Kissidougou","gn-ks"},
			{"Koubia","gn-kb"},
			{"Koundara","gn-kn"},
			{"Kouroussa","gn-ko"},
			{"Labe","gn-la"},
			{"Lelouma","gn-le"},
			{"Lola","gn-lo"},
			{"Macenta","gn-mc"},
			{"Mali","gn-ml"},
			{"Mamou","gn-mm"},
			{"Mandiana","gn-md"},
			{"Nzerekore","gn-nz"},
			{"Pita","gn-pi"},
			{"Siguiri","gn-si"},
			{"Telimele","gn-te"},
			{"Tougue","gn-to"},
			{"Yomou","gn-yo"},
			{"Guadeloupe","gp"},
			{"Annobon","gq-an"},
			{"Bioko Norte","gq-bn"},
			{"Bioko Sur","gq-bs"},
			{"Centro Sur","gq-cs"},
			{"Kie-Ntem","gq-kn"},
			{"Litoral","gq-li"},
			{"Wele-Nzas","gq-wn"},
			{"Aitolia kai Akarnania","gr-01"},
			{"Akhaia","gr-13"},
			{"Argolis","gr-11"},
			{"Arkadhia","gr-12"},
			{"Arta","dj-ar"},
			{"Attiki","gr-a1"},
			{"Dhodhekanisos","gr-81"},
			{"Drama","gr-52"},
			{"Evritania","gr-05"},
			{"Evros","gr-71"},
			{"Evvoia","gr-04"},
			{"Florina","gr-63"},
			{"Fokis","gr-07"},
			{"Fthiotis","gr-06"},
			{"Grevena","gr-51"},
			{"Ilia","gr-14"},
			{"Imathia","gr-53"},
			{"Ioannina","gr-33"},
			{"Iraklion","gr-91"},
			{"Kardhitsa","gr-41"},
			{"Kastoria","gr-56"},
			{"Kavala","gr-55"},
			{"Kefallinia","gr-23"},
			{"Kerkira","gr-22"},
			{"Khalkidhiki","gr-64"},
			{"Khania","gr-94"},
			{"Khios","gr-85"},
			{"Kikladhes","gr-82"},
			{"Kilkis","gr-57"},
			{"Korinthia","gr-15"},
			{"Kozani","gr-58"},
			{"Lakonia","gr-16"},
			{"Larisa","gr-42"},
			{"Lasithi","gr-92"},
			{"Lesvos","gr-83"},
			{"Levkas","gr-24"},
			{"Magnisia","gr-43"},
			{"Messinia","gr-17"},
			{"Pella","gr-59"},
			{"Pieria","gr-61"},
			{"Preveza","gr-34"},
			{"Rethimni","gr-93"},
			{"Rodhopi","gr-73"},
			{"Samos","gr-84"},
			{"Serrai","gr-62"},
			{"Thesprotia","gr-32"},
			{"Thessaloniki","gr-54"},
			{"Trikala","gr-44"},
			{"Voiotia","gr-03"},
			{"Xanthi","gr-72"},
			{"Zakinthos","gr-21"},
			{"Alta Verapaz","gt-av"},
			{"Baja Verapaz","gt-bv"},
			{"Chimaltenango","gt-cm"},
			{"Chiquimula","gt-cq"},
			{"El Progreso","gt-pr"},
			{"Escuintla","gt-es"},
			{"Guatemala","gt-gu"},
			{"Huehuetenango","gt-hu"},
			{"Izabal","gt-iz"},
			{"Jalapa","gt-ja"},
			{"Jutiapa","gt-ju"},
			{"Peten","gt-pe"},
			{"Quetzaltenango","gt-qz"},
			{"Quiche","gt-qc"},
			{"Retalhuleu","gt-re"},
			{"Sacatepequez","gt-sa"},
			{"San Marcos","gt-sm"},
			{"Santa Rosa","gt-sr"},
			{"Solola","gt-so"},
			{"Suchitepequez","gt-su"},
			{"Totonicapan","gt-to"},
			{"Zacapa","gt-za"},
			{"Bafata","gw-ba"},
			{"Biombo","gw-bm"},
			{"Bissau","gw-bs"},
			{"Bolama","gw-bl"},
			{"Cacheu","gw-ca"},
			{"Gabu","gw-ga"},
			{"Oio","gw-oi"},
			{"Quinara","gw-qu"},
			{"Tombali","gw-to"},
			{"Cuyuni-Mazaruni","gy-cu"},
			{"Demerara-Mahaica","gy-de"},
			{"East Berbice-Corentyne","gy-eb"},
			{"Essequibo Islands-West Demerara","gy-es"},
			{"Mahaica-Berbice","gy-ma"},
			{"Pomeroon-Supenaam","gy-pm"},
			{"Upper Demerara-Berbice","gy-ud"},
			{"Atlantida","hn-at"},
			{"Choluteca","hn-ch"},
			{"Colon","hn-cl"},
			{"Comayagua","hn-cm"},
			{"Copan","hn-cp"},
			{"Cortes","hn-cr"},
			{"El Paraiso","hn-ep"},
			{"Francisco Morazan","hn-fm"},
			{"Gracias a Dios","hn-gd"},
			{"Intibuca","hn-in"},
			{"Islas de la Bahia","hn-ib"},
			{"La Paz","bo-l"},
			{"Lempira","hn-le"},
			{"Ocotepeque","hn-oc"},
			{"Olancho","hn-ol"},
			{"Santa Barbara","hn-sb"},
			{"Valle","hn-va"},
			{"Yoro","hn-yo"},
			{"Bjelovarsko-bilogorska zupanija","hr-07"},
			{"Brodsko-posavska zupanija","hr-12"},
			{"Dubrovacko-neretvanska zupanija","hr-19"},
			{"Grad Zagreb","hr-21"},
			{"Istarska zupanija","hr-18"},
			{"Karlovacka zupanija","hr-04"},
			{"Koprivnicko-krizevacka zupanija","hr-06"},
			{"Krapinsko-zagorska zupanija","hr-02"},
			{"Licko-senjska zupanija","hr-09"},
			{"Medimurska zupanija","hr-20"},
			{"Osjecko-baranjska zupanija","hr-14"},
			{"Pozesko-slavonska zupanija","hr-11"},
			{"Primorsko-goranska zupanija","hr-08"},
			{"Sibensko-kninska zupanija","hr-15"},
			{"Sisacko-moslavacka zupanija","hr-03"},
			{"Splitsko-dalmatinska zupanija","hr-17"},
			{"Varazdinska zupanija","hr-05"},
			{"Viroviticko-podravska zupanija","hr-10"},
			{"Vukovarsko-srijemska zupanija","hr-16"},
			{"Zadarska zupanija","hr-13"},
			{"Zagrebacka zupanija","hr-01"},
			{"Artibonite","ht-ar"},
			{"Centre","cm-ce"},
			{"Grand' Anse","ht-ga"},
			{"Nippes","ht-ni"},
			{"Nord","cm-no"},
			{"Nord-Est","ht-ne"},
			{"Nord-Ouest","cm-nw"},
			{"Ouest","cm-ou"},
			{"Sud","cm-su"},
			{"Sud-Est","ht-se"},
			{"Bacs-Kiskun","hu-bk"},
			{"Baranya","hu-ba"},
			{"Bekes","hu-be"},
			{"Borsod-Abauj-Zemplen","hu-bz"},
			{"Budapest","hu-bu"},
			{"Csongrad","hu-cs"},
			{"Fejer","hu-fe"},
			{"Gyor-Moson-Sopron","hu-gs"},
			{"Hajdu-Bihar","hu-hb"},
			{"Heves","hu-he"},
			{"Jasz-Nagykun-Szolnok","hu-jn"},
			{"Komarom-Esztergom","hu-ke"},
			{"Nograd","hu-no"},
			{"Pest","hu-pe"},
			{"Somogy","hu-so"},
			{"Szabolcs-Szatmar-Bereg","hu-sz"},
			{"Tolna","hu-to"},
			{"Vas","hu-va"},
			{"Veszprem","hu-ve"},
			{"Zala","hu-za"},
			{"Aceh","id-ac"},
			{"Bali","id-ba"},
			{"Bangka Belitung","id-bb"},
			{"Banten","id-bt"},
			{"Bengkulu","id-be"},
			{"Gorontalo","id-go"},
			{"Jakarta Raya","id-jk"},
			{"Jambi","id-ja"},
			{"Jawa Barat","id-jb"},
			{"Jawa Tengah","id-jt"},
			{"Jawa Timur","id-ji"},
			{"Kalimantan Barat","id-kb"},
			{"Kalimantan Selatan","id-ks"},
			{"Kalimantan Tengah","id-kt"},
			{"Kalimantan Timur","id-ki"},
			{"Kepulauan Riau","id-kr"},
			{"Lampung","id-la"},
			{"Maluku","id-ma"},
			{"Maluku Utara","id-mu"},
			{"Nusa Tenggara Barat","id-nb"},
			{"Nusa Tenggara Timur","id-nt"},
			{"Papua","id-pa"},
			{"Papua Barat","id-pb"},
			{"Riau","id-ri"},
			{"Sulawesi Barat","id-sr"},
			{"Sulawesi Selatan","id-sn"},
			{"Sulawesi Tengah","id-st"},
			{"Sulawesi Tenggara","id-sg"},
			{"Sulawesi Utara","id-sa"},
			{"Sumatera Barat","id-sb"},
			{"Sumatera Selatan","id-ss"},
			{"Sumatera Utara","id-su"},
			{"Yogyakarta","id-yo"},
			{"Carlow","ie-cw"},
			{"Cavan","ie-cn"},
			{"Clare","ie-ce"},
			{"Cork","ie-co"},
			{"Donegal","ie-dl"},
			{"Dublin","ie-d"},
			{"Galway","ie-g"},
			{"Kerry","ie-ky"},
			{"Kildare","ie-ke"},
			{"Kilkenny","ie-kk"},
			{"Laois","ie-ls"},
			{"Leitrim","ie-lm"},
			{"Limerick","ie-lk"},
			{"Longford","ie-ld"},
			{"Louth","ie-lh"},
			{"Mayo","ie-mo"},
			{"Meath","ie-mh"},
			{"Monaghan","ie-mn"},
			{"Offaly","ie-oy"},
			{"Roscommon","ie-rn"},
			{"Sligo","ie-so"},
			{"Tipperary","ie-ta"},
			{"Waterford","ie-wd"},
			{"Westmeath","ie-wh"},
			{"Wexford","ie-wx"},
			{"Wicklow","ie-ww"},
			{"HaDarom","il-d"},
			{"HaMerkaz","il-m"},
			{"HaTsafon","il-z"},
			{"Hefa","il-ha"},
			{"Tel-Aviv","il-ta"},
			{"Yerushalayim","il-jm"},
			{"Isle of Man","im"},
			{"Andaman and Nicobar Islands","in-an"},
			{"Andhra Pradesh","in-ap"},
			{"Arunachal Pradesh","in-ar"},
			{"Assam","in-as"},
			{"Bihar","in-br"},
			{"Chandigarh","in-ch"},
			{"Chhattisgarh","in-ct"},
			{"Dadra and Nagar Haveli","in-dn"},
			{"Daman and Diu","in-dd"},
			{"Delhi","in-dl"},
			{"Goa","in-ga"},
			{"Gujarat","in-gj"},
			{"Haryana","in-hr"},
			{"Himachal Pradesh","in-hp"},
			{"Jammu and Kashmir","in-jk"},
			{"Jharkhand","in-jh"},
			{"Karnataka","in-ka"},
			{"Kerala","in-kl"},
			{"Lakshadweep","in-ld"},
			{"Madhya Pradesh","in-mp"},
			{"Maharashtra","in-mh"},
			{"Manipur","in-mn"},
			{"Meghalaya","in-ml"},
			{"Mizoram","in-mz"},
			{"Nagaland","in-nl"},
			{"Odisha","in-or"},
			{"Puducherry","in-py"},
			{"Punjab","in-pb"},
			{"Rajasthan","in-rj"},
			{"Sikkim","in-sk"},
			{"Tamil Nadu","in-tn"},
			{"Telangana","in-tg"},
			{"Tripura","in-tr"},
			{"Uttar Pradesh","in-up"},
			{"Uttarakhand","in-ut"},
			{"West Bengal","in-wb"},
			{"British Indian Ocean Territory","io"},
			{"Al Anbar","iq-an"},
			{"Al Basrah","iq-ba"},
			{"Al Muthanna","iq-mu"},
			{"Al Qadisiyah","iq-qa"},
			{"An Najaf","iq-na"},
			{"Arbil","iq-ar"},
			{"As Sulaymaniyah","iq-su"},
			{"Babil","iq-bb"},
			{"Baghdad","iq-bg"},
			{"Dahuk","iq-da"},
			{"Dhi Qar","iq-dq"},
			{"Diyala","iq-di"},
			{"Karbala'","iq-ka"},
			{"Kirkuk","iq-ki"},
			{"Maysan","iq-ma"},
			{"Ninawa","iq-ni"},
			{"Salah ad Din","iq-sd"},
			{"Wasit","iq-wa"},
			{"Alborz","ir-32"},
			{"Ardabil","ir-03"},
			{"Azarbayjan-e Gharbi","ir-02"},
			{"Azarbayjan-e Sharqi","ir-01"},
			{"Bushehr","ir-06"},
			{"Chahar Mahal va Bakhtiari","ir-08"},
			{"Esfahan","ir-04"},
			{"Fars","ir-14"},
			{"Gilan","ir-19"},
			{"Golestan","ir-27"},
			{"Hamadan","ir-24"},
			{"Hormozgan","ir-23"},
			{"Ilam","ir-05"},
			{"Kerman","ir-15"},
			{"Kermanshah","ir-17"},
			{"Khorasan-e Jonubi","ir-29"},
			{"Khorasan-e Razavi","ir-30"},
			{"Khorasan-e Shomali","ir-31"},
			{"Khuzestan","ir-10"},
			{"Kohgiluyeh va Bowyer Ahmad","ir-18"},
			{"Kordestan","ir-16"},
			{"Lorestan","ir-20"},
			{"Markazi","ir-22"},
			{"Mazandaran","ir-21"},
			{"Qazvin","ir-28"},
			{"Qom","ir-26"},
			{"Semnan","ir-12"},
			{"Sistan va Baluchestan","ir-13"},
			{"Tehran","ir-07"},
			{"Yazd","ir-25"},
			{"Zanjan","ir-11"},
			{"Austurland","is-7"},
			{"Hofudborgarsvaedi utan Reykjavikur","is-1"},
			{"Nordurland eystra","is-6"},
			{"Nordurland vestra","is-5"},
			{"Sudurland","is-8"},
			{"Sudurnes","is-2"},
			{"Vestfirdir","is-4"},
			{"Vesturland","is-3"},
			{"Abruzzo","it-65"},
			{"Basilicata","it-77"},
			{"Calabria","it-78"},
			{"Campania","it-72"},
			{"Emilia-Romagna","it-45"},
			{"Friuli-Venezia Giulia","it-36"},
			{"Lazio","it-62"},
			{"Liguria","it-42"},
			{"Lombardia","it-25"},
			{"Marche","it-57"},
			{"Molise","it-67"},
			{"Piemonte","it-21"},
			{"Puglia","it-75"},
			{"Sardegna","it-88"},
			{"Sicilia","it-82"},
			{"Toscana","it-52"},
			{"Trentino-Alto Adige","it-32"},
			{"Umbria","it-55"},
			{"Valle d'Aosta","it-23"},
			{"Veneto","it-34"},
			{"Jersey","je"},
			{"Clarendon","jm-13"},
			{"Hanover","jm-09"},
			{"Kingston","jm-01"},
			{"Manchester","jm-12"},
			{"Portland","jm-04"},
			{"Saint Andrew","dm-02"},
			{"Saint Ann","jm-06"},
			{"Saint Catherine","jm-14"},
			{"Saint Elizabeth","jm-11"},
			{"Saint James","bb-04"},
			{"Saint Mary","ag-05"},
			{"Saint Thomas","jm-03"},
			{"Trelawny","jm-07"},
			{"Westmoreland","jm-10"},
			{"Al 'Aqabah","jo-aq"},
			{"Al 'Asimah","jo-am"},
			{"Al Balqa'","jo-ba"},
			{"Al Karak","jo-ka"},
			{"Al Mafraq","jo-ma"},
			{"At Tafilah","jo-at"},
			{"Az Zarqa'","jo-az"},
			{"Irbid","jo-ir"},
			{"Ma'an","jo-mn"},
			{"Madaba","jo-md"},
			{"Aichi","jp-23"},
			{"Akita","jp-05"},
			{"Aomori","jp-02"},
			{"Chiba","jp-12"},
			{"Ehime","jp-38"},
			{"Fukui","jp-18"},
			{"Fukuoka","jp-40"},
			{"Fukushima","jp-07"},
			{"Gifu","jp-21"},
			{"Gunma","jp-10"},
			{"Hiroshima","jp-34"},
			{"Hokkaido","jp-01"},
			{"Hyogo","jp-28"},
			{"Ibaraki","jp-08"},
			{"Ishikawa","jp-17"},
			{"Iwate","jp-03"},
			{"Kagawa","jp-37"},
			{"Kagoshima","jp-46"},
			{"Kanagawa","jp-14"},
			{"Kochi","jp-39"},
			{"Kumamoto","jp-43"},
			{"Kyoto","jp-26"},
			{"Mie","jp-24"},
			{"Miyagi","jp-04"},
			{"Miyazaki","jp-45"},
			{"Nagano","jp-20"},
			{"Nagasaki","jp-42"},
			{"Nara","jp-29"},
			{"Niigata","jp-15"},
			{"Oita","jp-44"},
			{"Okayama","jp-33"},
			{"Okinawa","jp-47"},
			{"Osaka","jp-27"},
			{"Saga","jp-41"},
			{"Saitama","jp-11"},
			{"Shiga","jp-25"},
			{"Shimane","jp-32"},
			{"Shizuoka","jp-22"},
			{"Tochigi","jp-09"},
			{"Tokushima","jp-36"},
			{"Tokyo","jp-13"},
			{"Tottori","jp-31"},
			{"Toyama","jp-16"},
			{"Wakayama","jp-30"},
			{"Yamagata","jp-06"},
			{"Yamaguchi","jp-35"},
			{"Yamanashi","jp-19"},
			{"Central","bw-ce"},
			{"Coast","ke-300"},
			{"Eastern","gh-ep"},
			{"Nairobi Area","ke-110"},
			{"North-Eastern","ke-500"},
			{"Nyanza","ke-600"},
			{"Rift Valley","ke-700"},
			{"Western","fj-w"},
			{"Batken","kg-b"},
			{"Bishkek","kg-gb"},
			{"Chu","kg-c"},
			{"Jalal-Abad","kg-j"},
			{"Naryn","kg-n"},
			{"Osh","kg-o"},
			{"Talas","kg-t"},
			{"Ysyk-Kol","kg-y"},
			{"Baat Dambang","kh-2"},
			{"Banteay Mean Chey","kh-1"},
			{"Kampong Chaam","kh-3"},
			{"Kampong Chhnang","kh-4"},
			{"Kampong Spueu","kh-5"},
			{"Kampong Thum","kh-6"},
			{"Kampot","kh-7"},
			{"Kandaal","kh-8"},
			{"Kaoh Kong","kh-9"},
			{"Kracheh","kh-10"},
			{"Krong Kaeb","kh-23"},
			{"Krong Pailin","kh-24"},
			{"Krong Preah Sihanouk","kh-18"},
			{"Mondol Kiri","kh-11"},
			{"Otdar Mean Chey","kh-22"},
			{"Phnom Penh","kh-12"},
			{"Pousaat","kh-15"},
			{"Preah Vihear","kh-13"},
			{"Prey Veaeng","kh-14"},
			{"Rotanak Kiri","kh-16"},
			{"Siem Reab","kh-17"},
			{"Stueng Traeng","kh-19"},
			{"Svaay Rieng","kh-20"},
			{"Taakaev","kh-21"},
			{"Gilbert Islands","ki-g"},
			{"Line Islands","ki-l"},
			{"Anjouan","km-a"},
			{"Grande Comore","km-g"},
			{"Moheli","km-m"},
			{"Saint George Basseterre","kn-03"},
			{"Saint Paul Charlestown","kn-09"},
			{"Chagang-do","kp-04"},
			{"Hamgyong-bukto","kp-09"},
			{"Hamgyong-namdo","kp-08"},
			{"Hwanghae-bukto","kp-06"},
			{"Hwanghae-namdo","kp-05"},
			{"Kangwon-do","kp-07"},
			{"Nason (Najin-Sonbong)","kp-13"},
			{"P'yongan-bukto","kp-03"},
			{"P'yongan-namdo","kp-02"},
			{"P'yongyang","kp-01"},
			{"Yanggang-do","kp-10"},
			{"Busan","kr-26"},
			{"Chungbuk","kr-43"},
			{"Chungnam","kr-44"},
			{"Daegu","kr-27"},
			{"Daejeon","kr-30"},
			{"Gangwon","kr-42"},
			{"Gwangju","kr-29"},
			{"Gyeongbuk","kr-47"},
			{"Gyeonggi","kr-41"},
			{"Gyeongnam","kr-48"},
			{"Incheon","kr-28"},
			{"Jeju","kr-49"},
			{"Jeonbuk","kr-45"},
			{"Jeonnam","kr-46"},
			{"Seoul","kr-11"},
			{"Ulsan","kr-31"},
			{"Al Ahmadi","kw-ah"},
			{"Al Asimah","bh-13"},
			{"Al Farwaniyah","kw-fa"},
			{"Al Jahra","kw-ja"},
			{"Hawalli","kw-ha"},
			{"Mubarak al Kabir","kw-mu"},
			{"Cayman Islands","ky"},
			{"Almaty","kz-ala"},
			{"Almaty oblysy","kz-alm"},
			{"Aqmola oblysy","kz-akm"},
			{"Aqtobe oblysy","kz-akt"},
			{"Astana","kz-ast"},
			{"Atyrau oblysy","kz-aty"},
			{"Batys Qazaqstan oblysy","kz-zap"},
			{"Bayqonyr","kz-zap"},
			{"Mangghystau oblysy","kz-man"},
			{"Ongtustik Qazaqstan oblysy","kz-yuz"},
			{"Pavlodar oblysy","kz-pav"},
			{"Qaraghandy oblysy","kz-kar"},
			{"Qostanay oblysy","kz-kus"},
			{"Qyzylorda oblysy","kz-kzy"},
			{"Shyghys Qazaqstan oblysy","kz-vos"},
			{"Soltustik Qazaqstan oblysy","kz-sev"},
			{"Zhambyl oblysy","kz-zha"},
			{"Attapu","la-at"},
			{"Bokeo","la-bk"},
			{"Bolikhamxai","la-bl"},
			{"Champasak","la-ch"},
			{"Houaphan","la-ho"},
			{"Khammouan","la-kh"},
			{"Louang Namtha","la-lm"},
			{"Louangphabang","la-lp"},
			{"Oudomxai","la-ou"},
			{"Phongsali","la-ph"},
			{"Salavan","la-sl"},
			{"Savannakhet","la-sv"},
			{"Vientiane","la-vi"},
			{"Xaignabouli","la-xa"},
			{"Xekong","la-xe"},
			{"Xiangkhouang","la-xi"},
			{"Aakkar","lb-ak"},
			{"Baalbek-Hermel","lb-bh"},
			{"Beqaa","lb-bi"},
			{"Beyrouth","lb-ba"},
			{"Liban-Nord","lb-as"},
			{"Liban-Sud","lb-ja"},
			{"Mont-Liban","lb-jl"},
			{"Nabatiye","lb-na"},
			{"Anse la Raye","lc-01"},
			{"Castries","lc-02"},
			{"Dennery","lc-05"},
			{"Gros Islet","lc-06"},
			{"Laborie","lc-07"},
			{"Micoud","lc-08"},
			{"Soufriere","lc-10"},
			{"Vieux Fort","lc-11"},
			{"Balzers","li-01"},
			{"Eschen","li-02"},
			{"Gamprin","li-03"},
			{"Mauren","li-04"},
			{"Planken","li-05"},
			{"Ruggell","li-06"},
			{"Schaan","li-07"},
			{"Schellenberg","li-08"},
			{"Triesen","li-09"},
			{"Triesenberg","li-10"},
			{"Vaduz","li-11"},
			{"Central Province","lk-2"},
			{"Eastern Province","lk-5"},
			{"North Central Province","lk-7"},
			{"North Western Province","lk-6"},
			{"Northern Province","lk-4"},
			{"Sabaragamuwa Province","lk-9"},
			{"Southern Province","lk-3"},
			{"Uva Province","lk-8"},
			{"Western Province","lk-1"},
			{"Bomi","lr-bm"},
			{"Bong","lr-bg"},
			{"Gbarpolu","lr-gp"},
			{"Grand Bassa","lr-gb"},
			{"Grand Cape Mount","lr-cm"},
			{"Grand Gedeh","lr-gg"},
			{"Grand Kru","lr-gk"},
			{"Lofa","lr-lo"},
			{"Margibi","lr-mg"},
			{"Maryland","lr-my"},
			{"Montserrado","lr-mo"},
			{"Nimba","lr-ni"},
			{"River Cess","lr-ri"},
			{"River Gee","lr-rg"},
			{"Sinoe","lr-si"},
			{"Berea","ls-d"},
			{"Butha-Buthe","ls-b"},
			{"Leribe","ls-c"},
			{"Mafeteng","ls-e"},
			{"Maseru","ls-a"},
			{"Mohale's Hoek","ls-f"},
			{"Mokhotlong","ls-j"},
			{"Qacha's Nek","ls-h"},
			{"Quthing","ls-g"},
			{"Thaba-Tseka","ls-k"},
			{"Alytaus Apskritis","lt-al"},
			{"Kauno Apskritis","lt-ku"},
			{"Klaipedos Apskritis","lt-kl"},
			{"Marijampoles Apskritis","lt-mr"},
			{"Panevezio Apskritis","lt-pn"},
			{"Siauliu Apskritis","lt-sa"},
			{"Taurages Apskritis","lt-ta"},
			{"Telsiu Apskritis","lt-te"},
			{"Utenos Apskritis","lt-ut"},
			{"Vilniaus Apskritis","lt-vl"},
			{"Diekirch","lu-d"},
			{"Grevenmacher","lu-g"},
			{"Luxembourg","be-wlx"},
			{"Adazu","lv-011"},
			{"Aglonas","lv-001"},
			{"Aizkraukles","lv-002"},
			{"Aizputes","lv-003"},
			{"Alojas","lv-005"},
			{"Aluksnes","lv-007"},
			{"Babites","lv-012"},
			{"Baltinavas","lv-014"},
			{"Balvu","lv-015"},
			{"Bauskas","lv-016"},
			{"Beverinas","lv-017"},
			{"Brocenu","lv-018"},
			{"Carnikavas","lv-020"},
			{"Cesu","lv-022"},
			{"Cesvaines","lv-021"},
			{"Ciblas","lv-023"},
			{"Daugavpils","lv-025"},
			{"Dobeles","lv-026"},
			{"Dundagas","lv-027"},
			{"Gulbenes","lv-033"},
			{"Iecavas","lv-034"},
			{"Incukalna","lv-037"},
			{"Jaunjelgavas","lv-038"},
			{"Jaunpiebalgas","lv-039"},
			{"Jaunpils","lv-040"},
			{"Jekabpils","lv-042"},
			{"Jelgava","lv-jel"},
			{"Jelgavas","lv-041"},
			{"Jurmala","lv-jur"},
			{"Kekavas","lv-052"},
			{"Kokneses","lv-046"},
			{"Kraslavas","lv-047"},
			{"Kuldigas","lv-050"},
			{"Liepaja","lv-lpx"},
			{"Liepajas","lv-le"},
			{"Limbazu","lv-lm"},
			{"Lubanas","lv-057"},
			{"Ludzas","lv-058"},
			{"Madonas","lv-059"},
			{"Malpils","lv-061"},
			{"Ogres","lv-067"},
			{"Olaines","lv-068"},
			{"Ozolnieku","lv-069"},
			{"Preilu","lv-073"},
			{"Rezeknes","lv-077"},
			{"Riga","lv-rix"},
			{"Rigas","lv-ri"},
			{"Rojas","lv-079"},
			{"Ropazu","lv-080"},
			{"Rugaju","lv-082"},
			{"Rundales","lv-083"},
			{"Salacgrivas","lv-086"},
			{"Saldus","lv-088"},
			{"Sejas","lv-090"},
			{"Siguldas","lv-091"},
			{"Skrundas","lv-093"},
			{"Stopinu","lv-095"},
			{"Strencu","lv-096"},
			{"Talsu","lv-097"},
			{"Tukuma","lv-099"},
			{"Vainodes","lv-100"},
			{"Valkas","lv-101"},
			{"Valmieras","lv-vm"},
			{"Varkavas","lv-103"},
			{"Vecumnieku","lv-105"},
			{"Ventspils","lv-106"},
			{"Al Butnan","ly-bu"},
			{"Al Jabal al Akhdar","ly-ja"},
			{"Al Jabal al Gharbi","ly-jg"},
			{"Al Jafarah","ly-ji"},
			{"Al Jufrah","ly-ju"},
			{"Al Kufrah","ly-kf"},
			{"Al Marj","ly-mj"},
			{"Al Marqab","ly-mb"},
			{"Al Wahat","ly-wa"},
			{"An Nuqat al Khams","ly-nq"},
			{"Az Zawiyah","ly-za"},
			{"Banghazi","ly-ba"},
			{"Darnah","ly-dr"},
			{"Ghat","ly-gt"},
			{"Misratah","ly-mi"},
			{"Murzuq","ly-mq"},
			{"Nalut","ly-nl"},
			{"Sabha","ly-sb"},
			{"Surt","ly-sr"},
			{"Tarabulus","ly-tb"},
			{"Wadi al Hayat","ly-wd"},
			{"Wadi ash Shati'","ly-ws"},
			{"Chaouia-Ouardigha","ma-09"},
			{"Doukhala-Abda","ma-10"},
			{"Fes-Boulemane","ma-05"},
			{"Gharb-Chrarda-Beni Hssen","ma-02"},
			{"Grand Casablanca","ma-08"},
			{"Guelmim-Es Semara","ma-14"},
			{"L'Oriental","ma-04"},
			{"Marrakech-Tensift-Al Haouz","ma-11"},
			{"Meknes-Tafilalet","ma-06"},
			{"Rabat-Sale-Zemmour-Zaer","ma-07"},
			{"Souss-Massa-Draa","ma-13"},
			{"Tadla-Azilal","ma-12"},
			{"Tanger-Tetouan","ma-01"},
			{"Taza-Al Hoceima-Taounate","ma-03"},
			{"Monaco","mc-mo"},
			{"Anenii Noi","md-an"},
			{"Balti","md-ba"},
			{"Basarabeasca","md-bs"},
			{"Bender","md-ti"},
			{"Briceni","md-br"},
			{"Cahul","md-ca"},
			{"Calarasi","md-cl"},
			{"Cantemir","md-ct"},
			{"Causeni","md-cs"},
			{"Chisinau","md-cu"},
			{"Cimislia","md-cm"},
			{"Criuleni","md-cr"},
			{"Donduseni","md-do"},
			{"Drochia","md-dr"},
			{"Dubasari","md-du"},
			{"Edinet","md-ed"},
			{"Falesti","md-fa"},
			{"Floresti","md-fl"},
			{"Gagauzia, Unitatea teritoriala autonoma","md-ga"},
			{"Glodeni","md-gl"},
			{"Hincesti","md-hi"},
			{"Ialoveni","md-ia"},
			{"Leova","md-le"},
			{"Nisporeni","md-ni"},
			{"Ocnita","md-oc"},
			{"Orhei","md-or"},
			{"Rezina","md-re"},
			{"Riscani","md-ri"},
			{"Singerei","md-si"},
			{"Soldanesti","md-sd"},
			{"Soroca","md-so"},
			{"Stefan Voda","md-sv"},
			{"Stinga Nistrului, unitatea teritoriala din","md-sn"},
			{"Straseni","md-st"},
			{"Taraclia","md-ta"},
			{"Telenesti","md-te"},
			{"Ungheni","md-un"},
			{"Bar","me-02"},
			{"Budva","me-05"},
			{"Cetinje","me-06"},
			{"Danilovgrad","me-07"},
			{"Herceg-Novi","me-08"},
			{"Kolasin","me-09"},
			{"Kotor","me-10"},
			{"Mojkovac","me-11"},
			{"Niksic","me-12"},
			{"Podgorica","me-16"},
			{"Tivat","me-19"},
			{"Ulcinj","me-20"},
			{"Zabljak","me-21"},
			{"Antananarivo","mg-t"},
			{"Antsiranana","mg-d"},
			{"Fianarantsoa","mg-f"},
			{"Mahajanga","mg-m"},
			{"Toamasina","mg-a"},
			{"Toliara","mg-u"},
			{"Ailinglaplap Atoll","mh-all"},
			{"Ailuk Atoll","mh-alk"},
			{"Arno Atoll","mh-arn"},
			{"Aur Atoll","mh-aur"},
			{"Ebon Atoll","mh-ebo"},
			{"Enewetak Atoll","mh-eni"},
			{"Jabat Island","mh-jab"},
			{"Jaluit Atoll","mh-jal"},
			{"Kili Island","mh-kil"},
			{"Kwajalein Atoll","mh-kwa"},
			{"Lae Atoll","mh-lae"},
			{"Lib Island","mh-lib"},
			{"Likiep Atoll","mh-lik"},
			{"Majuro Atoll","mh-maj"},
			{"Maloelap Atoll","mh-mal"},
			{"Mejit Island","mh-mej"},
			{"Mili Atoll","mh-mil"},
			{"Namdrik Atoll","mh-nmk"},
			{"Namu Atoll","mh-nmu"},
			{"Rongelap Atoll","mh-ron"},
			{"Ujae Atoll","mh-uja"},
			{"Utrik Atoll","mh-uti"},
			{"Wotho Atoll","mh-wth"},
			{"Wotje Atoll","mh-wtj"},
			{"Aracinovo","mk-02"},
			{"Berovo","mk-03"},
			{"Bitola","mk-04"},
			{"Bogdanci","mk-05"},
			{"Bogovinje","mk-06"},
			{"Bosilovo","mk-07"},
			{"Brvenica","mk-08"},
			{"Caska","mk-80"},
			{"Centar Zupa","mk-78"},
			{"Cesinovo-Oblesevo","mk-81"},
			{"Cucer Sandevo","mk-82"},
			{"Debar","mk-21"},
			{"Debarca","mk-22"},
			{"Delcevo","mk-23"},
			{"Demir Hisar","mk-25"},
			{"Demir Kapija","mk-24"},
			{"Dojran","mk-26"},
			{"Dolneni","mk-27"},
			{"Gevgelija","mk-18"},
			{"Gostivar","mk-19"},
			{"Gradsko","mk-20"},
			{"Ilinden","mk-34"},
			{"Jegunovce","mk-35"},
			{"Karbinci","mk-37"},
			{"Kavadarci","mk-36"},
			{"Kicevo","mk-40"},
			{"Kocani","mk-42"},
			{"Konce","mk-41"},
			{"Kratovo","mk-43"},
			{"Kriva Palanka","mk-44"},
			{"Krivogastani","mk-45"},
			{"Krusevo","mk-46"},
			{"Kumanovo","mk-47"},
			{"Lipkovo","mk-48"},
			{"Lozovo","mk-49"},
			{"Makedonska Kamenica","mk-51"},
			{"Makedonski Brod","mk-52"},
			{"Mavrovo i Rostusa","mk-50"},
			{"Mogila","mk-53"},
			{"Negotino","mk-54"},
			{"Novaci","mk-55"},
			{"Novo Selo","mk-56"},
			{"Ohrid","mk-58"},
			{"Pehcevo","mk-60"},
			{"Petrovec","mk-59"},
			{"Plasnica","mk-61"},
			{"Prilep","mk-62"},
			{"Probistip","mk-63"},
			{"Radovis","mk-64"},
			{"Rankovce","mk-65"},
			{"Resen","mk-66"},
			{"Rosoman","mk-67"},
			{"Skopje","mk-85"},
			{"Sopiste","mk-70"},
			{"Staro Nagoricane","mk-71"},
			{"Stip","mk-83"},
			{"Struga","mk-72"},
			{"Strumica","mk-73"},
			{"Studenicani","mk-74"},
			{"Sveti Nikole","mk-69"},
			{"Tearce","mk-75"},
			{"Tetovo","mk-76"},
			{"Valandovo","mk-10"},
			{"Vasilevo","mk-11"},
			{"Veles","mk-13"},
			{"Vevcani","mk-12"},
			{"Vinica","mk-14"},
			{"Vrapciste","mk-16"},
			{"Zelenikovo","mk-32"},
			{"Zelino","mk-30"},
			{"Zrnovci","mk-33"},
			{"Bamako","ml-bko"},
			{"Gao","ml-7"},
			{"Kayes","ml-1"},
			{"Kidal","ml-8"},
			{"Koulikoro","ml-2"},
			{"Mopti","ml-5"},
			{"Segou","ml-4"},
			{"Sikasso","ml-3"},
			{"Tombouctou","ml-6"},
			{"Ayeyawady","mm-07"},
			{"Bago","mm-02"},
			{"Chin","mm-14"},
			{"Kachin","mm-11"},
			{"Kayah","mm-12"},
			{"Kayin","mm-13"},
			{"Magway","mm-03"},
			{"Mandalay","mm-04"},
			{"Mon","mm-15"},
			{"Nay Pyi Taw","mm-18"},
			{"Rakhine","mm-16"},
			{"Sagaing","mm-01"},
			{"Shan","mm-17"},
			{"Taninthayi","mm-05"},
			{"Yangon","mm-06"},
			{"Arhangay","mn-073"},
			{"Bayan-Olgiy","mn-071"},
			{"Bayanhongor","mn-069"},
			{"Bulgan","mn-067"},
			{"Darhan uul","mn-037"},
			{"Dornod","mn-061"},
			{"Dornogovi","mn-063"},
			{"Dundgovi","mn-059"},
			{"Dzavhan","mn-057"},
			{"Govi-Altay","mn-065"},
			{"Govi-Sumber","mn-064"},
			{"Hentiy","mn-039"},
			{"Hovd","mn-043"},
			{"Hovsgol","mn-041"},
			{"Omnogovi","mn-053"},
			{"Orhon","mn-035"},
			{"Ovorhangay","mn-055"},
			{"Selenge","mn-049"},
			{"Suhbaatar","mn-051"},
			{"Tov","mn-047"},
			{"Ulaanbaatar","mn-1"},
			{"Uvs","mn-046"},
			{"Northern Mariana Islands","mp"},
			{"Martinique","mq"},
			{"Adrar","dz-01"},
			{"Assaba","mr-03"},
			{"Brakna","mr-05"},
			{"Dakhlet Nouadhibou","mr-08"},
			{"Gorgol","mr-04"},
			{"Guidimaka","mr-10"},
			{"Hodh Ech Chargui","mr-01"},
			{"Hodh El Gharbi","mr-02"},
			{"Inchiri","mr-12"},
			{"Nouakchott","mr-nkc"},
			{"Tagant","mr-09"},
			{"Tiris Zemmour","mr-11"},
			{"Trarza","mr-06"},
			{"Malta","mt"},
			{"Black River","mu-bl"},
			{"Flacq","mu-fl"},
			{"Grand Port","mu-gp"},
			{"Moka","mu-mo"},
			{"Pamplemousses","mu-pa"},
			{"Plaines Wilhems","mu-pw"},
			{"Port Louis","mu-pl"},
			{"Riviere du Rempart","mu-rr"},
			{"Savanne","mu-sa"},
			{"Alifu","mv-02"},
			{"Baa","mv-20"},
			{"Dhaalu","mv-17"},
			{"Gaafu Dhaalu","mv-28"},
			{"Haa Alifu","mv-07"},
			{"Haa Dhaalu","mv-23"},
			{"Kaafu","mv-26"},
			{"Laamu","mv-05"},
			{"Maale","mv-mle"},
			{"Meemu","mv-12"},
			{"Noonu","mv-25"},
			{"Raa","mv-13"},
			{"Seenu","mv-01"},
			{"Shaviyani","mv-24"},
			{"Thaa","mv-08"},
			{"Balaka","mw-ba"},
			{"Blantyre","mw-bl"},
			{"Chikwawa","mw-ck"},
			{"Chiradzulu","mw-cr"},
			{"Chitipa","mw-ct"},
			{"Dedza","mw-de"},
			{"Dowa","mw-do"},
			{"Karonga","mw-kr"},
			{"Kasungu","mw-ks"},
			{"Likoma","mw-lk"},
			{"Lilongwe","mw-li"},
			{"Machinga","mw-mh"},
			{"Mangochi","mw-mg"},
			{"Mchinji","mw-mc"},
			{"Mulanje","mw-mu"},
			{"Mwanza","mw-mw"},
			{"Mzimba","mw-mz"},
			{"Neno","mw-ne"},
			{"Nkhata Bay","mw-nb"},
			{"Nkhotakota","mw-nk"},
			{"Nsanje","mw-ns"},
			{"Ntcheu","mw-nu"},
			{"Ntchisi","mw-ni"},
			{"Phalombe","mw-ph"},
			{"Rumphi","mw-ru"},
			{"Salima","mw-sa"},
			{"Thyolo","mw-th"},
			{"Zomba","mw-zo"},
			{"Aguascalientes","mx-agu"},
			{"Baja California","mx-bcn"},
			{"Baja California Sur","mx-bcs"},
			{"Campeche","mx-cam"},
			{"Chiapas","mx-chp"},
			{"Chihuahua","mx-chh"},
			{"Coahuila","mx-coa"},
			{"Colima","mx-col"},
			{"Distrito Federal","br-df"},
			{"Durango","mx-dur"},
			{"Guanajuato","mx-gua"},
			{"Guerrero","mx-gro"},
			{"Hidalgo","mx-hid"},
			{"Jalisco","mx-jal"},
			{"Mexico","mx-mex"},
			{"Michoacan","mx-mic"},
			{"Morelos","mx-mor"},
			{"Nayarit","mx-nay"},
			{"Nuevo Leon","mx-nle"},
			{"Oaxaca","mx-oax"},
			{"Puebla","mx-pue"},
			{"Queretaro","mx-que"},
			{"Quintana Roo","mx-roo"},
			{"San Luis Potosi","mx-slp"},
			{"Sinaloa","mx-sin"},
			{"Sonora","mx-son"},
			{"Tabasco","mx-tab"},
			{"Tamaulipas","mx-tam"},
			{"Tlaxcala","mx-tla"},
			{"Veracruz","mx-ver"},
			{"Yucatan","mx-yuc"},
			{"Zacatecas","mx-zac"},
			{"Johor","my-01"},
			{"Kedah","my-02"},
			{"Kelantan","my-03"},
			{"Melaka","my-04"},
			{"Negeri Sembilan","my-05"},
			{"Pahang","my-06"},
			{"Perak","my-08"},
			{"Perlis","my-09"},
			{"Pulau Pinang","my-07"},
			{"Sabah","my-12"},
			{"Sarawak","my-13"},
			{"Selangor","my-10"},
			{"Terengganu","my-11"},
			{"Wilayah Persekutuan Kuala Lumpur","my-14"},
			{"Wilayah Persekutuan Labuan","my-15"},
			{"Wilayah Persekutuan Putrajaya","my-16"},
			{"Cabo Delgado","mz-p"},
			{"Gaza","mz-g"},
			{"Inhambane","mz-i"},
			{"Manica","mz-b"},
			{"Maputo","mz-l"},
			{"Nampula","mz-n"},
			{"Niassa","mz-a"},
			{"Sofala","mz-s"},
			{"Tete","mz-t"},
			{"Zambezia","mz-q"},
			{"Erongo","na-er"},
			{"Hardap","na-ha"},
			{"Karas","na-ka"},
			{"Khomas","na-kh"},
			{"Kunene","na-ku"},
			{"Ohangwena","na-ow"},
			{"Omaheke","na-oh"},
			{"Omusati","na-os"},
			{"Oshana","na-on"},
			{"Oshikoto","na-ot"},
			{"Otjozondjupa","na-od"},
			{"Zambezi","na-ca"},
			{"Agadez","ne-1"},
			{"Diffa","ne-2"},
			{"Dosso","ne-3"},
			{"Maradi","ne-4"},
			{"Niamey","ne-8"},
			{"Tahoua","ne-5"},
			{"Tillaberi","ne-6"},
			{"Zinder","ne-7"},
			{"Norfolk Island","nf"},
			{"Abia","ng-ab"},
			{"Abuja Federal Capital Territory","ng-fc"},
			{"Adamawa","ng-ad"},
			{"Akwa Ibom","ng-ak"},
			{"Anambra","ng-an"},
			{"Bauchi","ng-ba"},
			{"Bayelsa","ng-by"},
			{"Benue","ng-be"},
			{"Borno","ng-bo"},
			{"Cross River","ng-cr"},
			{"Delta","ng-de"},
			{"Ebonyi","ng-eb"},
			{"Edo","ng-ed"},
			{"Ekiti","ng-ek"},
			{"Enugu","ng-en"},
			{"Gombe","ng-go"},
			{"Imo","ng-im"},
			{"Jigawa","ng-ji"},
			{"Kaduna","ng-kd"},
			{"Kano","ng-kn"},
			{"Katsina","ng-kt"},
			{"Kebbi","ng-ke"},
			{"Kogi","ng-ko"},
			{"Kwara","ng-kw"},
			{"Lagos","ng-la"},
			{"Nasarawa","ng-na"},
			{"Niger","ng-ni"},
			{"Ogun","ng-og"},
			{"Ondo","ng-on"},
			{"Osun","ng-os"},
			{"Oyo","ng-oy"},
			{"Plateau","bj-pl"},
			{"Rivers","ng-ri"},
			{"Sokoto","ng-so"},
			{"Taraba","ng-ta"},
			{"Yobe","ng-yo"},
			{"Zamfara","ng-za"},
			{"Atlantico Norte","ni-an"},
			{"Atlantico Sur","ni-as"},
			{"Boaco","ni-bo"},
			{"Carazo","ni-ca"},
			{"Chinandega","ni-ci"},
			{"Chontales","ni-co"},
			{"Esteli","ni-es"},
			{"Granada","ni-gr"},
			{"Jinotega","ni-ji"},
			{"Leon","ni-le"},
			{"Madriz","ni-md"},
			{"Managua","ni-mn"},
			{"Masaya","ni-ms"},
			{"Matagalpa","ni-mt"},
			{"Nueva Segovia","ni-ns"},
			{"Rio San Juan","ni-sj"},
			{"Rivas","ni-ri"},
			{"Drenthe","nl-dr"},
			{"Flevoland","nl-fl"},
			{"Fryslan","nl-fr"},
			{"Gelderland","nl-ge"},
			{"Groningen","nl-gr"},
			{"Limburg","bg-vli"},
			{"Noord-Brabant","nl-nb"},
			{"Noord-Holland","nl-nh"},
			{"Overijssel","nl-ov"},
			{"Utrecht","nl-ut"},
			{"Zeeland","nl-ze"},
			{"Zuid-Holland","nl-zh"},
			{"Akershus","no-02"},
			{"Aust-Agder","no-09"},
			{"Buskerud","no-06"},
			{"Finnmark","no-20"},
			{"Hedmark","no-04"},
			{"Hordaland","no-12"},
			{"More og Romsdal","no-15"},
			{"Nord-Trondelag","no-17"},
			{"Nordland","no-18"},
			{"Oppland","no-05"},
			{"Oslo","no-03"},
			{"Ostfold","no-01"},
			{"Rogaland","no-11"},
			{"Sogn og Fjordane","no-14"},
			{"Sor-Trondelag","no-16"},
			{"Telemark","no-08"},
			{"Troms","no-19"},
			{"Vest-Agder","no-10"},
			{"Vestfold","no-07"},
			{"Bagmati","np-ba"},
			{"Bheri","np-bh"},
			{"Dhawalagiri","np-dh"},
			{"Gandaki","np-ga"},
			{"Janakpur","np-ja"},
			{"Karnali","np-ka"},
			{"Kosi","np-ko"},
			{"Lumbini","np-lu"},
			{"Mahakali","np-ma"},
			{"Mechi","np-me"},
			{"Narayani","np-na"},
			{"Rapti","np-ra"},
			{"Sagarmatha","np-sa"},
			{"Seti","np-se"},
			{"Yaren","nr-14"},
			{"Niue","nu"},
			{"Auckland","nz-auk"},
			{"Bay of Plenty","nz-bop"},
			{"Canterbury","nz-can"},
			{"Chatham Islands","nz-cit"},
			{"Gisborne","nz-gis"},
			{"Hawke's Bay","nz-hkb"},
			{"Manawatu-Wanganui","nz-mwt"},
			{"Marlborough","nz-mbh"},
			{"Nelson","nz-nsn"},
			{"Northland","nz-ntl"},
			{"Otago","nz-ota"},
			{"Southland","nz-stl"},
			{"Taranaki","nz-tki"},
			{"Tasman","nz-tas"},
			{"Waikato","nz-wko"},
			{"Wellington","nz-wgn"},
			{"West Coast","nz-wtc"},
			{"Ad Dakhiliyah","om-da"},
			{"Al Buraymi","om-bu"},
			{"Al Wusta","bh-16"},
			{"Az Zahirah","om-za"},
			{"Janub al Batinah","om-bs"},
			{"Janub ash Sharqiyah","om-ss"},
			{"Masqat","om-ma"},
			{"Musandam","om-mu"},
			{"Shamal al Batinah","om-bj"},
			{"Shamal ash Sharqiyah","om-sj"},
			{"Zufar","om-zu"},
			{"Bocas del Toro","pa-1"},
			{"Chiriqui","pa-4"},
			{"Cocle","pa-2"},
			{"Colon","hn-cl"},
			{"Darien","pa-5"},
			{"Herrera","pa-6"},
			{"Los Santos","pa-7"},
			{"Panama","pa-8"},
			{"San Blas","pa-0"},
			{"Veraguas","pa-9"},
			{"Amazonas","br-am"},
			{"Ancash","pe-anc"},
			{"Apurimac","pe-apu"},
			{"Arequipa","pe-are"},
			{"Ayacucho","pe-aya"},
			{"Cajamarca","pe-caj"},
			{"Callao","pe-cal"},
			{"Cusco","pe-cus"},
			{"Huancavelica","pe-huv"},
			{"Huanuco","pe-huc"},
			{"Ica","pe-ica"},
			{"Junin","pe-jun"},
			{"La Libertad","pe-lal"},
			{"Lambayeque","pe-lam"},
			{"Lima","pe-lim"},
			{"Loreto","pe-lor"},
			{"Madre de Dios","pe-mdd"},
			{"Moquegua","pe-moq"},
			{"Pasco","pe-pas"},
			{"Piura","pe-piu"},
			{"Puno","pe-pun"},
			{"San Martin","pe-sam"},
			{"Tacna","pe-tac"},
			{"Tumbes","pe-tum"},
			{"Ucayali","pe-uca"},
			{"Bougainville","pg-nsb"},
			{"Chimbu","pg-cpk"},
			{"East New Britain","pg-ebr"},
			{"East Sepik","pg-esw"},
			{"Eastern Highlands","pg-ehg"},
			{"Enga","pg-epw"},
			{"Gulf","pg-gpk"},
			{"Madang","pg-mpm"},
			{"Manus","pg-mrl"},
			{"Milne Bay","pg-mba"},
			{"Morobe","pg-mpl"},
			{"National Capital District","pg-ncd"},
			{"New Ireland","pg-nik"},
			{"Northern","fj-n"},
			{"Southern Highlands","pg-shm"},
			{"West New Britain","pg-wbk"},
			{"West Sepik","pg-san"},
			{"Western","fj-w"},
			{"Western Highlands","pg-whm"},
			{"Abra","ph-abr"},
			{"Agusan del Norte","ph-agn"},
			{"Agusan del Sur","ph-ags"},
			{"Aklan","ph-akl"},
			{"Albay","ph-alb"},
			{"Antique","ph-ant"},
			{"Apayao","ph-apa"},
			{"Aurora","ph-aur"},
			{"Basilan","ph-bas"},
			{"Bataan","ph-ban"},
			{"Batanes","ph-btn"},
			{"Batangas","ph-btg"},
			{"Benguet","ph-ben"},
			{"Bohol","ph-boh"},
			{"Bukidnon","ph-buk"},
			{"Bulacan","ph-bul"},
			{"Cagayan","ph-cag"},
			{"Camarines Norte","ph-can"},
			{"Camarines Sur","ph-cas"},
			{"Camiguin","ph-cam"},
			{"Capiz","ph-cap"},
			{"Catanduanes","ph-cat"},
			{"Cavite","ph-cav"},
			{"Cebu","ph-ceb"},
			{"Cotabato","ph-nco"},
			{"Davao Oriental","ph-dao"},
			{"Davao del Sur","ph-das"},
			{"Eastern Samar","ph-eas"},
			{"Ifugao","ph-ifu"},
			{"Ilocos Norte","ph-iln"},
			{"Ilocos Sur","ph-ils"},
			{"Iloilo","ph-ili"},
			{"Isabela","ph-isa"},
			{"Kalinga","ph-kal"},
			{"La Union","ph-lun"},
			{"Laguna","ph-lag"},
			{"Lanao del Norte","ph-lan"},
			{"Lanao del Sur","ph-las"},
			{"Leyte","ph-ley"},
			{"Maguindanao","ph-mag"},
			{"Marinduque","ph-mad"},
			{"Masbate","ph-mas"},
			{"Mindoro Occidental","ph-mdc"},
			{"Mindoro Oriental","ph-mdr"},
			{"Misamis Occidental","ph-msc"},
			{"Misamis Oriental","ph-msr"},
			{"Mountain Province","ph-mou"},
			{"National Capital Region","ph-00"},
			{"Negros Occidental","ph-nec"},
			{"Negros Oriental","ph-ner"},
			{"Northern Samar","ph-nsa"},
			{"Nueva Ecija","ph-nue"},
			{"Nueva Vizcaya","ph-nuv"},
			{"Palawan","ph-plw"},
			{"Pampanga","ph-pam"},
			{"Pangasinan","ph-pan"},
			{"Quezon","ph-que"},
			{"Quirino","ph-qui"},
			{"Rizal","ph-riz"},
			{"Romblon","ph-rom"},
			{"Samar (Western Samar)","ph-wsa"},
			{"Siquijor","ph-sig"},
			{"Sorsogon","ph-sor"},
			{"South Cotabato","ph-sco"},
			{"Southern Leyte","ph-sle"},
			{"Sultan Kudarat","ph-suk"},
			{"Sulu","ph-slu"},
			{"Surigao del Norte","ph-sun"},
			{"Surigao del Sur","ph-sur"},
			{"Tarlac","ph-tar"},
			{"Tawi-Tawi","ph-taw"},
			{"Zambales","ph-zmb"},
			{"Zamboanga del Norte","ph-zan"},
			{"Zamboanga del Sur","ph-zas"},
			{"Azad Kashmir","pk-jk"},
			{"Balochistan","pk-ba"},
			{"Federally Administered Tribal Areas","pk-ta"},
			{"Gilgit-Baltistan","pk-gb"},
			{"Islamabad","pk-is"},
			{"Khyber Pakhtunkhwa","pk-kp"},
			{"Punjab","in-pb"},
			{"Sindh","pk-sd"},
			{"Dolnoslaskie","pl-ds"},
			{"Kujawsko-Pomorskie","pl-kp"},
			{"Lodzkie","pl-ld"},
			{"Lubelskie","pl-lu"},
			{"Lubuskie","pl-lb"},
			{"Malopolskie","pl-ma"},
			{"Mazowieckie","pl-mz"},
			{"Opolskie","pl-op"},
			{"Podkarpackie","pl-pk"},
			{"Podlaskie","pl-pd"},
			{"Pomorskie","pl-pm"},
			{"Slaskie","pl-sl"},
			{"Swietokrzyskie","pl-sk"},
			{"Warminsko-Mazurskie","pl-wn"},
			{"Wielkopolskie","pl-wp"},
			{"Zachodniopomorskie","pl-zp"},
			{"Saint Pierre and Miquelon","pm"},
			{"Aveiro","pt-01"},
			{"Beja","pt-02"},
			{"Braga","pt-03"},
			{"Braganca","pt-04"},
			{"Castelo Branco","pt-05"},
			{"Coimbra","pt-06"},
			{"Evora","pt-07"},
			{"Faro","pt-08"},
			{"Guarda","pt-09"},
			{"Leiria","pt-10"},
			{"Lisboa","pt-11"},
			{"Portalegre","pt-12"},
			{"Porto","pt-13"},
			{"Regiao Autonoma da Madeira","pt-30"},
			{"Regiao Autonoma dos Acores","pt-20"},
			{"Santarem","pt-14"},
			{"Setubal","pt-15"},
			{"Viana do Castelo","pt-16"},
			{"Vila Real","pt-17"},
			{"Viseu","pt-18"},
			{"Aimeliik","pw-002"},
			{"Airai","pw-004"},
			{"Angaur","pw-010"},
			{"Kayangel","pw-100"},
			{"Koror","pw-150"},
			{"Melekeok","pw-212"},
			{"Ngaraard","pw-214"},
			{"Ngarchelong","pw-218"},
			{"Ngardmau","pw-222"},
			{"Ngatpang","pw-224"},
			{"Ngiwal","pw-228"},
			{"Peleliu","pw-350"},
			{"Alto Paraguay","py-16"},
			{"Alto Parana","py-10"},
			{"Amambay","py-13"},
			{"Asuncion","py-asu"},
			{"Boqueron","py-19"},
			{"Caaguazu","py-5"},
			{"Caazapa","py-6"},
			{"Canindeyu","py-14"},
			{"Central","bw-ce"},
			{"Concepcion","py-1"},
			{"Cordillera","py-3"},
			{"Guaira","py-4"},
			{"Itapua","py-7"},
			{"Misiones","ar-n"},
			{"Neembucu","py-12"},
			{"Paraguari","py-9"},
			{"Presidente Hayes","py-15"},
			{"San Pedro","py-2"},
			{"Ad Dawhah","qa-da"},
			{"Al Khawr wa adh Dhakhirah","qa-kh"},
			{"Al Wakrah","qa-wa"},
			{"Ar Rayyan","qa-ra"},
			{"Ash Shamal","qa-ms"},
			{"Az Za'ayin","qa-za"},
			{"Umm Salal","qa-us"},
			{"Reunion","re"},
			{"Alba","ro-ab"},
			{"Arad","ro-ar"},
			{"Arges","ro-ag"},
			{"Bacau","ro-bc"},
			{"Bihor","ro-bh"},
			{"Bistrita-Nasaud","ro-bn"},
			{"Botosani","ro-bt"},
			{"Braila","ro-br"},
			{"Brasov","ro-bv"},
			{"Bucuresti","ro-b"},
			{"Buzau","ro-bz"},
			{"Calarasi","md-cl"},
			{"Caras-Severin","ro-cs"},
			{"Cluj","ro-cj"},
			{"Constanta","ro-ct"},
			{"Covasna","ro-cv"},
			{"Dambovita","ro-db"},
			{"Dolj","ro-dj"},
			{"Galati","ro-gl"},
			{"Giurgiu","ro-gr"},
			{"Gorj","ro-gj"},
			{"Harghita","ro-hr"},
			{"Hunedoara","ro-hd"},
			{"Ialomita","ro-il"},
			{"Iasi","ro-is"},
			{"Ilfov","ro-if"},
			{"Maramures","ro-mm"},
			{"Mehedinti","ro-mh"},
			{"Mures","ro-ms"},
			{"Neamt","ro-nt"},
			{"Olt","ro-ot"},
			{"Prahova","ro-ph"},
			{"Salaj","ro-sj"},
			{"Satu Mare","ro-sm"},
			{"Sibiu","ro-sb"},
			{"Suceava","ro-sv"},
			{"Teleorman","ro-tr"},
			{"Timis","ro-tm"},
			{"Tulcea","ro-tl"},
			{"Valcea","ro-vl"},
			{"Vaslui","ro-vs"},
			{"Vrancea","ro-vn"},
			{"Adygeya, Respublika","ru-ad"},
			{"Altay, Respublika","ru-al"},
			{"Altayskiy kray","ru-alt"},
			{"Amurskaya oblast'","ru-amu"},
			{"Arkhangel'skaya oblast'","ru-ark"},
			{"Astrakhanskaya oblast'","ru-ast"},
			{"Bashkortostan, Respublika","ru-ba"},
			{"Belgorodskaya oblast'","ru-bel"},
			{"Bryanskaya oblast'","ru-bry"},
			{"Buryatiya, Respublika","ru-bu"},
			{"Chechenskaya Respublika","ru-ce"},
			{"Chelyabinskaya oblast'","ru-che"},
			{"Chukotskiy avtonomnyy okrug","ru-chu"},
			{"Chuvashskaya Respublika","ru-cu"},
			{"Dagestan, Respublika","ru-da"},
			{"Ingushetiya, Respublika","ru-in"},
			{"Irkutskaya oblast'","ru-irk"},
			{"Ivanovskaya oblast'","ru-iva"},
			{"Kabardino-Balkarskaya Respublika","ru-kb"},
			{"Kaliningradskaya oblast'","ru-kgd"},
			{"Kalmykiya, Respublika","ru-kl"},
			{"Kaluzhskaya oblast'","ru-klu"},
			{"Kamchatskiy kray","ru-kam"},
			{"Karachayevo-Cherkesskaya Respublika","ru-kc"},
			{"Kareliya, Respublika","ru-kr"},
			{"Kemerovskaya oblast'","ru-kem"},
			{"Khabarovskiy kray","ru-kha"},
			{"Khakasiya, Respublika","ru-kk"},
			{"Khanty-Mansiyskiy avtonomnyy okrug-Yugra","ru-khm"},
			{"Kirovskaya oblast'","ru-kir"},
			{"Komi, Respublika","ru-ko"},
			{"Kostromskaya oblast'","ru-kos"},
			{"Krasnodarskiy kray","ru-kda"},
			{"Krasnoyarskiy kray","ru-kya"},
			{"Kurganskaya oblast'","ru-kgn"},
			{"Kurskaya oblast'","ru-krs"},
			{"Leningradskaya oblast'","ru-len"},
			{"Lipetskaya oblast'","ru-lip"},
			{"Magadanskaya oblast'","ru-mag"},
			{"Mariy El, Respublika","ru-me"},
			{"Mordoviya, Respublika","ru-mo"},
			{"Moskovskaya oblast'","ru-mos"},
			{"Moskva","ru-mow"},
			{"Murmanskaya oblast'","ru-mur"},
			{"Nenetskiy avtonomnyy okrug","ru-nen"},
			{"Nizhegorodskaya oblast'","ru-niz"},
			{"Novgorodskaya oblast'","ru-ngr"},
			{"Novosibirskaya oblast'","ru-nvs"},
			{"Omskaya oblast'","ru-oms"},
			{"Orenburgskaya oblast'","ru-ore"},
			{"Orlovskaya oblast'","ru-orl"},
			{"Penzenskaya oblast'","ru-pnz"},
			{"Permskiy kray","ru-per"},
			{"Primorskiy kray","ru-pri"},
			{"Pskovskaya oblast'","ru-psk"},
			{"Rostovskaya oblast'","ru-ros"},
			{"Ryazanskaya oblast'","ru-rya"},
			{"Sakha, Respublika","ru-sa"},
			{"Sakhalinskaya oblast'","ru-sak"},
			{"Samarskaya oblast'","ru-sam"},
			{"Sankt-Peterburg","ru-spe"},
			{"Saratovskaya oblast'","ru-sar"},
			{"Severnaya Osetiya-Alaniya, Respublika","ru-se"},
			{"Smolenskaya oblast'","ru-smo"},
			{"Stavropol'skiy kray","ru-sta"},
			{"Sverdlovskaya oblast'","ru-sve"},
			{"Tambovskaya oblast'","ru-tam"},
			{"Tatarstan, Respublika","ru-ta"},
			{"Tomskaya oblast'","ru-tom"},
			{"Tul'skaya oblast'","ru-tul"},
			{"Tverskaya oblast'","ru-tve"},
			{"Tyumenskaya oblast'","ru-tyu"},
			{"Tyva, Respublika","ru-ty"},
			{"Udmurtskaya Respublika","ru-ud"},
			{"Ul'yanovskaya oblast'","ru-uly"},
			{"Vladimirskaya oblast'","ru-vla"},
			{"Volgogradskaya oblast'","ru-vgg"},
			{"Vologodskaya oblast'","ru-vlg"},
			{"Voronezhskaya oblast'","ru-vor"},
			{"Yamalo-Nenetskiy avtonomnyy okrug","ru-yan"},
			{"Yaroslavskaya oblast'","ru-yar"},
			{"Yevreyskaya avtonomnaya oblast'","ru-yev"},
			{"Zabaykal'skiy kray","ru-zab"},
			{"Est","cm-es"},
			{"Nord","cm-no"},
			{"Ouest","cm-ou"},
			{"Sud","cm-su"},
			{"Ville de Kigali","rw-01"},
			{"'Asir","sa-14"},
			{"Al Bahah","sa-11"},
			{"Al Hudud ash Shamaliyah","sa-08"},
			{"Al Jawf","sa-12"},
			{"Al Madinah al Munawwarah","sa-03"},
			{"Al Qasim","sa-05"},
			{"Ar Riyad","sa-01"},
			{"Ash Sharqiyah","eg-shr"},
			{"Ha'il","sa-06"},
			{"Jazan","sa-09"},
			{"Makkah al Mukarramah","sa-02"},
			{"Najran","sa-10"},
			{"Tabuk","sa-07"},
			{"Central","bw-ce"},
			{"Guadalcanal","sb-gu"},
			{"Isabel","sb-is"},
			{"Makira","sb-mk"},
			{"Malaita","sb-ml"},
			{"Western","fj-w"},
			{"English River","sc-16"},
			{"Blue Nile","sd-nb"},
			{"Gedaref","sd-gd"},
			{"Gezira","sd-gz"},
			{"Kassala","sd-ka"},
			{"Khartoum","sd-kh"},
			{"North Darfur","sd-dn"},
			{"North Kordofan","sd-kn"},
			{"Northern","fj-n"},
			{"Red Sea","sd-rs"},
			{"River Nile","sd-nr"},
			{"Sennar","sd-si"},
			{"South Darfur","sd-ds"},
			{"South Kordofan","sd-ks"},
			{"West Darfur","sd-dw"},
			{"White Nile","sd-nw"},
			{"Blekinge Lan","se-k"},
			{"Dalarnas Lan","se-w"},
			{"Gavleborgs Lan","se-x"},
			{"Gotlands Lan","se-i"},
			{"Hallands Lan","se-n"},
			{"Jamtlands Lan","se-z"},
			{"Jonkopings Lan","se-f"},
			{"Kalmar Lan","se-h"},
			{"Kronobergs Lan","se-g"},
			{"Norrbottens Lan","se-bd"},
			{"Orebro Lan","se-t"},
			{"Ostergotlands Lan","se-e"},
			{"Skane Lan","se-m"},
			{"Sodermanlands Lan","se-d"},
			{"Stockholms Lan","se-ab"},
			{"Uppsala Lan","se-c"},
			{"Varmlands Lan","se-s"},
			{"Vasterbottens Lan","se-ac"},
			{"Vasternorrlands Lan","se-y"},
			{"Vastmanlands Lan","se-u"},
			{"Vastra Gotaland","se-o"},
			{"Singapore","sg-01"},
			{"Ascension","sh-ac"},
			{"Saint Helena","sh-hl"},
			{"Tristan da Cunha","sh-ta"},
			{"Ajdovscina","si-001"},
			{"Bled","si-003"},
			{"Bohinj","si-004"},
			{"Borovnica","si-005"},
			{"Bovec","si-006"},
			{"Brezice","si-009"},
			{"Brezovica","si-008"},
			{"Celje","si-011"},
			{"Cerknica","si-013"},
			{"Cerkno","si-014"},
			{"Crensovci","si-015"},
			{"Crnomelj","si-017"},
			{"Destrnik","si-018"},
			{"Divaca","si-019"},
			{"Domzale","si-023"},
			{"Dravograd","si-025"},
			{"Gornja Radgona","si-029"},
			{"Grosuplje","si-032"},
			{"Hoce-Slivnica","si-160"},
			{"Horjul","si-162"},
			{"Hrastnik","si-034"},
			{"Idrija","si-036"},
			{"Ig","si-037"},
			{"Ilirska Bistrica","si-038"},
			{"Ivancna Gorica","si-039"},
			{"Izola-Isola","si-040"},
			{"Jesenice","si-041"},
			{"Kamnik","si-043"},
			{"Kanal","si-044"},
			{"Kidricevo","si-045"},
			{"Kobarid","si-046"},
			{"Kocevje","si-048"},
			{"Koper-Capodistria","si-050"},
			{"Kranj","si-052"},
			{"Kranjska Gora","si-053"},
			{"Krsko","si-054"},
			{"Lasko","si-057"},
			{"Lenart","si-058"},
			{"Lendava","si-059"},
			{"Litija","si-060"},
			{"Ljubljana","si-061"},
			{"Ljutomer","si-063"},
			{"Log-Dragomer","si-208"},
			{"Logatec","si-064"},
			{"Lovrenc na Pohorju","si-167"},
			{"Maribor","si-070"},
			{"Medvode","si-071"},
			{"Menges","si-072"},
			{"Metlika","si-073"},
			{"Mezica","si-074"},
			{"Miklavz na Dravskem Polju","si-169"},
			{"Miren-Kostanjevica","si-075"},
			{"Mislinja","si-076"},
			{"Mozirje","si-079"},
			{"Murska Sobota","si-080"},
			{"Muta","si-081"},
			{"Nova Gorica","si-084"},
			{"Novo Mesto","si-085"},
			{"Odranci","si-086"},
			{"Oplotnica","si-171"},
			{"Ormoz","si-087"},
			{"Piran","si-090"},
			{"Pivka","si-091"},
			{"Poljcane","si-200"},
			{"Polzela","si-173"},
			{"Postojna","si-094"},
			{"Prebold","si-174"},
			{"Prevalje","si-175"},
			{"Ptuj","si-096"},
			{"Racam","si-098"},
			{"Radece","si-099"},
			{"Radenci","si-100"},
			{"Radlje ob Dravi","si-101"},
			{"Radovljica","si-102"},
			{"Ravne na Koroskem","si-103"},
			{"Ribnica","si-104"},
			{"Rogaska Slatina","si-106"},
			{"Ruse","bg-18"},
			{"Sempeter-Vrtojba","si-183"},
			{"Sencur","si-117"},
			{"Sentilj","si-118"},
			{"Sentjur pri Celju","si-120"},
			{"Sevnica","si-110"},
			{"Sezana","si-111"},
			{"Skofja Loka","si-122"},
			{"Skofljica","si-123"},
			{"Slovenj Gradec","si-112"},
			{"Slovenska Bistrica","si-113"},
			{"Slovenske Konjice","si-114"},
			{"Sostanj","si-126"},
			{"Store","si-127"},
			{"Straza","si-203"},
			{"Tolmin","si-128"},
			{"Trbovlje","si-129"},
			{"Trebnje","si-130"},
			{"Trzic","si-131"},
			{"Trzin","si-186"},
			{"Turnisce","si-132"},
			{"Velenje","si-133"},
			{"Vipava","si-136"},
			{"Vodice","si-138"},
			{"Vojnik","si-139"},
			{"Vrhnika","si-140"},
			{"Vuzenica","si-141"},
			{"Zagorje ob Savi","si-142"},
			{"Zalec","si-190"},
			{"Zelezniki","si-146"},
			{"Ziri","si-147"},
			{"Zrece","si-144"},
			{"Zuzemberk","si-193"},
			{"Svalbard and Jan Mayen","sj"},
			{"Banskobystricky kraj","sk-bc"},
			{"Bratislavsky kraj","sk-bl"},
			{"Kosicky kraj","sk-ki"},
			{"Nitriansky kraj","sk-ni"},
			{"Presovsky kraj","sk-pv"},
			{"Trenciansky kraj","sk-tc"},
			{"Trnavsky kraj","sk-ta"},
			{"Zilinsky kraj","sk-zi"},
			{"Eastern","gh-ep"},
			{"Northern","fj-n"},
			{"Southern","bw-so"},
			{"Western Area","sl-w"},
			{"Acquaviva","sm-01"},
			{"Chiesanuova","sm-02"},
			{"San Marino","sm-07"},
			{"Serravalle","sm-09"},
			{"Dakar","sn-dk"},
			{"Diourbel","sn-db"},
			{"Fatick","sn-fk"},
			{"Kaffrine","sn-ka"},
			{"Kaolack","sn-kl"},
			{"Kedougou","sn-ke"},
			{"Kolda","sn-kd"},
			{"Louga","sn-lg"},
			{"Matam","sn-mt"},
			{"Saint-Louis","sn-sl"},
			{"Sedhiou","sn-se"},
			{"Tambacounda","sn-tc"},
			{"Thies","sn-th"},
			{"Ziguinchor","sn-zg"},
			{"Awdal","so-aw"},
			{"Bakool","so-bk"},
			{"Banaadir","so-bn"},
			{"Bari","so-br"},
			{"Bay","so-by"},
			{"Galguduud","so-ga"},
			{"Gedo","so-ge"},
			{"Hiiraan","so-hi"},
			{"Jubbada Dhexe","so-jd"},
			{"Jubbada Hoose","so-jh"},
			{"Mudug","so-mu"},
			{"Nugaal","so-nu"},
			{"Sanaag","so-sa"},
			{"Shabeellaha Dhexe","so-sd"},
			{"Shabeellaha Hoose","so-sh"},
			{"Sool","so-so"},
			{"Togdheer","so-to"},
			{"Woqooyi Galbeed","so-wo"},
			{"Brokopondo","sr-br"},
			{"Commewijne","sr-cm"},
			{"Coronie","sr-cr"},
			{"Marowijne","sr-ma"},
			{"Nickerie","sr-ni"},
			{"Para","br-pa"},
			{"Paramaribo","sr-pm"},
			{"Saramacca","sr-sa"},
			{"Wanica","sr-wa"},
			{"Central Equatoria","ss-ec"},
			{"Eastern Equatoria","ss-ee"},
			{"Jonglei","ss-jg"},
			{"Lakes","ss-lk"},
			{"Northern Bahr el Ghazal","ss-bn"},
			{"Unity","ss-uy"},
			{"Upper Nile","ss-nu"},
			{"Warrap","ss-wr"},
			{"Western Bahr el Ghazal","ss-bw"},
			{"Western Equatoria","ss-ew"},
			{"Principe","st-p"},
			{"Sao Tome","st-s"},
			{"Ahuachapan","sv-ah"},
			{"Cabanas","sv-ca"},
			{"Chalatenango","sv-ch"},
			{"Cuscatlan","sv-cu"},
			{"La Libertad","pe-lal"},
			{"La Paz","bo-l"},
			{"La Union","ph-lun"},
			{"Morazan","sv-mo"},
			{"San Miguel","sv-sm"},
			{"San Salvador","sv-ss"},
			{"San Vicente","sv-sv"},
			{"Santa Ana","sv-sa"},
			{"Sonsonate","sv-so"},
			{"Usulutan","sv-us"},
			{"Al Hasakah","sy-ha"},
			{"Al Ladhiqiyah","sy-la"},
			{"Al Qunaytirah","sy-qu"},
			{"Ar Raqqah","sy-ra"},
			{"As Suwayda'","sy-su"},
			{"Dar'a","sy-dr"},
			{"Dayr az Zawr","sy-dy"},
			{"Dimashq","sy-di"},
			{"Halab","sy-hl"},
			{"Hamah","sy-hm"},
			{"Hims","sy-hi"},
			{"Idlib","sy-id"},
			{"Rif Dimashq","sy-rd"},
			{"Tartus","sy-ta"},
			{"Hhohho","sz-hh"},
			{"Lubombo","sz-lu"},
			{"Manzini","sz-ma"},
			{"Shiselweni","sz-sh"},
			{"Turks and Caicos Islands","tc"},
			{"Bahr el Gazel","td-bg"},
			{"Batha","td-ba"},
			{"Borkou","td-bo"},
			{"Chari-Baguirmi","td-cb"},
			{"Guera","td-gr"},
			{"Hadjer Lamis","td-hl"},
			{"Kanem","td-ka"},
			{"Lac","td-lc"},
			{"Logone-Occidental","td-lo"},
			{"Logone-Oriental","td-lr"},
			{"Mandoul","td-ma"},
			{"Mayo-Kebbi-Est","td-me"},
			{"Mayo-Kebbi-Ouest","td-mo"},
			{"Moyen-Chari","td-mc"},
			{"Ouaddai","td-od"},
			{"Salamat","td-sa"},
			{"Tandjile","td-ta"},
			{"Tibesti","td-ti"},
			{"Wadi Fira","td-wf"},
			{"Centre","cm-ce"},
			{"Kara","tg-k"},
			{"Maritime","tg-m"},
			{"Plateaux","cg-14"},
			{"Savannes","tg-s"},
			{"Amnat Charoen","th-37"},
			{"Ang Thong","th-15"},
			{"Buri Ram","th-31"},
			{"Chachoengsao","th-24"},
			{"Chai Nat","th-18"},
			{"Chaiyaphum","th-36"},
			{"Chanthaburi","th-22"},
			{"Chiang Mai","th-50"},
			{"Chiang Rai","th-57"},
			{"Chon Buri","th-20"},
			{"Chumphon","th-86"},
			{"Kalasin","th-46"},
			{"Kamphaeng Phet","th-62"},
			{"Kanchanaburi","th-71"},
			{"Khon Kaen","th-40"},
			{"Krabi","th-81"},
			{"Krung Thep Maha Nakhon","th-10"},
			{"Lampang","th-52"},
			{"Lamphun","th-51"},
			{"Loei","th-42"},
			{"Lop Buri","th-16"},
			{"Mae Hong Son","th-58"},
			{"Maha Sarakham","th-44"},
			{"Mukdahan","th-49"},
			{"Nakhon Nayok","th-26"},
			{"Nakhon Pathom","th-73"},
			{"Nakhon Phanom","th-48"},
			{"Nakhon Ratchasima","th-30"},
			{"Nakhon Sawan","th-60"},
			{"Nakhon Si Thammarat","th-80"},
			{"Nan","th-55"},
			{"Narathiwat","th-96"},
			{"Nong Bua Lam Phu","th-39"},
			{"Nong Khai","th-43"},
			{"Nonthaburi","th-12"},
			{"Pathum Thani","th-13"},
			{"Pattani","th-94"},
			{"Phangnga","th-82"},
			{"Phatthalung","th-93"},
			{"Phayao","th-56"},
			{"Phetchabun","th-67"},
			{"Phetchaburi","th-76"},
			{"Phichit","th-66"},
			{"Phitsanulok","th-65"},
			{"Phra Nakhon Si Ayutthaya","th-14"},
			{"Phrae","th-54"},
			{"Phuket","th-83"},
			{"Prachin Buri","th-25"},
			{"Prachuap Khiri Khan","th-77"},
			{"Ranong","th-85"},
			{"Ratchaburi","th-70"},
			{"Rayong","th-21"},
			{"Roi Et","th-45"},
			{"Sa Kaeo","th-27"},
			{"Sakon Nakhon","th-47"},
			{"Samut Prakan","th-11"},
			{"Samut Sakhon","th-74"},
			{"Samut Songkhram","th-75"},
			{"Saraburi","th-19"},
			{"Satun","th-91"},
			{"Si Sa Ket","th-33"},
			{"Sing Buri","th-17"},
			{"Songkhla","th-90"},
			{"Sukhothai","th-64"},
			{"Suphan Buri","th-72"},
			{"Surat Thani","th-84"},
			{"Surin","th-32"},
			{"Tak","th-63"},
			{"Trang","th-92"},
			{"Trat","th-23"},
			{"Ubon Ratchathani","th-34"},
			{"Udon Thani","th-41"},
			{"Uthai Thani","th-61"},
			{"Uttaradit","th-53"},
			{"Yala","th-95"},
			{"Yasothon","th-35"},
			{"Khatlon","tj-kt"},
			{"Kuhistoni Badakhshon","tj-gb"},
			{"Regions of Republican Subordination","tj-rr"},
			{"Sughd","tj-su"},
			{"Tajikistan","tj"},
			{"Tokelau","tk"},
			{"Dili","tl-di"},
			{"Ahal","tm-a"},
			{"Balkan","tm-b"},
			{"Dashoguz","tm-d"},
			{"Lebap","tm-l"},
			{"Mary","tm-m"},
			{"Aiana","tn-12"},
			{"Al Mahdia","tn-53"},
			{"Al Munastir","tn-52"},
			{"Bajah","tn-31"},
			{"Ben Arous","tn-13"},
			{"Bizerte","tn-23"},
			{"El Kef","tn-33"},
			{"Gabes","tn-81"},
			{"Gafsa","tn-71"},
			{"Jendouba","tn-32"},
			{"Kairouan","tn-41"},
			{"Kasserine","tn-42"},
			{"Kebili","tn-73"},
			{"Madanin","tn-82"},
			{"Manouba","tn-14"},
			{"Nabeul","tn-21"},
			{"Sfax","tn-61"},
			{"Sidi Bou Zid","tn-43"},
			{"Siliana","tn-34"},
			{"Sousse","tn-51"},
			{"Tataouine","tn-83"},
			{"Tozeur","tn-72"},
			{"Tunis","tn-11"},
			{"Zaghouan","tn-22"},
			{"Ha'apai","to-02"},
			{"Tongatapu","to-04"},
			{"Vava'u","to-05"},
			{"Adana","tr-01"},
			{"Adiyaman","tr-02"},
			{"Afyonkarahisar","tr-03"},
			{"Agri","tr-04"},
			{"Aksaray","tr-68"},
			{"Amasya","tr-05"},
			{"Ankara","tr-06"},
			{"Antalya","tr-07"},
			{"Ardahan","tr-75"},
			{"Artvin","tr-08"},
			{"Aydin","tr-09"},
			{"Balikesir","tr-10"},
			{"Bartin","tr-74"},
			{"Batman","tr-72"},
			{"Bayburt","tr-69"},
			{"Bilecik","tr-11"},
			{"Bingol","tr-12"},
			{"Bitlis","tr-13"},
			{"Bolu","tr-14"},
			{"Burdur","tr-15"},
			{"Bursa","tr-16"},
			{"Canakkale","tr-17"},
			{"Cankiri","tr-18"},
			{"Corum","tr-19"},
			{"Denizli","tr-20"},
			{"Diyarbakir","tr-21"},
			{"Duzce","tr-81"},
			{"Edirne","tr-22"},
			{"Elazig","tr-23"},
			{"Erzincan","tr-24"},
			{"Erzurum","tr-25"},
			{"Eskisehir","tr-26"},
			{"Gaziantep","tr-27"},
			{"Giresun","tr-28"},
			{"Gumushane","tr-29"},
			{"Hakkari","tr-30"},
			{"Hatay","tr-31"},
			{"Igdir","tr-76"},
			{"Isparta","tr-32"},
			{"Istanbul","tr-34"},
			{"Izmir","tr-35"},
			{"Kahramanmaras","tr-46"},
			{"Karabuk","tr-78"},
			{"Karaman","tr-70"},
			{"Kars","tr-36"},
			{"Kastamonu","tr-37"},
			{"Kayseri","tr-38"},
			{"Kilis","tr-79"},
			{"Kirikkale","tr-71"},
			{"Kirklareli","tr-39"},
			{"Kirsehir","tr-40"},
			{"Kocaeli","tr-41"},
			{"Konya","tr-42"},
			{"Kutahya","tr-43"},
			{"Malatya","tr-44"},
			{"Manisa","tr-45"},
			{"Mardin","tr-47"},
			{"Mersin","tr-33"},
			{"Mugla","tr-48"},
			{"Mus","tr-49"},
			{"Nevsehir","tr-50"},
			{"Nigde","tr-51"},
			{"Ordu","tr-52"},
			{"Osmaniye","tr-80"},
			{"Rize","tr-53"},
			{"Sakarya","tr-54"},
			{"Samsun","tr-55"},
			{"Sanliurfa","tr-63"},
			{"Siirt","tr-56"},
			{"Sinop","tr-57"},
			{"Sirnak","tr-73"},
			{"Sivas","tr-58"},
			{"Tekirdag","tr-59"},
			{"Tokat","tr-60"},
			{"Trabzon","tr-61"},
			{"Tunceli","tr-62"},
			{"Usak","tr-64"},
			{"Van","tr-65"},
			{"Yalova","tr-77"},
			{"Yozgat","tr-66"},
			{"Zonguldak","tr-67"},
			{"Arima","tt-ari"},
			{"Mayaro","tt-mrc"},
			{"Port-of-Spain","tt-pos"},
			{"Saint Andrew","dm-02"},
			{"Saint George","dm-04"},
			{"San Fernando","tt-sfo"},
			{"Tobago","tt-tob"},
			{"Trinidad and Tobago","tt-tob"},
			{"Victoria","au-vic"},
			{"Tuvalu","tv"},
			{"Kao-hsiung","tw-khh"},
			{"T'ai-pei","tw-tpe"},
			{"T'ai-wan","tw"},
			{"Arusha","tz-01"},
			{"Dar es Salaam","tz-02"},
			{"Dodoma","tz-03"},
			{"Iringa","tz-04"},
			{"Kagera","tz-05"},
			{"Kaskazini Pemba","tz-06"},
			{"Kaskazini Unguja","tz-07"},
			{"Kigoma","tz-08"},
			{"Kilimanjaro","tz-09"},
			{"Kusini Pemba","tz-10"},
			{"Kusini Unguja","tz-11"},
			{"Lindi","tz-12"},
			{"Manyara","tz-26"},
			{"Mara","tz-13"},
			{"Mbeya","tz-14"},
			{"Mjini Magharibi","tz-15"},
			{"Morogoro","tz-16"},
			{"Mtwara","tz-17"},
			{"Mwanza","mw-mw"},
			{"Pwani","tz-19"},
			{"Rukwa","tz-20"},
			{"Ruvuma","tz-21"},
			{"Shinyanga","tz-22"},
			{"Singida","tz-23"},
			{"Tabora","tz-24"},
			{"Tanga","tz-25"},
			{"Avtonomna Respublika Krym","ua-43"},
			{"Cherkas'ka Oblast'","ua-71"},
			{"Chernihivs'ka Oblast'","ua-74"},
			{"Chernivets'ka Oblast'","ua-77"},
			{"Dnipropetrovs'ka Oblast'","ua-12"},
			{"Donets'ka Oblast'","ua-14"},
			{"Ivano-Frankivs'ka Oblast'","ua-26"},
			{"Kharkivs'ka Oblast'","ua-63"},
			{"Khersons'ka Oblast'","ua-65"},
			{"Khmel'nyts'ka Oblast'","ua-68"},
			{"Kirovohrads'ka Oblast'","ua-35"},
			{"Kyiv","ua-30"},
			{"Kyivs'ka Oblast'","ua-32"},
			{"L'vivs'ka Oblast'","ua-46"},
			{"Luhans'ka Oblast'","ua-09"},
			{"Mykolaivs'ka Oblast'","ua-48"},
			{"Odes'ka Oblast'","ua-51"},
			{"Poltavs'ka Oblast'","ua-53"},
			{"Rivnens'ka Oblast'","ua-56"},
			{"Sevastopol'","ua-40"},
			{"Sums'ka Oblast'","ua-59"},
			{"Ternopil's'ka Oblast'","ua-61"},
			{"Vinnyts'ka Oblast'","ua-05"},
			{"Volyns'ka Oblast'","ua-07"},
			{"Zakarpats'ka Oblast'","ua-21"},
			{"Zaporiz'ka Oblast'","ua-23"},
			{"Zhytomyrs'ka Oblast'","ua-18"},
			{"Abim","ug-317"},
			{"Adjumani","ug-301"},
			{"Agago","ug-322"},
			{"Alebtong","ug-323"},
			{"Amolatar","ug-314"},
			{"Amudat","ug-324"},
			{"Amuria","ug-216"},
			{"Amuru","ug-319"},
			{"Apac","ug-302"},
			{"Arua","ug-303"},
			{"Budaka","ug-217"},
			{"Bududa","ug-223"},
			{"Bugiri","ug-201"},
			{"Buikwe","ug-117"},
			{"Bukedea","ug-224"},
			{"Bukomansibi","ug-118"},
			{"Bukwa","ug-218"},
			{"Bulambuli","ug-225"},
			{"Buliisa","ug-419"},
			{"Bundibugyo","ug-401"},
			{"Bushenyi","ug-402"},
			{"Busia","ug-202"},
			{"Butaleja","ug-219"},
			{"Buvuma","ug-120"},
			{"Buyende","ug-226"},
			{"Dokolo","ug-318"},
			{"Gomba","ug-121"},
			{"Gulu","ug-304"},
			{"Hoima","ug-403"},
			{"Iganga","ug-203"},
			{"Isingiro","ug-417"},
			{"Jinja","ug-204"},
			{"Kaabong","ug-315"},
			{"Kabale","ug-404"},
			{"Kabarole","ug-405"},
			{"Kaberamaido","ug-213"},
			{"Kalangala","ug-101"},
			{"Kaliro","ug-220"},
			{"Kampala","ug-102"},
			{"Kamuli","ug-205"},
			{"Kamwenge","ug-413"},
			{"Kanungu","ug-414"},
			{"Kapchorwa","ug-206"},
			{"Kasese","ug-406"},
			{"Katakwi","ug-207"},
			{"Kayunga","ug-112"},
			{"Kibaale","ug-407"},
			{"Kiboga","ug-103"},
			{"Kibuku","ug-227"},
			{"Kiryandongo","ug-420"},
			{"Kisoro","ug-408"},
			{"Kitgum","ug-305"},
			{"Koboko","ug-316"},
			{"Kole","ug-326"},
			{"Kotido","ug-306"},
			{"Kumi","ug-208"},
			{"Kween","ug-228"},
			{"Kyankwanzi","ug-123"},
			{"Kyegegwa","ug-421"},
			{"Kyenjojo","ug-415"},
			{"Lira","ug-307"},
			{"Luuka","ug-229"},
			{"Luwero","ug-104"},
			{"Lwengo","ug-124"},
			{"Lyantonde","ug-116"},
			{"Manafwa","ug-221"},
			{"Maracha","ug-320"},
			{"Masaka","ug-105"},
			{"Masindi","ug-409"},
			{"Mayuge","ug-214"},
			{"Mbale","ug-209"},
			{"Mbarara","ug-410"},
			{"Mitooma","ug-422"},
			{"Mityana","ug-114"},
			{"Moroto","ug-308"},
			{"Moyo","ug-309"},
			{"Mpigi","ug-106"},
			{"Mubende","ug-107"},
			{"Mukono","ug-108"},
			{"Nakapiripirit","ug-311"},
			{"Nakaseke","ug-115"},
			{"Nakasongola","ug-109"},
			{"Namayingo","ug-230"},
			{"Namutumba","ug-222"},
			{"Napak","ug-328"},
			{"Nebbi","ug-310"},
			{"Ngora","ug-231"},
			{"Ntoroko","ug-423"},
			{"Ntungamo","ug-411"},
			{"Otuke","ug-330"},
			{"Oyam","ug-321"},
			{"Pader","ug-312"},
			{"Pallisa","ug-210"},
			{"Rakai","ug-110"},
			{"Rubirizi","ug-424"},
			{"Rukungiri","ug-412"},
			{"Sembabule","ug-111"},
			{"Serere","ug-232"},
			{"Sheema","ug-425"},
			{"Sironko","ug-215"},
			{"Soroti","ug-211"},
			{"Tororo","ug-212"},
			{"Wakiso","ug-113"},
			{"Yumbe","ug-313"},
			{"Zombo","ug-331"},
			{"Palmyra Atoll","um-95"},
			{"Alabama","us-al"},
			{"Alaska","us-ak"},
			{"Arizona","us-az"},
			{"Arkansas","us-ar"},
			{"California","us-ca"},
			{"Colorado","us-co"},
			{"Connecticut","us-ct"},
			{"Delaware","us-de"},
			{"District Of Columbia","us-dc"},
			{"Florida","us-fl"},
			{"Georgia","us-ga"},
			{"Hawaii","us-hi"},
			{"Idaho","us-id"},
			{"Illinois","us-il"},
			{"Indiana","us-in"},
			{"Iowa","us-ia"},
			{"Kansas","us-ks"},
			{"Kentucky","us-ky"},
			{"Louisiana","us-la"},
			{"Maine","us-me"},
			{"Maryland","lr-my"},
			{"Massachusetts","us-ma"},
			{"Michigan","us-mi"},
			{"Minnesota","us-mn"},
			{"Mississippi","us-ms"},
			{"Missouri","us-mo"},
			{"Montana","bg-12"},
			{"Nebraska","us-ne"},
			{"Nevada","us-nv"},
			{"New Hampshire","us-nh"},
			{"New Jersey","us-nj"},
			{"New Mexico","us-nm"},
			{"New York","us-ny"},
			{"North Carolina","us-nc"},
			{"North Dakota","us-nd"},
			{"Ohio","us-oh"},
			{"Oklahoma","us-ok"},
			{"Oregon","us-or"},
			{"Pennsylvania","us-pa"},
			{"Rhode Island","us-ri"},
			{"South Carolina","us-sc"},
			{"South Dakota","us-sd"},
			{"Tennessee","us-tn"},
			{"Texas","us-tx"},
			{"Utah","us-ut"},
			{"Vermont","us-vt"},
			{"Virginia","us-va"},
			{"Washington","us-wa"},
			{"West Virginia","us-wv"},
			{"Wisconsin","us-wi"},
			{"Wyoming","us-wy"},
			{"Artigas","uy-ar"},
			{"Canelones","uy-ca"},
			{"Cerro Largo","uy-cl"},
			{"Colonia","uy-co"},
			{"Durazno","uy-du"},
			{"Flores","uy-fs"},
			{"Florida","us-fl"},
			{"Lavalleja","uy-la"},
			{"Maldonado","uy-ma"},
			{"Montevideo","uy-mo"},
			{"Paysandu","uy-pa"},
			{"Rio Negro","ar-r"},
			{"Rivera","uy-rv"},
			{"Rocha","uy-ro"},
			{"Salto","uy-sa"},
			{"San Jose","cr-sj"},
			{"Soriano","uy-so"},
			{"Tacuarembo","uy-ta"},
			{"Treinta y Tres","uy-tt"},
			{"Andijon","uz-an"},
			{"Buxoro","uz-bu"},
			{"Farg'ona","uz-fa"},
			{"Jizzax","uz-ji"},
			{"Namangan","uz-ng"},
			{"Navoiy","uz-nw"},
			{"Qashqadaryo","uz-qa"},
			{"Qoraqalpog'iston Respublikasi","uz-qr"},
			{"Samarqand","uz-sa"},
			{"Sirdaryo","uz-si"},
			{"Surxondaryo","uz-su"},
			{"Toshkent","uz-to"},
			{"Xorazm","uz-xo"},
			{"Charlotte","vc-01"},
			{"Saint George","dm-04"},
			{"Amazonas","br-am"},
			{"Anzoategui","ve-b"},
			{"Apure","ve-c"},
			{"Aragua","ve-d"},
			{"Barinas","ve-e"},
			{"Bolivar","co-bol"},
			{"Carabobo","ve-g"},
			{"Cojedes","ve-h"},
			{"Delta Amacuro","ve-y"},
			{"Distrito Federal","br-df"},
			{"Falcon","ve-i"},
			{"Guarico","ve-j"},
			{"Lara","ve-k"},
			{"Merida","ve-l"},
			{"Miranda","ve-m"},
			{"Monagas","ve-n"},
			{"Nueva Esparta","ve-o"},
			{"Portuguesa","ve-p"},
			{"Sucre","co-suc"},
			{"Tachira","ve-s"},
			{"Trujillo","ve-t"},
			{"Vargas","ve-x"},
			{"Yaracuy","ve-u"},
			{"Zulia","ve-v"},
			{"An Giang","vn-44"},
			{"Bac Giang","vn-54"},
			{"Bac Kan","vn-53"},
			{"Bac Lieu","vn-55"},
			{"Bac Ninh","vn-56"},
			{"Ben Tre","vn-50"},
			{"Binh Dinh","vn-31"},
			{"Binh Duong","vn-57"},
			{"Binh Phuoc","vn-58"},
			{"Binh Thuan","vn-40"},
			{"Ca Mau","vn-59"},
			{"Can Tho","vn-ct"},
			{"Cao Bang","vn-04"},
			{"Da Nang","vn-dn"},
			{"Dak Lak","vn-33"},
			{"Dien Bien","vn-71"},
			{"Dong Nai","vn-39"},
			{"Dong Thap","vn-45"},
			{"Gia Lai","vn-30"},
			{"Ha Giang","vn-03"},
			{"Ha Nam","vn-63"},
			{"Ha Noi","vn-hn"},
			{"Ha Tinh","vn-23"},
			{"Hai Duong","vn-61"},
			{"Hai Phong","vn-hp"},
			{"Ho Chi Minh","vn-sg"},
			{"Hoa Binh","vn-14"},
			{"Hung Yen","vn-66"},
			{"Khanh Hoa","vn-34"},
			{"Kien Giang","vn-47"},
			{"Lai Chau","vn-01"},
			{"Lam Dong","vn-35"},
			{"Lang Son","vn-09"},
			{"Lao Cai","vn-02"},
			{"Long An","vn-41"},
			{"Nam Dinh","vn-67"},
			{"Nghe An","vn-22"},
			{"Ninh Binh","vn-18"},
			{"Ninh Thuan","vn-36"},
			{"Phu Tho","vn-68"},
			{"Phu Yen","vn-32"},
			{"Quang Binh","vn-24"},
			{"Quang Nam","vn-27"},
			{"Quang Ngai","vn-29"},
			{"Quang Ninh","vn-13"},
			{"Quang Tri","vn-25"},
			{"Soc Trang","vn-52"},
			{"Son La","vn-05"},
			{"Tay Ninh","vn-37"},
			{"Thai Binh","vn-20"},
			{"Thai Nguyen","vn-69"},
			{"Thanh Hoa","vn-21"},
			{"Thua Thien-Hue","vn-26"},
			{"Tien Giang","vn-46"},
			{"Tra Vinh","vn-51"},
			{"Tuyen Quang","vn-07"},
			{"Vinh Long","vn-49"},
			{"Vinh Phuc","vn-70"},
			{"Yen Bai","vn-06"},
			{"Malampa","vu-map"},
			{"Sanma","vu-sam"},
			{"Shefa","vu-see"},
			{"Tafea","vu-tae"},
			{"Torba","vu-tob"},
			{"Wallis and Futuna Islands","wf"},
			{"A'ana","ws-aa"},
			{"Atua","ws-at"},
			{"Gagaifomauga","ws-gi"},
			{"Palauli","ws-pa"},
			{"Tuamasaga","ws-tu"},
			{"'Adan","ye-ad"},
			{"'Amran","ye-am"},
			{"Abyan","ye-ab"},
			{"Ad Dali","ye-da"},
			{"Al Bayda'","ye-ba"},
			{"Al Hudaydah","ye-hu"},
			{"Al Jawf","sa-12"},
			{"Al Mahrah","ye-mr"},
			{"Al Mahwit","ye-mw"},
			{"Amanat al 'Asimah","ye-sa"},
			{"Dhamar","ye-dh"},
			{"Hadramawt","ye-hd"},
			{"Hajjah","ye-hj"},
			{"Ibb","ye-ib"},
			{"Lahij","ye-la"},
			{"Ma'rib","ye-ma"},
			{"Raymah","ye-ra"},
			{"Sa'dah","ye-sd"},
			{"San'a'","ye-sn"},
			{"Shabwah","ye-sh"},
			{"Ta'izz","ye-ta"},
			{"Eastern Cape","za-ec"},
			{"Free State","za-fs"},
			{"Gauteng","za-gt"},
			{"KwaZulu-Natal","za-nl"},
			{"Limpopo","za-lp"},
			{"Mpumalanga","za-mp"},
			{"North-West","bw-nw"},
			{"Northern Cape","za-nc"},
			{"Western Cape","za-wc"},
			{"Central","bw-ce"},
			{"Copperbelt","zm-08"},
			{"Eastern","gh-ep"},
			{"Luapula","zm-04"},
			{"Lusaka","zm-09"},
			{"North-Western","zm-06"},
			{"Northern","fj-n"},
			{"Southern","bw-so"},
			{"Western","fj-w"},
			{"Bulawayo","zw-bu"},
			{"Harare","zw-ha"},
			{"Manicaland","zw-ma"},
			{"Mashonaland Central","zw-mc"},
			{"Mashonaland East","zw-me"},
			{"Mashonaland West","zw-mw"},
			{"Masvingo","zw-mv"},
			{"Matabeleland North","zw-mn"},
			{"Matabeleland South","zw-ms"},
			{"Midlands","zw-mi"},
		};

		#endregion ISO 3166-2
	}
}