using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TawGatherMembersInfo
{
	public static class Iso3166
	{
		#region ISO 3166

		/// <summary>
		/// Country name to two letter ISO 3166
		/// </summary>
		public readonly static BiDictionary<string, string> countryNameToIso3166 = new BiDictionary<string, string>()
		{
{"Afghanistan","af"},
{"Albania","al"},
{"Algeria","dz"},
{"American Samoa","as"},
{"Andorra","ad"},
{"Angola","ao"},
{"Anguilla","ai"},
{"Antarctica","aq"},
{"Antigua and Barbuda","ag"},
{"Argentina","ar"},
{"Armenia","am"},
{"Aruba","aw"},
{"Australia","au"},
{"Austria","at"},
{"Azerbaijan","az"},
{"Bahamas","bs"},
{"Bahrain","bh"},
{"Bangladesh","bd"},
{"Barbados","bb"},
{"Belarus","by"},
{"Belgium","be"},
{"Belize","bz"},
{"Benin","bj"},
{"Bermuda","bm"},
{"Bhutan","bt"},
{"Bolivia","bo"},
{"Bonaire","bq"},
{"Bosnia and Herzegovina","ba"},
{"Botswana","bw"},
{"Bouvet Island","bv"},
{"Brazil","br"},
{"British Indian Ocean Territory","io"},
{"Brunei Darussalam","bn"},
{"Bulgaria","bg"},
{"Burkina Faso","bf"},
{"Burundi","bi"},
{"Cambodia","kh"},
{"Cameroon","cm"},
{"Canada","ca"},
{"Cape Verde","cv"},
{"Cayman Islands","ky"},
{"Central African Republic","cf"},
{"Chad","td"},
{"Chile","cl"},
{"China","cn"},
{"Christmas Island","cx"},
{"Cocos (Keeling) Islands","cc"},
{"Colombia","co"},
{"Comoros","km"},
{"Congo","cg"},
{"Democratic Republic of the Congo","cd"},
{"Cook Islands","ck"},
{"Costa Rica","cr"},
{"Croatia","hr"},
{"Cuba","cu"},
{"Curacao","cw"},
{"Cyprus","cy"},
{"Czech Republic","cz"},
{"Côte d'Ivoire","ci"},
{"Denmark","dk"},
{"Djibouti","dj"},
{"Dominica","dm"},
{"Dominican Republic","do"},
{"Ecuador","ec"},
{"Egypt","eg"},
{"El Salvador","sv"},
{"Equatorial Guinea","gq"},
{"Eritrea","er"},
{"Estonia","ee"},
{"Ethiopia","et"},
{"Falkland Islands (Malvinas)","fk"},
{"Faroe Islands","fo"},
{"Fiji","fj"},
{"Finland","fi"},
{"France","fr"},
{"French Guiana","gf"},
{"French Polynesia","pf"},
{"French Southern Territories","tf"},
{"Gabon","ga"},
{"Gambia","gm"},
{"Georgia","ge"},
{"Germany","de"},
{"Ghana","gh"},
{"Gibraltar","gi"},
{"Greece","gr"},
{"Greenland","gl"},
{"Grenada","gd"},
{"Guadeloupe","gp"},
{"Guam","gu"},
{"Guatemala","gt"},
{"Guernsey","gg"},
{"Guinea","gn"},
{"Guinea-Bissau","gw"},
{"Guyana","gy"},
{"Haiti","ht"},
{"Heard Island and McDonald Mcdonald Islands","hm"},
{"Holy See (Vatican City State)","va"},
{"Honduras","hn"},
{"Hong Kong","hk"},
{"Hungary","hu"},
{"Iceland","is"},
{"India","in"},
{"Indonesia","id"},
{"Iran, Islamic Republic of","ir"},
{"Iraq","iq"},
{"Ireland","ie"},
{"Isle of Man","im"},
{"Israel","il"},
{"Italy","it"},
{"Jamaica","jm"},
{"Japan","jp"},
{"Jersey","je"},
{"Jordan","jo"},
{"Kazakhstan","kz"},
{"Kenya","ke"},
{"Kiribati","ki"},
{"Korea, Democratic People's Republic of","kp"},
{"Korea, Republic of","kr"},
{"Kuwait","kw"},
{"Kyrgyzstan","kg"},
{"Lao People's Democratic Republic","la"},
{"Latvia","lv"},
{"Lebanon","lb"},
{"Lesotho","ls"},
{"Liberia","lr"},
{"Libya","ly"},
{"Liechtenstein","li"},
{"Lithuania","lt"},
{"Luxembourg","lu"},
{"Macao","mo"},
{"Macedonia, the Former Yugoslav Republic of","mk"},
{"Madagascar","mg"},
{"Malawi","mw"},
{"Malaysia","my"},
{"Maldives","mv"},
{"Mali","ml"},
{"Malta","mt"},
{"Marshall Islands","mh"},
{"Martinique","mq"},
{"Mauritania","mr"},
{"Mauritius","mu"},
{"Mayotte","yt"},
{"Mexico","mx"},
{"Micronesia, Federated States of","fm"},
{"Moldova, Republic of","md"},
{"Monaco","mc"},
{"Mongolia","mn"},
{"Montenegro","me"},
{"Montserrat","ms"},
{"Morocco","ma"},
{"Mozambique","mz"},
{"Myanmar","mm"},
{"Namibia","na"},
{"Nauru","nr"},
{"Nepal","np"},
{"Netherlands","nl"},
{"New Caledonia","nc"},
{"New Zealand","nz"},
{"Nicaragua","ni"},
{"Niger","ne"},
{"Nigeria","ng"},
{"Niue","nu"},
{"Norfolk Island","nf"},
{"Northern Mariana Islands","mp"},
{"Norway","no"},
{"Oman","om"},
{"Pakistan","pk"},
{"Palau","pw"},
{"Palestine, State of","ps"},
{"Panama","pa"},
{"Papua New Guinea","pg"},
{"Paraguay","py"},
{"Peru","pe"},
{"Philippines","ph"},
{"Pitcairn","pn"},
{"Poland","pl"},
{"Portugal","pt"},
{"Puerto Rico","pr"},
{"Qatar","qa"},
{"Romania","ro"},
{"Russian Federation","ru"},
{"Rwanda","rw"},
{"Reunion","re"},
{"Saint Barthalemy","bl"},
{"Saint Helena","sh"},
{"Saint Kitts and Nevis","kn"},
{"Saint Lucia","lc"},
{"Saint Martin (French part)","mf"},
{"Saint Pierre and Miquelon","pm"},
{"Saint Vincent and the Grenadines","vc"},
{"Samoa","ws"},
{"San Marino","sm"},
{"Sao Tome and Principe","st"},
{"Saudi Arabia","sa"},
{"Senegal","sn"},
{"Serbia","rs"},
{"Seychelles","sc"},
{"Sierra Leone","sl"},
{"Singapore","sg"},
{"Sint Maarten (Dutch part)","sx"},
{"Slovakia","sk"},
{"Slovenia","si"},
{"Solomon Islands","sb"},
{"Somalia","so"},
{"South Africa","za"},
{"South Georgia and the South Sandwich Islands","gs"},
{"South Sudan","ss"},
{"Spain","es"},
{"Sri Lanka","lk"},
{"Sudan","sd"},
{"Suriname","sr"},
{"Svalbard and Jan Mayen","sj"},
{"Swaziland","sz"},
{"Sweden","se"},
{"Switzerland","ch"},
{"Syrian Arab Republic","sy"},
{"Taiwan, Province of China","tw"},
{"Tajikistan","tj"},
{"United Republic of Tanzania","tz"},
{"Thailand","th"},
{"Timor-Leste","tl"},
{"Togo","tg"},
{"Tokelau","tk"},
{"Tonga","to"},
{"Trinidad and Tobago","tt"},
{"Tunisia","tn"},
{"Turkey","tr"},
{"Turkmenistan","tm"},
{"Turks and Caicos Islands","tc"},
{"Tuvalu","tv"},
{"Uganda","ug"},
{"Ukraine","ua"},
{"United Arab Emirates","ae"},
{"United Kingdom","gb"},
{"United States","us"},
{"United States Minor Outlying Islands","um"},
{"Uruguay","uy"},
{"Uzbekistan","uz"},
{"Vanuatu","vu"},
{"Venezuela","ve"},
{"Vietnam","vn"},
{"British Virgin Islands","vg"},
{"US Virgin Islands","vi"},
{"Wallis and Futuna","wf"},
{"Western Sahara","eh"},
{"Yemen","ye"},
{"Zambia","zm"},
{"Zimbabwe","zw"},
{"Aland Islands","ax"},
		};

		#endregion ISO 3166

		#region ISO 3166-2

		/// <summary>
		/// Country subdivison name to ISO 3166-2
		/// Taken from: http://www.ip2location.com/free/iso3166-2
		/// </summary>
		public readonly static BiDictionary<string, string> countrySubdivisonNameToIso3166_2 = new BiDictionary<string, string>()
		{
{"Canillo","ad-02"},
{"Encamp","ad-03"},
{"La Massana","ad-04"},
{"Ordino","ad-05"},
{"Sant Julia de Loria","ad-06"},
{"Andorra la Vella","ad-07"},
{"Escaldes-Engordany","ad-08"},
{"'Ajman","ae-aj"},
{"Abu Zaby","ae-az"},
{"Dubayy","ae-du"},
{"Al Fujayrah","ae-fu"},
{"Ra's al Khaymah","ae-rk"},
{"Ash Shariqah","ae-sh"},
{"Umm al Qaywayn","ae-uq"},
{"Balkh","af-bal"},
{"Bamyan","af-bam"},
{"Badghis","af-bdg"},
{"Badakhshan","af-bds"},
{"Baghlan","af-bgl"},
{"Daykundi","af-day"},
{"Farah","af-fra"},
{"Faryab","af-fyb"},
{"Ghazni","af-gha"},
{"Ghor","af-gho"},
{"Helmand","af-hel"},
{"Herat","af-her"},
{"Jowzjan","af-jow"},
{"Kabul","af-kab"},
{"Kandahar","af-kan"},
{"Kapisa","af-kap"},
{"Kunduz","af-kdz"},
{"Khost","af-kho"},
{"Kunar","af-knr"},
{"Laghman","af-lag"},
{"Logar","af-log"},
{"Nangarhar","af-nan"},
{"Nimroz","af-nim"},
{"Nuristan","af-nur"},
{"Panjshayr","af-pan"},
{"Parwan","af-par"},
{"Paktiya","af-pia"},
{"Paktika","af-pka"},
{"Samangan","af-sam"},
{"Sar-e pul","af-sar"},
{"Takhar","af-tak"},
{"Uruzgan","af-uru"},
{"Wardak","af-war"},
{"Zabul","af-zab"},
{"Saint John","ag-04"},
{"Saint Mary","ag-05"},
{"Saint Paul","ag-06"},
{"Anguilla","ai"},
{"Berat","al-01"},
{"Durres","al-02"},
{"Elbasan","al-03"},
{"Fier","al-04"},
{"Gjirokaster","al-05"},
{"Korce","al-06"},
{"Kukes","al-07"},
{"Lezhe","al-08"},
{"Diber","al-09"},
{"Shkoder","al-10"},
{"Tirane","al-11"},
{"Vlore","al-12"},
{"Aragacotn","am-ag"},
{"Ararat","am-ar"},
{"Armavir","am-av"},
{"Erevan","am-er"},
{"Gegark'unik'","am-gr"},
{"Kotayk'","am-kt"},
{"Lori","am-lo"},
{"Sirak","am-sh"},
{"Syunik'","am-su"},
{"Tavus","am-tv"},
{"Vayoc Jor","am-vd"},
{"Bengo","ao-bgo"},
{"Benguela","ao-bgu"},
{"Bie","ao-bie"},
{"Cabinda","ao-cab"},
{"Kuando Kubango","ao-ccu"},
{"Cunene","ao-cnn"},
{"Kwanza Norte","ao-cno"},
{"Kwanza Sul","ao-cus"},
{"Huambo","ao-hua"},
{"Huila","ao-hui"},
{"Lunda Norte","ao-lno"},
{"Lunda Sul","ao-lsu"},
{"Luanda","ao-lua"},
{"Malange","ao-mal"},
{"Moxico","ao-mox"},
{"Namibe","ao-nam"},
{"Uige","ao-uig"},
{"Zaire","ao-zai"},
{"Antarctica","aq"},
{"Salta","ar-a"},
{"Buenos Aires","ar-b"},
{"Ciudad Autonoma de Buenos Aires","ar-c"},
{"San Luis","ar-d"},
{"Entre Rios","ar-e"},
{"La Rioja","ar-f"},
{"Santiago del Estero","ar-g"},
{"Chaco","ar-h"},
{"San Juan","ar-j"},
{"Catamarca","ar-k"},
{"La Pampa","ar-l"},
{"Mendoza","ar-m"},
{"Misiones","ar-n"},
{"Formosa","ar-p"},
{"Neuquen","ar-q"},
{"Rio Negro","ar-r"},
{"Santa Fe","ar-s"},
{"Tucuman","ar-t"},
{"Chubut","ar-u"},
{"Tierra del Fuego","ar-v"},
{"Corrientes","ar-w"},
{"Cordoba","ar-x"},
{"Jujuy","ar-y"},
{"Santa Cruz","ar-z"},
{"Burgenland","at-1"},
{"Karnten","at-2"},
{"Niederosterreich","at-3"},
{"Oberosterreich","at-4"},
{"Salzburg","at-5"},
{"Steiermark","at-6"},
{"Tirol","at-7"},
{"Vorarlberg","at-8"},
{"Wien","at-9"},
{"Australian Capital Territory","au-act"},
{"New South Wales","au-nsw"},
{"Northern Territory","au-nt"},
{"Queensland","au-qld"},
{"South Australia","au-sa"},
{"Tasmania","au-tas"},
{"Victoria","au-vic"},
{"Western Australia","au-wa"},
{"Abseron","az-abs"},
{"Agstafa","az-aga"},
{"Agcabadi","az-agc"},
{"Agdam","az-agm"},
{"Agdas","az-ags"},
{"Agsu","az-agu"},
{"Astara","az-ast"},
{"Baki","az-ba"},
{"Balakan","az-bal"},
{"Barda","az-bar"},
{"Beylaqan","az-bey"},
{"Bilasuvar","az-bil"},
{"Cabrayil","az-cab"},
{"Calilabad","az-cal"},
{"Daskasan","az-das"},
{"Fuzuli","az-fuz"},
{"Ganca","az-ga"},
{"Gadabay","az-gad"},
{"Goranboy","az-gor"},
{"Goycay","az-goy"},
{"Goygol","az-gyg"},
{"Haciqabul","az-hac"},
{"Imisli","az-imi"},
{"Ismayilli","az-ism"},
{"Kalbacar","az-kal"},
{"Lacin","az-lac"},
{"Lankaran","az-lan"},
{"Lerik","az-ler"},
{"Masalli","az-mas"},
{"Mingacevir","az-mi"},
{"Naftalan","az-na"},
{"Neftcala","az-nef"},
{"Naxcivan","az-nv"},
{"Oguz","az-ogu"},
{"Qabala","az-qab"},
{"Qax","az-qax"},
{"Qazax","az-qaz"},
{"Quba","az-qba"},
{"Qubadli","az-qbi"},
{"Qobustan","az-qob"},
{"Qusar","az-qus"},
{"Sabirabad","az-sab"},
{"Saki","az-sak"},
{"Salyan","az-sal"},
{"Saatli","az-sat"},
{"Samkir","az-skr"},
{"Sumqayit","az-sm"},
{"Samaxi","az-smi"},
{"Samux","az-smx"},
{"Sirvan","az-sr"},
{"Susa","az-sus"},
{"Tartar","az-tar"},
{"Tovuz","az-tov"},
{"Ucar","az-uca"},
{"Xankandi","az-xa"},
{"Xacmaz","az-xac"},
{"Xocali","az-xci"},
{"Xizi","az-xtz"},
{"Xocavand","az-xvd"},
{"Yardimli","az-yar"},
{"Yevlax","az-yev"},
{"Zangilan","az-zan"},
{"Zaqatala","az-zaq"},
{"Zardab","az-zar"},
{"Federacija Bosna i Hercegovina","ba-bih"},
{"Republika Srpska","ba-srp"},
{"Christ Church","bb-01"},
{"Saint James","bb-04"},
{"Saint Joseph","bb-06"},
{"Saint Michael","bb-08"},
{"Saint Peter","bb-09"},
{"Barisal","bd-a"},
{"Chittagong","bd-b"},
{"Dhaka","bd-c"},
{"Khulna","bd-d"},
{"Rajshahi","bd-e"},
{"Rangpur","bd-f"},
{"Sylhet","bd-g"},
{"Brussels Hoofdstedelijk Gewest","be-bru"},
{"Antwerpen","be-van"},
{"Vlaams-Brabant","be-vbr"},
{"Oost-Vlaanderen","be-vov"},
{"West-Vlaanderen","be-vwv"},
{"Brabant Wallon","be-wbr"},
{"Hainaut","be-wht"},
{"Liege","be-wlg"},
{"Luxembourg","be-wlx"},
{"Namur","be-wna"},
{"Banwa","bf-abn"},
{"Bale","bf-bal"},
{"Bam","bf-bam"},
{"Bazega","bf-baz"},
{"Bougouriba","bf-bgr"},
{"Boulgou","bf-blg"},
{"Boulkiemde","bf-blk"},
{"Comoe","bf-com"},
{"Ganzourgou","bf-gan"},
{"Gnagna","bf-gna"},
{"Gourma","bf-gou"},
{"Houet","bf-hou"},
{"Ioba","bf-iob"},
{"Kadiogo","bf-kad"},
{"Kenedougou","bf-ken"},
{"Komondjari","bf-kmd"},
{"Kompienga","bf-kmp"},
{"Koulpelogo","bf-kop"},
{"Kossi","bf-kos"},
{"Kouritenga","bf-kot"},
{"Kourweogo","bf-kow"},
{"Leraba","bf-ler"},
{"Loroum","bf-lor"},
{"Mouhoun","bf-mou"},
{"Namentenga","bf-nam"},
{"Nahouri","bf-nao"},
{"Nayala","bf-nay"},
{"Noumbiel","bf-nou"},
{"Oubritenga","bf-oub"},
{"Oudalan","bf-oud"},
{"Passore","bf-pas"},
{"Poni","bf-pon"},
{"Seno","bf-sen"},
{"Sissili","bf-sis"},
{"Sanmatenga","bf-smt"},
{"Sanguie","bf-sng"},
{"Soum","bf-som"},
{"Sourou","bf-sor"},
{"Tapoa","bf-tap"},
{"Tui","bf-tui"},
{"Yagha","bf-yag"},
{"Yatenga","bf-yat"},
{"Ziro","bf-zir"},
{"Zondoma","bf-zon"},
{"Zoundweogo","bf-zou"},
{"Blagoevgrad","bg-01"},
{"Burgas","bg-02"},
{"Varna","bg-03"},
{"Veliko Tarnovo","bg-04"},
{"Vidin","bg-05"},
{"Vratsa","bg-06"},
{"Gabrovo","bg-07"},
{"Dobrich","bg-08"},
{"Kardzhali","bg-09"},
{"Kyustendil","bg-10"},
{"Lovech","bg-11"},
{"Montana","bg-12"},
{"Pazardzhik","bg-13"},
{"Pernik","bg-14"},
{"Pleven","bg-15"},
{"Plovdiv","bg-16"},
{"Razgrad","bg-17"},
{"Ruse","bg-18"},
{"Silistra","bg-19"},
{"Sliven","bg-20"},
{"Smolyan","bg-21"},
{"Sofia (stolitsa)","bg-22"},
{"Sofia","bg-23"},
{"Stara Zagora","bg-24"},
{"Targovishte","bg-25"},
{"Haskovo","bg-26"},
{"Shumen","bg-27"},
{"Yambol","bg-28"},
{"Limburg","bg-vli"},
{"Al Asimah","bh-13"},
{"Al Muharraq","bh-15"},
{"Al Wusta","bh-16"},
{"Ash Shamaliyah","bh-17"},
{"Bubanza","bi-bb"},
{"Bujumbura Mairie","bi-bm"},
{"Bururi","bi-br"},
{"Cankuzo","bi-ca"},
{"Cibitoke","bi-ci"},
{"Gitega","bi-gi"},
{"Kirundo","bi-ki"},
{"Karuzi","bi-kr"},
{"Kayanza","bi-ky"},
{"Makamba","bi-ma"},
{"Muramvya","bi-mu"},
{"Mwaro","bi-mw"},
{"Muyinga","bi-my"},
{"Ngozi","bi-ng"},
{"Rutana","bi-rt"},
{"Ruyigi","bi-ry"},
{"Atacora","bj-ak"},
{"Alibori","bj-al"},
{"Atlantique","bj-aq"},
{"Borgou","bj-bo"},
{"Collines","bj-co"},
{"Donga","bj-do"},
{"Couffo","bj-ko"},
{"Littoral","bj-li"},
{"Mono","bj-mo"},
{"Oueme","bj-ou"},
{"Plateau","bj-pl"},
{"Zou","bj-zo"},
{"Saint Barthelemy","bl"},
{"Belait","bn-be"},
{"Brunei-Muara","bn-bm"},
{"Temburong","bn-te"},
{"Tutong","bn-tu"},
{"El Beni","bo-b"},
{"Cochabamba","bo-c"},
{"Chuquisaca","bo-h"},
{"La Paz","bo-l"},
{"Pando","bo-n"},
{"Oruro","bo-o"},
{"Potosi","bo-p"},
{"Tarija","bo-t"},
{"Bonaire","bq-bo"},
{"Saba","bq-sa"},
{"Sint Eustatius","bq-se"},
{"Acre","br-ac"},
{"Alagoas","br-al"},
{"Amazonas","br-am"},
{"Amapa","br-ap"},
{"Bahia","br-ba"},
{"Ceara","br-ce"},
{"Distrito Federal","br-df"},
{"Espirito Santo","br-es"},
{"Goias","br-go"},
{"Maranhao","br-ma"},
{"Minas Gerais","br-mg"},
{"Mato Grosso do Sul","br-ms"},
{"Mato Grosso","br-mt"},
{"Para","br-pa"},
{"Paraiba","br-pb"},
{"Pernambuco","br-pe"},
{"Piaui","br-pi"},
{"Parana","br-pr"},
{"Rio de Janeiro","br-rj"},
{"Rio Grande do Norte","br-rn"},
{"Rondonia","br-ro"},
{"Roraima","br-rr"},
{"Rio Grande do Sul","br-rs"},
{"Santa Catarina","br-sc"},
{"Sergipe","br-se"},
{"Sao Paulo","br-sp"},
{"Tocantins","br-to"},
{"Fresh Creek","bs-fc"},
{"Freeport","bs-fp"},
{"Harbour Island","bs-hi"},
{"High Rock","bs-hr"},
{"Long Island","bs-li"},
{"Marsh Harbour","bs-mh"},
{"New Providence","bs-np"},
{"Rock Sound","bs-rs"},
{"Paro","bt-11"},
{"Chhukha","bt-12"},
{"Ha","bt-13"},
{"Thimphu","bt-15"},
{"Dagana","bt-22"},
{"Punakha","bt-23"},
{"Trongsa","bt-32"},
{"Zhemgang","bt-34"},
{"Monggar","bt-42"},
{"Gasa","bt-ga"},
{"Trashi Yangtse","bt-ty"},
{"Central","bw-ce"},
{"Ghanzi","bw-gh"},
{"Kgalagadi","bw-kg"},
{"Kgatleng","bw-kl"},
{"Kweneng","bw-kw"},
{"North-East","bw-ne"},
{"North-West","bw-nw"},
{"South-East","bw-se"},
{"Southern","bw-so"},
{"Brestskaya Voblasts'","by-br"},
{"Homyel'skaya Voblasts'","by-ho"},
{"Hrodzyenskaya Voblasts'","by-hr"},
{"Mahilyowskaya Voblasts'","by-ma"},
{"Minskaya Voblasts'","by-mi"},
{"Vitsyebskaya Voblasts'","by-vi"},
{"Belize","bz-bz"},
{"Cayo","bz-cy"},
{"Corozal","bz-czl"},
{"Orange Walk","bz-ow"},
{"Stann Creek","bz-sc"},
{"Toledo","bz-tol"},
{"Alberta","ca-ab"},
{"British Columbia","ca-bc"},
{"Manitoba","ca-mb"},
{"New Brunswick","ca-nb"},
{"Newfoundland and Labrador","ca-nl"},
{"Nova Scotia","ca-ns"},
{"Northwest Territories","ca-nt"},
{"Nunavut","ca-nu"},
{"Ontario","ca-on"},
{"Prince Edward Island","ca-pe"},
{"Quebec","ca-qc"},
{"Saskatchewan","ca-sk"},
{"Yukon","ca-yt"},
{"Bas-Congo","cd-bc"},
{"Bandundu","cd-bn"},
{"Equateur","cd-eq"},
{"Katanga","cd-ka"},
{"Kasai-Oriental","cd-ke"},
{"Kinshasa","cd-kn"},
{"Kasai-Occidental","cd-kw"},
{"Maniema","cd-ma"},
{"Nord-Kivu","cd-nk"},
{"Orientale","cd-or"},
{"Sud-Kivu","cd-sk"},
{"Ouham","cf-ac"},
{"Bamingui-Bangoran","cf-bb"},
{"Bangui","cf-bgf"},
{"Basse-Kotto","cf-bk"},
{"Haute-Kotto","cf-hk"},
{"Haut-Mbomou","cf-hm"},
{"Mambere-Kadei","cf-hs"},
{"Nana-Grebizi","cf-kb"},
{"Kemo","cf-kg"},
{"Lobaye","cf-lb"},
{"Mbomou","cf-mb"},
{"Ombella-Mpoko","cf-mp"},
{"Nana-Mambere","cf-nm"},
{"Ouham-Pende","cf-op"},
{"Sangha-Mbaere","cf-se"},
{"Ouaka","cf-uk"},
{"Bouenza","cg-11"},
{"Pool","cg-12"},
{"Sangha","cg-13"},
{"Plateaux","cg-14"},
{"Cuvette-Ouest","cg-15"},
{"Pointe-Noire","cg-16"},
{"Lekoumou","cg-2"},
{"Likouala","cg-7"},
{"Cuvette","cg-8"},
{"Niari","cg-9"},
{"Brazzaville","cg-bzv"},
{"Lagunes","ci-01"},
{"Haut-Sassandra","ci-02"},
{"Savanes","ci-03"},
{"Vallee du Bandama","ci-04"},
{"Moyen-Comoe","ci-05"},
{"Dix-Huit Montagnes","ci-06"},
{"Lacs","ci-07"},
{"Zanzan","ci-08"},
{"Bas-Sassandra","ci-09"},
{"Denguele","ci-10"},
{"N'zi-Comoe","ci-11"},
{"Marahoue","ci-12"},
{"Sud-Comoe","ci-13"},
{"Worodougou","ci-14"},
{"Sud-Bandama","ci-15"},
{"Agneby","ci-16"},
{"Bafing","ci-17"},
{"Fromager","ci-18"},
{"Moyen-Cavally","ci-19"},
{"Cook Islands","ck"},
{"Aysen","cl-ai"},
{"Antofagasta","cl-an"},
{"Arica y Parinacota","cl-ap"},
{"Araucania","cl-ar"},
{"Atacama","cl-at"},
{"Biobio","cl-bi"},
{"Coquimbo","cl-co"},
{"Libertador General Bernardo O'Higgins","cl-li"},
{"Los Lagos","cl-ll"},
{"Los Rios","cl-lr"},
{"Magallanes","cl-ma"},
{"Maule","cl-ml"},
{"Region Metropolitana de Santiago","cl-rm"},
{"Tarapaca","cl-ta"},
{"Valparaiso","cl-vs"},
{"Adamaoua","cm-ad"},
{"Centre","cm-ce"},
{"Extreme-Nord","cm-en"},
{"Est","cm-es"},
{"Nord","cm-no"},
{"Nord-Ouest","cm-nw"},
{"Ouest","cm-ou"},
{"Sud","cm-su"},
{"Sud-Ouest","cm-sw"},
{"Beijing","cn-11"},
{"Tianjin","cn-12"},
{"Hebei","cn-13"},
{"Shanxi","cn-14"},
{"Nei Mongol","cn-15"},
{"Liaoning","cn-21"},
{"Jilin","cn-22"},
{"Heilongjiang","cn-23"},
{"Shanghai","cn-31"},
{"Jiangsu","cn-32"},
{"Zhejiang","cn-33"},
{"Anhui","cn-34"},
{"Fujian","cn-35"},
{"Jiangxi","cn-36"},
{"Shandong","cn-37"},
{"Henan","cn-41"},
{"Hubei","cn-42"},
{"Hunan","cn-43"},
{"Guangdong","cn-44"},
{"Guangxi","cn-45"},
{"Hainan","cn-46"},
{"Chongqing","cn-50"},
{"Sichuan","cn-51"},
{"Guizhou","cn-52"},
{"Yunnan","cn-53"},
{"Xizang","cn-54"},
{"Shaanxi","cn-61"},
{"Gansu","cn-62"},
{"Qinghai","cn-63"},
{"Ningxia","cn-64"},
{"Xinjiang","cn-65"},
{"Antioquia","co-ant"},
{"Arauca","co-ara"},
{"Atlantico","co-atl"},
{"Bolivar","co-bol"},
{"Boyaca","co-boy"},
{"Caldas","co-cal"},
{"Caqueta","co-caq"},
{"Casanare","co-cas"},
{"Cauca","co-cau"},
{"Cesar","co-ces"},
{"Cundinamarca","co-cun"},
{"Distrito Capital de Bogota","co-dc"},
{"Guainia","co-gua"},
{"Guaviare","co-guv"},
{"Choco","co-cho"},
{"La Guajira","co-lag"},
{"Magdalena","co-mag"},
{"Meta","co-met"},
{"Narino","co-nar"},
{"Norte de Santander","co-nsa"},
{"Putumayo","co-put"},
{"Quindio","co-qui"},
{"Risaralda","co-ris"},
{"Santander","co-san"},
{"San Andres, Providencia y Santa Catalina","co-sap"},
{"Sucre","co-suc"},
{"Tolima","co-tol"},
{"Valle del Cauca","co-vac"},
{"Vaupes","co-vau"},
{"Vichada","co-vid"},
{"Alajuela","cr-a"},
{"Cartago","cr-c"},
{"Guanacaste","cr-g"},
{"Heredia","cr-h"},
{"Limon","cr-l"},
{"Puntarenas","cr-p"},
{"San Jose","cr-sj"},
{"Pinar del Rio","cu-01"},
{"La Habana","cu-02"},
{"Matanzas","cu-04"},
{"Villa Clara","cu-05"},
{"Cienfuegos","cu-06"},
{"Sancti Spiritus","cu-07"},
{"Ciego de Avila","cu-08"},
{"Camaguey","cu-09"},
{"Las Tunas","cu-10"},
{"Holguin","cu-11"},
{"Granma","cu-12"},
{"Santiago de Cuba","cu-13"},
{"Guantanamo","cu-14"},
{"Artemisa","cu-15"},
{"Mayabeque","cu-16"},
{"Isla de la Juventud","cu-99"},
{"Brava","cv-br"},
{"Boa Vista","cv-bv"},
{"Santa Catarina do Fogo","cv-cf"},
{"Maio","cv-ma"},
{"Mosteiros","cv-mo"},
{"Paul","cv-pa"},
{"Porto Novo","cv-pn"},
{"Praia","cv-pr"},
{"Ribeira Brava","cv-rb"},
{"Ribeira Grande","cv-rg"},
{"Ribeira Grande de Santiago","cv-rs"},
{"Sao Domingos","cv-sd"},
{"Sao Filipe","cv-sf"},
{"Sal","cv-sl"},
{"Sao Miguel","cv-sm"},
{"Sao Salvador do Mundo","cv-ss"},
{"Sao Vicente","cv-sv"},
{"Tarrafal","cv-ta"},
{"Tarrafal de Sao Nicolau","cv-ts"},
{"Curacao","cw"},
{"Christmas Island","cx"},
{"Lefkosia","cy-01"},
{"Lemesos","cy-02"},
{"Larnaka","cy-03"},
{"Ammochostos","cy-04"},
{"Pafos","cy-05"},
{"Keryneia","cy-06"},
{"Jihocesky kraj","cz-jc"},
{"Jihomoravsky kraj","cz-jm"},
{"Karlovarsky kraj","cz-ka"},
{"Kralovehradecky kraj","cz-kr"},
{"Liberecky kraj","cz-li"},
{"Moravskoslezsky kraj","cz-mo"},
{"Olomoucky kraj","cz-ol"},
{"Pardubicky kraj","cz-pa"},
{"Plzensky kraj","cz-pl"},
{"Praha, hlavni mesto","cz-pr"},
{"Stredocesky kraj","cz-st"},
{"Ustecky kraj","cz-us"},
{"Vysocina kraj","cz-vy"},
{"Zlinsky kraj","cz-zl"},
{"Brandenburg","de-bb"},
{"Berlin","de-be"},
{"Baden-Wurttemberg","de-bw"},
{"Bayern","de-by"},
{"Bremen","de-hb"},
{"Hessen","de-he"},
{"Hamburg","de-hh"},
{"Mecklenburg-Vorpommern","de-mv"},
{"Niedersachsen","de-ni"},
{"Nordrhein-Westfalen","de-nw"},
{"Rheinland-Pfalz","de-rp"},
{"Schleswig-Holstein","de-sh"},
{"Saarland","de-sl"},
{"Sachsen","de-sn"},
{"Sachsen-Anhalt","de-st"},
{"Thuringen","de-th"},
{"Arta","dj-ar"},
{"Ali Sabieh","dj-as"},
{"Dikhil","dj-di"},
{"Djibouti","dj-dj"},
{"Obock","dj-ob"},
{"Tadjourah","dj-ta"},
{"Nordjylland","dk-81"},
{"Midtjylland","dk-82"},
{"Syddanmark","dk-83"},
{"Hovedstaden","dk-84"},
{"Sjelland","dk-85"},
{"Saint Andrew","dm-02"},
{"Saint David","dm-03"},
{"Saint George","dm-04"},
{"Saint Luke","dm-07"},
{"Saint Mark","dm-08"},
{"Saint Patrick","dm-09"},
{"Distrito Nacional","do-01"},
{"Azua","do-02"},
{"Baoruco","do-03"},
{"Barahona","do-04"},
{"Dajabon","do-05"},
{"Duarte","do-06"},
{"Elias Pina","do-07"},
{"El Seibo","do-08"},
{"Espaillat","do-09"},
{"Independencia","do-10"},
{"La Altagracia","do-11"},
{"La Romana","do-12"},
{"La Vega","do-13"},
{"Maria Trinidad Sanchez","do-14"},
{"Monte Cristi","do-15"},
{"Pedernales","do-16"},
{"Peravia","do-17"},
{"Puerto Plata","do-18"},
{"Salcedo","do-19"},
{"Samana","do-20"},
{"San Cristobal","do-21"},
{"San Pedro De Macoris","do-23"},
{"Sanchez Ramirez","do-24"},
{"Santiago","do-25"},
{"Santiago Rodriguez","do-26"},
{"Valverde","do-27"},
{"Monsenor Nouel","do-28"},
{"Monte Plata","do-29"},
{"Hato Mayor","do-30"},
{"Adrar","dz-01"},
{"Chlef","dz-02"},
{"Laghouat","dz-03"},
{"Oum el Bouaghi","dz-04"},
{"Batna","dz-05"},
{"Bejaia","dz-06"},
{"Biskra","dz-07"},
{"Bechar","dz-08"},
{"Blida","dz-09"},
{"Bouira","dz-10"},
{"Tamanrasset","dz-11"},
{"Tebessa","dz-12"},
{"Tlemcen","dz-13"},
{"Tiaret","dz-14"},
{"Tizi Ouzou","dz-15"},
{"Alger","dz-16"},
{"Djelfa","dz-17"},
{"Setif","dz-19"},
{"Saida","dz-20"},
{"Skikda","dz-21"},
{"Sidi Bel Abbes","dz-22"},
{"Annaba","dz-23"},
{"Guelma","dz-24"},
{"Constantine","dz-25"},
{"Medea","dz-26"},
{"Mostaganem","dz-27"},
{"Msila","dz-28"},
{"Mascara","dz-29"},
{"Ouargla","dz-30"},
{"Oran","dz-31"},
{"El Bayadh","dz-32"},
{"Illizi","dz-33"},
{"Bordj Bou Arreridj","dz-34"},
{"Boumerdes","dz-35"},
{"El Tarf","dz-36"},
{"Tindouf","dz-37"},
{"Tissemsilt","dz-38"},
{"El Oued","dz-39"},
{"Khenchela","dz-40"},
{"Souk Ahras","dz-41"},
{"Tipaza","dz-42"},
{"Mila","dz-43"},
{"Ain Defla","dz-44"},
{"Naama","dz-45"},
{"Ain Temouchent","dz-46"},
{"Ghardaia","dz-47"},
{"Relizane","dz-48"},
{"Azuay","ec-a"},
{"Carchi","ec-c"},
{"Orellana","ec-d"},
{"Esmeraldas","ec-e"},
{"Canar","ec-f"},
{"Guayas","ec-g"},
{"Chimborazo","ec-h"},
{"Imbabura","ec-i"},
{"Loja","ec-l"},
{"Manabi","ec-m"},
{"Napo","ec-n"},
{"El Oro","ec-o"},
{"Pichincha","ec-p"},
{"Morona-Santiago","ec-s"},
{"Santa Elena","ec-se"},
{"Tungurahua","ec-t"},
{"Sucumbios","ec-u"},
{"Galapagos","ec-w"},
{"Cotopaxi","ec-x"},
{"Pastaza","ec-y"},
{"Zamora-Chinchipe","ec-z"},
{"Harjumaa","ee-37"},
{"Hiiumaa","ee-39"},
{"Ida-Virumaa","ee-44"},
{"Jogevamaa","ee-49"},
{"Jarvamaa","ee-51"},
{"Laanemaa","ee-57"},
{"Laane-Virumaa","ee-59"},
{"Polvamaa","ee-65"},
{"Parnumaa","ee-67"},
{"Raplamaa","ee-70"},
{"Saaremaa","ee-74"},
{"Tartumaa","ee-78"},
{"Valgamaa","ee-82"},
{"Viljandimaa","ee-84"},
{"Vorumaa","ee-86"},
{"Al Iskandariyah","eg-alx"},
{"Aswan","eg-asn"},
{"Asyut","eg-ast"},
{"Al Bahr al Ahmar","eg-ba"},
{"Al Buhayrah","eg-bh"},
{"Bani Suwayf","eg-bns"},
{"Al Qahirah","eg-c"},
{"Ad Daqahliyah","eg-dk"},
{"Dumyat","eg-dt"},
{"Al Fayyum","eg-fym"},
{"Al Gharbiyah","eg-gh"},
{"Al Jizah","eg-gz"},
{"Al Ismailiyah","eg-is"},
{"Janub Sina'","eg-js"},
{"Al Qalyubiyah","eg-kb"},
{"Kafr ash Shaykh","eg-kfs"},
{"Qina","eg-kn"},
{"Al Uqsur","eg-lx"},
{"Al Minya","eg-mn"},
{"Al Minufiyah","eg-mnf"},
{"Matruh","eg-mt"},
{"Bur Sa'id","eg-pts"},
{"Suhaj","eg-shg"},
{"Ash Sharqiyah","eg-shr"},
{"Shamal Sina'","eg-sin"},
{"As Suways","eg-suz"},
{"Al Wadi al Jadid","eg-wad"},
{"Ansaba","er-an"},
{"Janubi al Bahri al Ahmar","er-dk"},
{"Al Janubi","er-du"},
{"Qash-Barkah","er-gb"},
{"Al Awsat","er-ma"},
{"Shimali al Bahri al Ahmar","er-sk"},
{"Andalucia","es-an"},
{"Aragon","es-ar"},
{"Asturias, Principado de","es-as"},
{"Cantabria","es-cb"},
{"Ceuta","es-ce"},
{"Castilla y Leon","es-cl"},
{"Castilla-La Mancha","es-cm"},
{"Canarias","es-cn"},
{"Catalunya","es-ct"},
{"Extremadura","es-ex"},
{"Galicia","es-ga"},
{"Illes Balears","es-ib"},
{"Murcia, Region de","es-mc"},
{"Madrid, Comunidad de","es-md"},
{"Melilla","es-ml"},
{"Navarra, Comunidad Foral de","es-nc"},
{"Pais Vasco","es-pv"},
{"Valenciana, Comunidad","es-vc"},
{"Adis Abeba","et-aa"},
{"Afar","et-af"},
{"Amara","et-am"},
{"Binshangul Gumuz","et-be"},
{"Dire Dawa","et-dd"},
{"Gambela Hizboch","et-ga"},
{"Hareri Hizb","et-ha"},
{"Oromiya","et-or"},
{"YeDebub Biheroch Bihereseboch na Hizboch","et-sn"},
{"Sumale","et-so"},
{"Tigray","et-ti"},
{"Etela-Karjala","fi-02"},
{"Etela-Pohjanmaa","fi-03"},
{"Etela-Savo","fi-04"},
{"Kainuu","fi-05"},
{"Kanta-Hame","fi-06"},
{"Keski-Pohjanmaa","fi-07"},
{"Keski-Suomi","fi-08"},
{"Kymenlaakso","fi-09"},
{"Lappi","fi-10"},
{"Pirkanmaa","fi-11"},
{"Pohjanmaa","fi-12"},
{"Pohjois-Karjala","fi-13"},
{"Pohjois-Pohjanmaa","fi-14"},
{"Pohjois-Savo","fi-15"},
{"Paijat-Hame","fi-16"},
{"Satakunta","fi-17"},
{"Uusimaa","fi-18"},
{"Varsinais-Suomi","fi-19"},
{"Northern","fj-n"},
{"Western","fj-w"},
{"Kosrae","fm-ksa"},
{"Pohnpei","fm-pni"},
{"Chuuk","fm-trk"},
{"Yap","fm-yap"},
{"Alsace","fr-a"},
{"Aquitaine","fr-b"},
{"Auvergne","fr-c"},
{"Bourgogne","fr-d"},
{"Bretagne","fr-e"},
{"Champagne-Ardenne","fr-g"},
{"Corse","fr-h"},
{"Franche-Comte","fr-i"},
{"Ile-de-France","fr-j"},
{"Languedoc-Roussillon","fr-k"},
{"Limousin","fr-l"},
{"Lorraine","fr-m"},
{"Midi-Pyrenees","fr-n"},
{"Nord-Pas-de-Calais","fr-o"},
{"Basse-Normandie","fr-p"},
{"Haute-Normandie","fr-q"},
{"Pays de la Loire","fr-r"},
{"Picardie","fr-s"},
{"Poitou-Charentes","fr-t"},
{"Provence-Alpes-Cote d'Azur","fr-u"},
{"Rhone-Alpes","fr-v"},
{"Estuaire","ga-1"},
{"Haut-Ogooue","ga-2"},
{"Moyen-Ogooue","ga-3"},
{"Ngounie","ga-4"},
{"Nyanga","ga-5"},
{"Ogooue-Ivindo","ga-6"},
{"Ogooue-Lolo","ga-7"},
{"Ogooue-Maritime","ga-8"},
{"Woleu-Ntem","ga-9"},
{"England","gb-eng"},
{"Northern Ireland","gb-nir"},
{"Scotland","gb-sct"},
{"Wales","gb-wls"},
{"Akhalk'alak'is Raioni","ge-04"},
{"Baghdat'is Raioni","ge-09"},
{"Borjomis Raioni","ge-11"},
{"Goris Raioni","ge-19"},
{"Javis Raioni","ge-23"},
{"K'arelis Raioni","ge-24"},
{"Khashuris Raioni","ge-28"},
{"Vanis Raioni","ge-61"},
{"Abkhazia","ge-ab"},
{"Ajaria","ge-aj"},
{"Guria","ge-gu"},
{"Imereti","ge-im"},
{"Kakheti","ge-ka"},
{"Kvemo Kartli","ge-kk"},
{"Mtskheta-Mtianeti","ge-mm"},
{"Racha-Lechkhumi and Kvemo Svaneti","ge-rl"},
{"Samtskhe-Javakheti","ge-sj"},
{"Shida Kartli","ge-sk"},
{"Samegrelo and Zemo Svaneti","ge-sz"},
{"T'bilisi","ge-tbs"},
{"Greater Accra","gh-aa"},
{"Ashanti","gh-ah"},
{"Brong-Ahafo","gh-ba"},
{"Eastern","gh-ep"},
{"Volta","gh-tv"},
{"Upper East","gh-ue"},
{"Upper West","gh-uw"},
{"Gibraltar","gi"},
{"Kommune Kujalleq","gl-ku"},
{"Qaasuitsup Kommunia","gl-qa"},
{"Qeqqata Kommunia","gl-qe"},
{"Kommuneqarfik Sermersooq","gl-sm"},
{"Banjul","gm-b"},
{"Lower River","gm-l"},
{"Central River","gm-m"},
{"North Bank","gm-n"},
{"Upper River","gm-u"},
{"Beyla","gn-be"},
{"Boffa","gn-bf"},
{"Boke","gn-bk"},
{"Conakry","gn-c"},
{"Coyah","gn-co"},
{"Dabola","gn-db"},
{"Dinguiraye","gn-di"},
{"Dalaba","gn-dl"},
{"Dubreka","gn-du"},
{"Faranah","gn-fa"},
{"Forecariah","gn-fo"},
{"Fria","gn-fr"},
{"Gaoual","gn-ga"},
{"Gueckedou","gn-gu"},
{"Kankan","gn-ka"},
{"Koubia","gn-kb"},
{"Kindia","gn-kd"},
{"Kerouane","gn-ke"},
{"Koundara","gn-kn"},
{"Kouroussa","gn-ko"},
{"Kissidougou","gn-ks"},
{"Labe","gn-la"},
{"Lelouma","gn-le"},
{"Lola","gn-lo"},
{"Macenta","gn-mc"},
{"Mandiana","gn-md"},
{"Mali","gn-ml"},
{"Mamou","gn-mm"},
{"Nzerekore","gn-nz"},
{"Pita","gn-pi"},
{"Siguiri","gn-si"},
{"Telimele","gn-te"},
{"Tougue","gn-to"},
{"Yomou","gn-yo"},
{"Guadeloupe","gp"},
{"Annobon","gq-an"},
{"Bioko Norte","gq-bn"},
{"Bioko Sur","gq-bs"},
{"Centro Sur","gq-cs"},
{"Kie-Ntem","gq-kn"},
{"Litoral","gq-li"},
{"Wele-Nzas","gq-wn"},
{"Aitolia kai Akarnania","gr-01"},
{"Voiotia","gr-03"},
{"Evvoia","gr-04"},
{"Evritania","gr-05"},
{"Fthiotis","gr-06"},
{"Fokis","gr-07"},
{"Argolis","gr-11"},
{"Arkadhia","gr-12"},
{"Akhaia","gr-13"},
{"Ilia","gr-14"},
{"Korinthia","gr-15"},
{"Lakonia","gr-16"},
{"Messinia","gr-17"},
{"Zakinthos","gr-21"},
{"Kerkira","gr-22"},
{"Kefallinia","gr-23"},
{"Levkas","gr-24"},
{"Thesprotia","gr-32"},
{"Ioannina","gr-33"},
{"Preveza","gr-34"},
{"Kardhitsa","gr-41"},
{"Larisa","gr-42"},
{"Magnisia","gr-43"},
{"Trikala","gr-44"},
{"Grevena","gr-51"},
{"Drama","gr-52"},
{"Imathia","gr-53"},
{"Thessaloniki","gr-54"},
{"Kavala","gr-55"},
{"Kastoria","gr-56"},
{"Kilkis","gr-57"},
{"Kozani","gr-58"},
{"Pella","gr-59"},
{"Pieria","gr-61"},
{"Serrai","gr-62"},
{"Florina","gr-63"},
{"Khalkidhiki","gr-64"},
{"Evros","gr-71"},
{"Xanthi","gr-72"},
{"Rodhopi","gr-73"},
{"Dhodhekanisos","gr-81"},
{"Kikladhes","gr-82"},
{"Lesvos","gr-83"},
{"Samos","gr-84"},
{"Khios","gr-85"},
{"Iraklion","gr-91"},
{"Lasithi","gr-92"},
{"Rethimni","gr-93"},
{"Khania","gr-94"},
{"Attiki","gr-a1"},
{"Alta Verapaz","gt-av"},
{"Baja Verapaz","gt-bv"},
{"Chimaltenango","gt-cm"},
{"Chiquimula","gt-cq"},
{"Escuintla","gt-es"},
{"Guatemala","gt-gu"},
{"Huehuetenango","gt-hu"},
{"Izabal","gt-iz"},
{"Jalapa","gt-ja"},
{"Jutiapa","gt-ju"},
{"Peten","gt-pe"},
{"El Progreso","gt-pr"},
{"Quiche","gt-qc"},
{"Quetzaltenango","gt-qz"},
{"Retalhuleu","gt-re"},
{"Sacatepequez","gt-sa"},
{"San Marcos","gt-sm"},
{"Solola","gt-so"},
{"Santa Rosa","gt-sr"},
{"Suchitepequez","gt-su"},
{"Totonicapan","gt-to"},
{"Zacapa","gt-za"},
{"Bafata","gw-ba"},
{"Bolama","gw-bl"},
{"Biombo","gw-bm"},
{"Bissau","gw-bs"},
{"Cacheu","gw-ca"},
{"Gabu","gw-ga"},
{"Oio","gw-oi"},
{"Quinara","gw-qu"},
{"Tombali","gw-to"},
{"Cuyuni-Mazaruni","gy-cu"},
{"Demerara-Mahaica","gy-de"},
{"East Berbice-Corentyne","gy-eb"},
{"Essequibo Islands-West Demerara","gy-es"},
{"Mahaica-Berbice","gy-ma"},
{"Pomeroon-Supenaam","gy-pm"},
{"Upper Demerara-Berbice","gy-ud"},
{"Atlantida","hn-at"},
{"Colon","hn-cl"},
{"Comayagua","hn-cm"},
{"Copan","hn-cp"},
{"Cortes","hn-cr"},
{"El Paraiso","hn-ep"},
{"Francisco Morazan","hn-fm"},
{"Gracias a Dios","hn-gd"},
{"Choluteca","hn-ch"},
{"Islas de la Bahia","hn-ib"},
{"Intibuca","hn-in"},
{"Lempira","hn-le"},
{"Ocotepeque","hn-oc"},
{"Olancho","hn-ol"},
{"Santa Barbara","hn-sb"},
{"Valle","hn-va"},
{"Yoro","hn-yo"},
{"Zagrebacka zupanija","hr-01"},
{"Krapinsko-zagorska zupanija","hr-02"},
{"Sisacko-moslavacka zupanija","hr-03"},
{"Karlovacka zupanija","hr-04"},
{"Varazdinska zupanija","hr-05"},
{"Koprivnicko-krizevacka zupanija","hr-06"},
{"Bjelovarsko-bilogorska zupanija","hr-07"},
{"Primorsko-goranska zupanija","hr-08"},
{"Licko-senjska zupanija","hr-09"},
{"Viroviticko-podravska zupanija","hr-10"},
{"Pozesko-slavonska zupanija","hr-11"},
{"Brodsko-posavska zupanija","hr-12"},
{"Zadarska zupanija","hr-13"},
{"Osjecko-baranjska zupanija","hr-14"},
{"Sibensko-kninska zupanija","hr-15"},
{"Vukovarsko-srijemska zupanija","hr-16"},
{"Splitsko-dalmatinska zupanija","hr-17"},
{"Istarska zupanija","hr-18"},
{"Dubrovacko-neretvanska zupanija","hr-19"},
{"Medimurska zupanija","hr-20"},
{"Grad Zagreb","hr-21"},
{"Artibonite","ht-ar"},
{"Grand' Anse","ht-ga"},
{"Nord-Est","ht-ne"},
{"Nippes","ht-ni"},
{"Sud-Est","ht-se"},
{"Baranya","hu-ba"},
{"Bekes","hu-be"},
{"Bacs-Kiskun","hu-bk"},
{"Budapest","hu-bu"},
{"Borsod-Abauj-Zemplen","hu-bz"},
{"Csongrad","hu-cs"},
{"Fejer","hu-fe"},
{"Gyor-Moson-Sopron","hu-gs"},
{"Hajdu-Bihar","hu-hb"},
{"Heves","hu-he"},
{"Jasz-Nagykun-Szolnok","hu-jn"},
{"Komarom-Esztergom","hu-ke"},
{"Nograd","hu-no"},
{"Pest","hu-pe"},
{"Somogy","hu-so"},
{"Szabolcs-Szatmar-Bereg","hu-sz"},
{"Tolna","hu-to"},
{"Vas","hu-va"},
{"Veszprem","hu-ve"},
{"Zala","hu-za"},
{"Aargau","ch-ag"},
{"Appenzell Innerrhoden","ch-ai"},
{"Appenzell Ausserrhoden","ch-ar"},
{"Bern","ch-be"},
{"Basel-Landschaft","ch-bl"},
{"Basel-Stadt","ch-bs"},
{"Fribourg","ch-fr"},
{"Geneve","ch-ge"},
{"Glarus","ch-gl"},
{"Graubunden","ch-gr"},
{"Jura","ch-ju"},
{"Luzern","ch-lu"},
{"Neuchatel","ch-ne"},
{"Nidwalden","ch-nw"},
{"Obwalden","ch-ow"},
{"Sankt Gallen","ch-sg"},
{"Schaffhausen","ch-sh"},
{"Solothurn","ch-so"},
{"Schwyz","ch-sz"},
{"Thurgau","ch-tg"},
{"Ticino","ch-ti"},
{"Uri","ch-ur"},
{"Vaud","ch-vd"},
{"Valais","ch-vs"},
{"Zug","ch-zg"},
{"Zurich","ch-zh"},
{"Aceh","id-ac"},
{"Bali","id-ba"},
{"Bangka Belitung","id-bb"},
{"Bengkulu","id-be"},
{"Banten","id-bt"},
{"Gorontalo","id-go"},
{"Jambi","id-ja"},
{"Jawa Barat","id-jb"},
{"Jawa Timur","id-ji"},
{"Jakarta Raya","id-jk"},
{"Jawa Tengah","id-jt"},
{"Kalimantan Barat","id-kb"},
{"Kalimantan Timur","id-ki"},
{"Kepulauan Riau","id-kr"},
{"Kalimantan Selatan","id-ks"},
{"Kalimantan Tengah","id-kt"},
{"Lampung","id-la"},
{"Maluku","id-ma"},
{"Maluku Utara","id-mu"},
{"Nusa Tenggara Barat","id-nb"},
{"Nusa Tenggara Timur","id-nt"},
{"Papua","id-pa"},
{"Papua Barat","id-pb"},
{"Riau","id-ri"},
{"Sulawesi Utara","id-sa"},
{"Sumatera Barat","id-sb"},
{"Sulawesi Tenggara","id-sg"},
{"Sulawesi Selatan","id-sn"},
{"Sulawesi Barat","id-sr"},
{"Sumatera Selatan","id-ss"},
{"Sulawesi Tengah","id-st"},
{"Sumatera Utara","id-su"},
{"Yogyakarta","id-yo"},
{"Clare","ie-ce"},
{"Cavan","ie-cn"},
{"Cork","ie-co"},
{"Carlow","ie-cw"},
{"Dublin","ie-d"},
{"Donegal","ie-dl"},
{"Galway","ie-g"},
{"Kildare","ie-ke"},
{"Kilkenny","ie-kk"},
{"Kerry","ie-ky"},
{"Longford","ie-ld"},
{"Louth","ie-lh"},
{"Limerick","ie-lk"},
{"Leitrim","ie-lm"},
{"Laois","ie-ls"},
{"Meath","ie-mh"},
{"Monaghan","ie-mn"},
{"Mayo","ie-mo"},
{"Offaly","ie-oy"},
{"Roscommon","ie-rn"},
{"Sligo","ie-so"},
{"Tipperary","ie-ta"},
{"Waterford","ie-wd"},
{"Westmeath","ie-wh"},
{"Wicklow","ie-ww"},
{"Wexford","ie-wx"},
{"HaDarom","il-d"},
{"Hefa","il-ha"},
{"Yerushalayim","il-jm"},
{"HaMerkaz","il-m"},
{"Tel-Aviv","il-ta"},
{"HaTsafon","il-z"},
{"Isle of Man","im"},
{"Andaman and Nicobar Islands","in-an"},
{"Andhra Pradesh","in-ap"},
{"Arunachal Pradesh","in-ar"},
{"Assam","in-as"},
{"Bihar","in-br"},
{"Chhattisgarh","in-ct"},
{"Daman and Diu","in-dd"},
{"Delhi","in-dl"},
{"Dadra and Nagar Haveli","in-dn"},
{"Goa","in-ga"},
{"Gujarat","in-gj"},
{"Himachal Pradesh","in-hp"},
{"Haryana","in-hr"},
{"Chandigarh","in-ch"},
{"Jharkhand","in-jh"},
{"Jammu and Kashmir","in-jk"},
{"Karnataka","in-ka"},
{"Kerala","in-kl"},
{"Lakshadweep","in-ld"},
{"Maharashtra","in-mh"},
{"Meghalaya","in-ml"},
{"Manipur","in-mn"},
{"Madhya Pradesh","in-mp"},
{"Mizoram","in-mz"},
{"Nagaland","in-nl"},
{"Odisha","in-or"},
{"Punjab","in-pb"},
{"Puducherry","in-py"},
{"Rajasthan","in-rj"},
{"Sikkim","in-sk"},
{"Telangana","in-tg"},
{"Tamil Nadu","in-tn"},
{"Tripura","in-tr"},
{"Uttar Pradesh","in-up"},
{"Uttarakhand","in-ut"},
{"West Bengal","in-wb"},
{"British Indian Ocean Territory","io"},
{"Al Anbar","iq-an"},
{"Arbil","iq-ar"},
{"Al Basrah","iq-ba"},
{"Babil","iq-bb"},
{"Baghdad","iq-bg"},
{"Dahuk","iq-da"},
{"Diyala","iq-di"},
{"Dhi Qar","iq-dq"},
{"Karbala'","iq-ka"},
{"Kirkuk","iq-ki"},
{"Maysan","iq-ma"},
{"Al Muthanna","iq-mu"},
{"An Najaf","iq-na"},
{"Ninawa","iq-ni"},
{"Al Qadisiyah","iq-qa"},
{"Salah ad Din","iq-sd"},
{"As Sulaymaniyah","iq-su"},
{"Wasit","iq-wa"},
{"Azarbayjan-e Sharqi","ir-01"},
{"Azarbayjan-e Gharbi","ir-02"},
{"Ardabil","ir-03"},
{"Esfahan","ir-04"},
{"Ilam","ir-05"},
{"Bushehr","ir-06"},
{"Tehran","ir-07"},
{"Chahar Mahal va Bakhtiari","ir-08"},
{"Khuzestan","ir-10"},
{"Zanjan","ir-11"},
{"Semnan","ir-12"},
{"Sistan va Baluchestan","ir-13"},
{"Fars","ir-14"},
{"Kerman","ir-15"},
{"Kordestan","ir-16"},
{"Kermanshah","ir-17"},
{"Kohgiluyeh va Bowyer Ahmad","ir-18"},
{"Gilan","ir-19"},
{"Lorestan","ir-20"},
{"Mazandaran","ir-21"},
{"Markazi","ir-22"},
{"Hormozgan","ir-23"},
{"Hamadan","ir-24"},
{"Yazd","ir-25"},
{"Qom","ir-26"},
{"Golestan","ir-27"},
{"Qazvin","ir-28"},
{"Khorasan-e Jonubi","ir-29"},
{"Khorasan-e Razavi","ir-30"},
{"Khorasan-e Shomali","ir-31"},
{"Alborz","ir-32"},
{"Hofudborgarsvaedi utan Reykjavikur","is-1"},
{"Sudurnes","is-2"},
{"Vesturland","is-3"},
{"Vestfirdir","is-4"},
{"Nordurland vestra","is-5"},
{"Nordurland eystra","is-6"},
{"Austurland","is-7"},
{"Sudurland","is-8"},
{"Piemonte","it-21"},
{"Valle d'Aosta","it-23"},
{"Lombardia","it-25"},
{"Trentino-Alto Adige","it-32"},
{"Veneto","it-34"},
{"Friuli-Venezia Giulia","it-36"},
{"Liguria","it-42"},
{"Emilia-Romagna","it-45"},
{"Toscana","it-52"},
{"Umbria","it-55"},
{"Marche","it-57"},
{"Lazio","it-62"},
{"Abruzzo","it-65"},
{"Molise","it-67"},
{"Campania","it-72"},
{"Puglia","it-75"},
{"Basilicata","it-77"},
{"Calabria","it-78"},
{"Sicilia","it-82"},
{"Sardegna","it-88"},
{"Jersey","je"},
{"Kingston","jm-01"},
{"Saint Thomas","jm-03"},
{"Portland","jm-04"},
{"Saint Ann","jm-06"},
{"Trelawny","jm-07"},
{"Hanover","jm-09"},
{"Westmoreland","jm-10"},
{"Saint Elizabeth","jm-11"},
{"Manchester","jm-12"},
{"Clarendon","jm-13"},
{"Saint Catherine","jm-14"},
{"Al 'Asimah","jo-am"},
{"Al 'Aqabah","jo-aq"},
{"At Tafilah","jo-at"},
{"Az Zarqa'","jo-az"},
{"Al Balqa'","jo-ba"},
{"Irbid","jo-ir"},
{"Al Karak","jo-ka"},
{"Al Mafraq","jo-ma"},
{"Madaba","jo-md"},
{"Ma'an","jo-mn"},
{"Hokkaido","jp-01"},
{"Aomori","jp-02"},
{"Iwate","jp-03"},
{"Miyagi","jp-04"},
{"Akita","jp-05"},
{"Yamagata","jp-06"},
{"Fukushima","jp-07"},
{"Ibaraki","jp-08"},
{"Tochigi","jp-09"},
{"Gunma","jp-10"},
{"Saitama","jp-11"},
{"Chiba","jp-12"},
{"Tokyo","jp-13"},
{"Kanagawa","jp-14"},
{"Niigata","jp-15"},
{"Toyama","jp-16"},
{"Ishikawa","jp-17"},
{"Fukui","jp-18"},
{"Yamanashi","jp-19"},
{"Nagano","jp-20"},
{"Gifu","jp-21"},
{"Shizuoka","jp-22"},
{"Aichi","jp-23"},
{"Mie","jp-24"},
{"Shiga","jp-25"},
{"Kyoto","jp-26"},
{"Osaka","jp-27"},
{"Hyogo","jp-28"},
{"Nara","jp-29"},
{"Wakayama","jp-30"},
{"Tottori","jp-31"},
{"Shimane","jp-32"},
{"Okayama","jp-33"},
{"Hiroshima","jp-34"},
{"Yamaguchi","jp-35"},
{"Tokushima","jp-36"},
{"Kagawa","jp-37"},
{"Ehime","jp-38"},
{"Kochi","jp-39"},
{"Fukuoka","jp-40"},
{"Saga","jp-41"},
{"Nagasaki","jp-42"},
{"Kumamoto","jp-43"},
{"Oita","jp-44"},
{"Miyazaki","jp-45"},
{"Kagoshima","jp-46"},
{"Okinawa","jp-47"},
{"Nairobi Area","ke-110"},
{"Coast","ke-300"},
{"North-Eastern","ke-500"},
{"Nyanza","ke-600"},
{"Rift Valley","ke-700"},
{"Batken","kg-b"},
{"Chu","kg-c"},
{"Bishkek","kg-gb"},
{"Jalal-Abad","kg-j"},
{"Naryn","kg-n"},
{"Osh","kg-o"},
{"Talas","kg-t"},
{"Ysyk-Kol","kg-y"},
{"Banteay Mean Chey","kh-1"},
{"Kracheh","kh-10"},
{"Mondol Kiri","kh-11"},
{"Phnom Penh","kh-12"},
{"Preah Vihear","kh-13"},
{"Prey Veaeng","kh-14"},
{"Pousaat","kh-15"},
{"Rotanak Kiri","kh-16"},
{"Siem Reab","kh-17"},
{"Krong Preah Sihanouk","kh-18"},
{"Stueng Traeng","kh-19"},
{"Baat Dambang","kh-2"},
{"Svaay Rieng","kh-20"},
{"Taakaev","kh-21"},
{"Otdar Mean Chey","kh-22"},
{"Krong Kaeb","kh-23"},
{"Krong Pailin","kh-24"},
{"Kampong Chaam","kh-3"},
{"Kampong Chhnang","kh-4"},
{"Kampong Spueu","kh-5"},
{"Kampong Thum","kh-6"},
{"Kampot","kh-7"},
{"Kandaal","kh-8"},
{"Kaoh Kong","kh-9"},
{"Gilbert Islands","ki-g"},
{"Line Islands","ki-l"},
{"Anjouan","km-a"},
{"Grande Comore","km-g"},
{"Moheli","km-m"},
{"Saint George Basseterre","kn-03"},
{"Saint Paul Charlestown","kn-09"},
{"P'yongyang","kp-01"},
{"P'yongan-namdo","kp-02"},
{"P'yongan-bukto","kp-03"},
{"Chagang-do","kp-04"},
{"Hwanghae-namdo","kp-05"},
{"Hwanghae-bukto","kp-06"},
{"Kangwon-do","kp-07"},
{"Hamgyong-namdo","kp-08"},
{"Hamgyong-bukto","kp-09"},
{"Yanggang-do","kp-10"},
{"Nason (Najin-Sonbong)","kp-13"},
{"Seoul","kr-11"},
{"Busan","kr-26"},
{"Daegu","kr-27"},
{"Incheon","kr-28"},
{"Gwangju","kr-29"},
{"Daejeon","kr-30"},
{"Ulsan","kr-31"},
{"Gyeonggi","kr-41"},
{"Gangwon","kr-42"},
{"Chungbuk","kr-43"},
{"Chungnam","kr-44"},
{"Jeonbuk","kr-45"},
{"Jeonnam","kr-46"},
{"Gyeongbuk","kr-47"},
{"Gyeongnam","kr-48"},
{"Jeju","kr-49"},
{"Al Ahmadi","kw-ah"},
{"Al Farwaniyah","kw-fa"},
{"Hawalli","kw-ha"},
{"Al Jahra","kw-ja"},
{"Mubarak al Kabir","kw-mu"},
{"Cayman Islands","ky"},
{"Aqmola oblysy","kz-akm"},
{"Aqtobe oblysy","kz-akt"},
{"Almaty","kz-ala"},
{"Almaty oblysy","kz-alm"},
{"Astana","kz-ast"},
{"Atyrau oblysy","kz-aty"},
{"Qaraghandy oblysy","kz-kar"},
{"Qostanay oblysy","kz-kus"},
{"Qyzylorda oblysy","kz-kzy"},
{"Mangghystau oblysy","kz-man"},
{"Pavlodar oblysy","kz-pav"},
{"Soltustik Qazaqstan oblysy","kz-sev"},
{"Shyghys Qazaqstan oblysy","kz-vos"},
{"Ongtustik Qazaqstan oblysy","kz-yuz"},
{"Batys Qazaqstan oblysy","kz-zap"},
{"Zhambyl oblysy","kz-zha"},
{"Attapu","la-at"},
{"Bokeo","la-bk"},
{"Bolikhamxai","la-bl"},
{"Houaphan","la-ho"},
{"Champasak","la-ch"},
{"Khammouan","la-kh"},
{"Louang Namtha","la-lm"},
{"Louangphabang","la-lp"},
{"Oudomxai","la-ou"},
{"Phongsali","la-ph"},
{"Salavan","la-sl"},
{"Savannakhet","la-sv"},
{"Vientiane","la-vi"},
{"Xaignabouli","la-xa"},
{"Xekong","la-xe"},
{"Xiangkhouang","la-xi"},
{"Aakkar","lb-ak"},
{"Liban-Nord","lb-as"},
{"Beyrouth","lb-ba"},
{"Baalbek-Hermel","lb-bh"},
{"Beqaa","lb-bi"},
{"Liban-Sud","lb-ja"},
{"Mont-Liban","lb-jl"},
{"Nabatiye","lb-na"},
{"Anse la Raye","lc-01"},
{"Castries","lc-02"},
{"Dennery","lc-05"},
{"Gros Islet","lc-06"},
{"Laborie","lc-07"},
{"Micoud","lc-08"},
{"Soufriere","lc-10"},
{"Vieux Fort","lc-11"},
{"Balzers","li-01"},
{"Eschen","li-02"},
{"Gamprin","li-03"},
{"Mauren","li-04"},
{"Planken","li-05"},
{"Ruggell","li-06"},
{"Schaan","li-07"},
{"Schellenberg","li-08"},
{"Triesen","li-09"},
{"Triesenberg","li-10"},
{"Vaduz","li-11"},
{"Western Province","lk-1"},
{"Central Province","lk-2"},
{"Southern Province","lk-3"},
{"Northern Province","lk-4"},
{"Eastern Province","lk-5"},
{"North Western Province","lk-6"},
{"North Central Province","lk-7"},
{"Uva Province","lk-8"},
{"Sabaragamuwa Province","lk-9"},
{"Bong","lr-bg"},
{"Bomi","lr-bm"},
{"Grand Cape Mount","lr-cm"},
{"Grand Bassa","lr-gb"},
{"Grand Gedeh","lr-gg"},
{"Grand Kru","lr-gk"},
{"Gbarpolu","lr-gp"},
{"Lofa","lr-lo"},
{"Margibi","lr-mg"},
{"Montserrado","lr-mo"},
{"Maryland","lr-my"},
{"Nimba","lr-ni"},
{"River Gee","lr-rg"},
{"River Cess","lr-ri"},
{"Sinoe","lr-si"},
{"Maseru","ls-a"},
{"Butha-Buthe","ls-b"},
{"Leribe","ls-c"},
{"Berea","ls-d"},
{"Mafeteng","ls-e"},
{"Mohale's Hoek","ls-f"},
{"Quthing","ls-g"},
{"Qacha's Nek","ls-h"},
{"Mokhotlong","ls-j"},
{"Thaba-Tseka","ls-k"},
{"Alytaus Apskritis","lt-al"},
{"Klaipedos Apskritis","lt-kl"},
{"Kauno Apskritis","lt-ku"},
{"Marijampoles Apskritis","lt-mr"},
{"Panevezio Apskritis","lt-pn"},
{"Siauliu Apskritis","lt-sa"},
{"Taurages Apskritis","lt-ta"},
{"Telsiu Apskritis","lt-te"},
{"Utenos Apskritis","lt-ut"},
{"Vilniaus Apskritis","lt-vl"},
{"Diekirch","lu-d"},
{"Grevenmacher","lu-g"},
{"Aglonas","lv-001"},
{"Aizkraukles","lv-002"},
{"Aizputes","lv-003"},
{"Alojas","lv-005"},
{"Aluksnes","lv-007"},
{"Adazu","lv-011"},
{"Babites","lv-012"},
{"Baltinavas","lv-014"},
{"Balvu","lv-015"},
{"Bauskas","lv-016"},
{"Beverinas","lv-017"},
{"Brocenu","lv-018"},
{"Carnikavas","lv-020"},
{"Cesvaines","lv-021"},
{"Cesu","lv-022"},
{"Ciblas","lv-023"},
{"Daugavpils","lv-025"},
{"Dobeles","lv-026"},
{"Dundagas","lv-027"},
{"Gulbenes","lv-033"},
{"Iecavas","lv-034"},
{"Incukalna","lv-037"},
{"Jaunjelgavas","lv-038"},
{"Jaunpiebalgas","lv-039"},
{"Jaunpils","lv-040"},
{"Jelgavas","lv-041"},
{"Jekabpils","lv-042"},
{"Kokneses","lv-046"},
{"Kraslavas","lv-047"},
{"Kuldigas","lv-050"},
{"Kekavas","lv-052"},
{"Lubanas","lv-057"},
{"Ludzas","lv-058"},
{"Madonas","lv-059"},
{"Malpils","lv-061"},
{"Ogres","lv-067"},
{"Olaines","lv-068"},
{"Ozolnieku","lv-069"},
{"Preilu","lv-073"},
{"Rezeknes","lv-077"},
{"Rojas","lv-079"},
{"Ropazu","lv-080"},
{"Rugaju","lv-082"},
{"Rundales","lv-083"},
{"Salacgrivas","lv-086"},
{"Saldus","lv-088"},
{"Sejas","lv-090"},
{"Siguldas","lv-091"},
{"Skrundas","lv-093"},
{"Stopinu","lv-095"},
{"Strencu","lv-096"},
{"Talsu","lv-097"},
{"Tukuma","lv-099"},
{"Vainodes","lv-100"},
{"Valkas","lv-101"},
{"Varkavas","lv-103"},
{"Vecumnieku","lv-105"},
{"Ventspils","lv-106"},
{"Jelgava","lv-jel"},
{"Jurmala","lv-jur"},
{"Liepajas","lv-le"},
{"Limbazu","lv-lm"},
{"Liepaja","lv-lpx"},
{"Rigas","lv-ri"},
{"Riga","lv-rix"},
{"Valmieras","lv-vm"},
{"Banghazi","ly-ba"},
{"Al Butnan","ly-bu"},
{"Darnah","ly-dr"},
{"Ghat","ly-gt"},
{"Al Jabal al Akhdar","ly-ja"},
{"Al Jabal al Gharbi","ly-jg"},
{"Al Jafarah","ly-ji"},
{"Al Jufrah","ly-ju"},
{"Al Kufrah","ly-kf"},
{"Al Marqab","ly-mb"},
{"Misratah","ly-mi"},
{"Al Marj","ly-mj"},
{"Murzuq","ly-mq"},
{"Nalut","ly-nl"},
{"An Nuqat al Khams","ly-nq"},
{"Sabha","ly-sb"},
{"Surt","ly-sr"},
{"Tarabulus","ly-tb"},
{"Al Wahat","ly-wa"},
{"Wadi al Hayat","ly-wd"},
{"Wadi ash Shati'","ly-ws"},
{"Az Zawiyah","ly-za"},
{"Tanger-Tetouan","ma-01"},
{"Gharb-Chrarda-Beni Hssen","ma-02"},
{"Taza-Al Hoceima-Taounate","ma-03"},
{"L'Oriental","ma-04"},
{"Fes-Boulemane","ma-05"},
{"Meknes-Tafilalet","ma-06"},
{"Rabat-Sale-Zemmour-Zaer","ma-07"},
{"Grand Casablanca","ma-08"},
{"Chaouia-Ouardigha","ma-09"},
{"Doukhala-Abda","ma-10"},
{"Marrakech-Tensift-Al Haouz","ma-11"},
{"Tadla-Azilal","ma-12"},
{"Souss-Massa-Draa","ma-13"},
{"Western Sahara","ma-14"},
{"Oued Ed-Dahab-Lagouira","ma-16"},
{"Monaco","mc-mo"},
{"Anenii Noi","md-an"},
{"Balti","md-ba"},
{"Briceni","md-br"},
{"Basarabeasca","md-bs"},
{"Cahul","md-ca"},
{"Calarasi","md-cl"},
{"Cimislia","md-cm"},
{"Criuleni","md-cr"},
{"Causeni","md-cs"},
{"Cantemir","md-ct"},
{"Chisinau","md-cu"},
{"Donduseni","md-do"},
{"Drochia","md-dr"},
{"Dubasari","md-du"},
{"Edinet","md-ed"},
{"Falesti","md-fa"},
{"Floresti","md-fl"},
{"Gagauzia, Unitatea teritoriala autonoma","md-ga"},
{"Glodeni","md-gl"},
{"Hincesti","md-hi"},
{"Ialoveni","md-ia"},
{"Leova","md-le"},
{"Nisporeni","md-ni"},
{"Ocnita","md-oc"},
{"Orhei","md-or"},
{"Rezina","md-re"},
{"Riscani","md-ri"},
{"Soldanesti","md-sd"},
{"Singerei","md-si"},
{"Stinga Nistrului, unitatea teritoriala din","md-sn"},
{"Soroca","md-so"},
{"Straseni","md-st"},
{"Stefan Voda","md-sv"},
{"Taraclia","md-ta"},
{"Telenesti","md-te"},
{"Bender","md-ti"},
{"Ungheni","md-un"},
{"Bar","me-02"},
{"Budva","me-05"},
{"Cetinje","me-06"},
{"Danilovgrad","me-07"},
{"Herceg-Novi","me-08"},
{"Kolasin","me-09"},
{"Kotor","me-10"},
{"Mojkovac","me-11"},
{"Niksic","me-12"},
{"Podgorica","me-16"},
{"Tivat","me-19"},
{"Ulcinj","me-20"},
{"Zabljak","me-21"},
{"Toamasina","mg-a"},
{"Antsiranana","mg-d"},
{"Fianarantsoa","mg-f"},
{"Mahajanga","mg-m"},
{"Antananarivo","mg-t"},
{"Toliara","mg-u"},
{"Ailuk Atoll","mh-alk"},
{"Ailinglaplap Atoll","mh-all"},
{"Arno Atoll","mh-arn"},
{"Aur Atoll","mh-aur"},
{"Ebon Atoll","mh-ebo"},
{"Enewetak Atoll","mh-eni"},
{"Jabat Island","mh-jab"},
{"Jaluit Atoll","mh-jal"},
{"Kili Island","mh-kil"},
{"Kwajalein Atoll","mh-kwa"},
{"Lae Atoll","mh-lae"},
{"Lib Island","mh-lib"},
{"Likiep Atoll","mh-lik"},
{"Majuro Atoll","mh-maj"},
{"Maloelap Atoll","mh-mal"},
{"Mejit Island","mh-mej"},
{"Mili Atoll","mh-mil"},
{"Namdrik Atoll","mh-nmk"},
{"Namu Atoll","mh-nmu"},
{"Rongelap Atoll","mh-ron"},
{"Ujae Atoll","mh-uja"},
{"Utrik Atoll","mh-uti"},
{"Wotho Atoll","mh-wth"},
{"Wotje Atoll","mh-wtj"},
{"Aracinovo","mk-02"},
{"Berovo","mk-03"},
{"Bitola","mk-04"},
{"Bogdanci","mk-05"},
{"Bogovinje","mk-06"},
{"Bosilovo","mk-07"},
{"Brvenica","mk-08"},
{"Valandovo","mk-10"},
{"Vasilevo","mk-11"},
{"Vevcani","mk-12"},
{"Veles","mk-13"},
{"Vinica","mk-14"},
{"Vrapciste","mk-16"},
{"Gevgelija","mk-18"},
{"Gostivar","mk-19"},
{"Gradsko","mk-20"},
{"Debar","mk-21"},
{"Debarca","mk-22"},
{"Delcevo","mk-23"},
{"Demir Kapija","mk-24"},
{"Demir Hisar","mk-25"},
{"Dojran","mk-26"},
{"Dolneni","mk-27"},
{"Zelino","mk-30"},
{"Zelenikovo","mk-32"},
{"Zrnovci","mk-33"},
{"Ilinden","mk-34"},
{"Jegunovce","mk-35"},
{"Kavadarci","mk-36"},
{"Karbinci","mk-37"},
{"Kicevo","mk-40"},
{"Konce","mk-41"},
{"Kocani","mk-42"},
{"Kratovo","mk-43"},
{"Kriva Palanka","mk-44"},
{"Krivogastani","mk-45"},
{"Krusevo","mk-46"},
{"Kumanovo","mk-47"},
{"Lipkovo","mk-48"},
{"Lozovo","mk-49"},
{"Mavrovo i Rostusa","mk-50"},
{"Makedonska Kamenica","mk-51"},
{"Makedonski Brod","mk-52"},
{"Mogila","mk-53"},
{"Negotino","mk-54"},
{"Novaci","mk-55"},
{"Novo Selo","mk-56"},
{"Ohrid","mk-58"},
{"Petrovec","mk-59"},
{"Pehcevo","mk-60"},
{"Plasnica","mk-61"},
{"Prilep","mk-62"},
{"Probistip","mk-63"},
{"Radovis","mk-64"},
{"Rankovce","mk-65"},
{"Resen","mk-66"},
{"Rosoman","mk-67"},
{"Sveti Nikole","mk-69"},
{"Sopiste","mk-70"},
{"Staro Nagoricane","mk-71"},
{"Struga","mk-72"},
{"Strumica","mk-73"},
{"Studenicani","mk-74"},
{"Tearce","mk-75"},
{"Tetovo","mk-76"},
{"Centar Zupa","mk-78"},
{"Caska","mk-80"},
{"Cesinovo-Oblesevo","mk-81"},
{"Cucer Sandevo","mk-82"},
{"Stip","mk-83"},
{"Skopje","mk-85"},
{"Kayes","ml-1"},
{"Koulikoro","ml-2"},
{"Sikasso","ml-3"},
{"Segou","ml-4"},
{"Mopti","ml-5"},
{"Tombouctou","ml-6"},
{"Gao","ml-7"},
{"Kidal","ml-8"},
{"Bamako","ml-bko"},
{"Sagaing","mm-01"},
{"Bago","mm-02"},
{"Magway","mm-03"},
{"Mandalay","mm-04"},
{"Taninthayi","mm-05"},
{"Yangon","mm-06"},
{"Ayeyawady","mm-07"},
{"Kachin","mm-11"},
{"Kayah","mm-12"},
{"Kayin","mm-13"},
{"Chin","mm-14"},
{"Mon","mm-15"},
{"Rakhine","mm-16"},
{"Shan","mm-17"},
{"Nay Pyi Taw","mm-18"},
{"Orhon","mn-035"},
{"Darhan uul","mn-037"},
{"Hentiy","mn-039"},
{"Hovsgol","mn-041"},
{"Hovd","mn-043"},
{"Uvs","mn-046"},
{"Tov","mn-047"},
{"Selenge","mn-049"},
{"Suhbaatar","mn-051"},
{"Omnogovi","mn-053"},
{"Ovorhangay","mn-055"},
{"Dzavhan","mn-057"},
{"Dundgovi","mn-059"},
{"Dornod","mn-061"},
{"Dornogovi","mn-063"},
{"Govi-Sumber","mn-064"},
{"Govi-Altay","mn-065"},
{"Bulgan","mn-067"},
{"Bayanhongor","mn-069"},
{"Bayan-Olgiy","mn-071"},
{"Arhangay","mn-073"},
{"Ulaanbaatar","mn-1"},
{"Northern Mariana Islands","mp"},
{"Martinique","mq"},
{"Hodh Ech Chargui","mr-01"},
{"Hodh El Gharbi","mr-02"},
{"Assaba","mr-03"},
{"Gorgol","mr-04"},
{"Brakna","mr-05"},
{"Trarza","mr-06"},
{"Dakhlet Nouadhibou","mr-08"},
{"Tagant","mr-09"},
{"Guidimaka","mr-10"},
{"Tiris Zemmour","mr-11"},
{"Inchiri","mr-12"},
{"Nouakchott","mr-nkc"},
{"Malta","mt"},
{"Black River","mu-bl"},
{"Flacq","mu-fl"},
{"Grand Port","mu-gp"},
{"Moka","mu-mo"},
{"Pamplemousses","mu-pa"},
{"Port Louis","mu-pl"},
{"Plaines Wilhems","mu-pw"},
{"Riviere du Rempart","mu-rr"},
{"Savanne","mu-sa"},
{"Seenu","mv-01"},
{"Alifu","mv-02"},
{"Laamu","mv-05"},
{"Haa Alifu","mv-07"},
{"Thaa","mv-08"},
{"Meemu","mv-12"},
{"Raa","mv-13"},
{"Dhaalu","mv-17"},
{"Baa","mv-20"},
{"Haa Dhaalu","mv-23"},
{"Shaviyani","mv-24"},
{"Noonu","mv-25"},
{"Kaafu","mv-26"},
{"Gaafu Dhaalu","mv-28"},
{"Maale","mv-mle"},
{"Balaka","mw-ba"},
{"Blantyre","mw-bl"},
{"Chikwawa","mw-ck"},
{"Chiradzulu","mw-cr"},
{"Chitipa","mw-ct"},
{"Dedza","mw-de"},
{"Dowa","mw-do"},
{"Karonga","mw-kr"},
{"Kasungu","mw-ks"},
{"Lilongwe","mw-li"},
{"Likoma","mw-lk"},
{"Mchinji","mw-mc"},
{"Mangochi","mw-mg"},
{"Machinga","mw-mh"},
{"Mulanje","mw-mu"},
{"Mwanza","mw-mw"},
{"Mzimba","mw-mz"},
{"Nkhata Bay","mw-nb"},
{"Neno","mw-ne"},
{"Ntchisi","mw-ni"},
{"Nkhotakota","mw-nk"},
{"Nsanje","mw-ns"},
{"Ntcheu","mw-nu"},
{"Phalombe","mw-ph"},
{"Rumphi","mw-ru"},
{"Salima","mw-sa"},
{"Thyolo","mw-th"},
{"Zomba","mw-zo"},
{"Aguascalientes","mx-agu"},
{"Baja California","mx-bcn"},
{"Baja California Sur","mx-bcs"},
{"Campeche","mx-cam"},
{"Coahuila","mx-coa"},
{"Colima","mx-col"},
{"Durango","mx-dur"},
{"Guerrero","mx-gro"},
{"Guanajuato","mx-gua"},
{"Hidalgo","mx-hid"},
{"Chihuahua","mx-chh"},
{"Chiapas","mx-chp"},
{"Jalisco","mx-jal"},
{"Mexico","mx-mex"},
{"Michoacan","mx-mic"},
{"Morelos","mx-mor"},
{"Nayarit","mx-nay"},
{"Nuevo Leon","mx-nle"},
{"Oaxaca","mx-oax"},
{"Puebla","mx-pue"},
{"Queretaro","mx-que"},
{"Quintana Roo","mx-roo"},
{"Sinaloa","mx-sin"},
{"San Luis Potosi","mx-slp"},
{"Sonora","mx-son"},
{"Tabasco","mx-tab"},
{"Tamaulipas","mx-tam"},
{"Tlaxcala","mx-tla"},
{"Veracruz","mx-ver"},
{"Yucatan","mx-yuc"},
{"Zacatecas","mx-zac"},
{"Johor","my-01"},
{"Kedah","my-02"},
{"Kelantan","my-03"},
{"Melaka","my-04"},
{"Negeri Sembilan","my-05"},
{"Pahang","my-06"},
{"Pulau Pinang","my-07"},
{"Perak","my-08"},
{"Perlis","my-09"},
{"Selangor","my-10"},
{"Terengganu","my-11"},
{"Sabah","my-12"},
{"Sarawak","my-13"},
{"Wilayah Persekutuan Kuala Lumpur","my-14"},
{"Wilayah Persekutuan Labuan","my-15"},
{"Wilayah Persekutuan Putrajaya","my-16"},
{"Niassa","mz-a"},
{"Manica","mz-b"},
{"Gaza","mz-g"},
{"Inhambane","mz-i"},
{"Maputo","mz-l"},
{"Nampula","mz-n"},
{"Cabo Delgado","mz-p"},
{"Zambezia","mz-q"},
{"Sofala","mz-s"},
{"Tete","mz-t"},
{"Zambezi","na-ca"},
{"Erongo","na-er"},
{"Hardap","na-ha"},
{"Karas","na-ka"},
{"Khomas","na-kh"},
{"Kunene","na-ku"},
{"Otjozondjupa","na-od"},
{"Omaheke","na-oh"},
{"Oshana","na-on"},
{"Omusati","na-os"},
{"Oshikoto","na-ot"},
{"Ohangwena","na-ow"},
{"Agadez","ne-1"},
{"Diffa","ne-2"},
{"Dosso","ne-3"},
{"Maradi","ne-4"},
{"Tahoua","ne-5"},
{"Tillaberi","ne-6"},
{"Zinder","ne-7"},
{"Niamey","ne-8"},
{"Norfolk Island","nf"},
{"Abia","ng-ab"},
{"Adamawa","ng-ad"},
{"Akwa Ibom","ng-ak"},
{"Anambra","ng-an"},
{"Bauchi","ng-ba"},
{"Benue","ng-be"},
{"Borno","ng-bo"},
{"Bayelsa","ng-by"},
{"Cross River","ng-cr"},
{"Delta","ng-de"},
{"Ebonyi","ng-eb"},
{"Edo","ng-ed"},
{"Ekiti","ng-ek"},
{"Enugu","ng-en"},
{"Abuja Federal Capital Territory","ng-fc"},
{"Gombe","ng-go"},
{"Imo","ng-im"},
{"Jigawa","ng-ji"},
{"Kaduna","ng-kd"},
{"Kebbi","ng-ke"},
{"Kano","ng-kn"},
{"Kogi","ng-ko"},
{"Katsina","ng-kt"},
{"Kwara","ng-kw"},
{"Lagos","ng-la"},
{"Nasarawa","ng-na"},
{"Niger","ng-ni"},
{"Ogun","ng-og"},
{"Ondo","ng-on"},
{"Osun","ng-os"},
{"Oyo","ng-oy"},
{"Rivers","ng-ri"},
{"Sokoto","ng-so"},
{"Taraba","ng-ta"},
{"Yobe","ng-yo"},
{"Zamfara","ng-za"},
{"Atlantico Norte","ni-an"},
{"Atlantico Sur","ni-as"},
{"Boaco","ni-bo"},
{"Carazo","ni-ca"},
{"Chinandega","ni-ci"},
{"Chontales","ni-co"},
{"Esteli","ni-es"},
{"Granada","ni-gr"},
{"Jinotega","ni-ji"},
{"Leon","ni-le"},
{"Madriz","ni-md"},
{"Managua","ni-mn"},
{"Masaya","ni-ms"},
{"Matagalpa","ni-mt"},
{"Nueva Segovia","ni-ns"},
{"Rivas","ni-ri"},
{"Rio San Juan","ni-sj"},
{"Drenthe","nl-dr"},
{"Flevoland","nl-fl"},
{"Fryslan","nl-fr"},
{"Gelderland","nl-ge"},
{"Groningen","nl-gr"},
{"Noord-Brabant","nl-nb"},
{"Noord-Holland","nl-nh"},
{"Overijssel","nl-ov"},
{"Utrecht","nl-ut"},
{"Zeeland","nl-ze"},
{"Zuid-Holland","nl-zh"},
{"Ostfold","no-01"},
{"Akershus","no-02"},
{"Oslo","no-03"},
{"Hedmark","no-04"},
{"Oppland","no-05"},
{"Buskerud","no-06"},
{"Vestfold","no-07"},
{"Telemark","no-08"},
{"Aust-Agder","no-09"},
{"Vest-Agder","no-10"},
{"Rogaland","no-11"},
{"Hordaland","no-12"},
{"Sogn og Fjordane","no-14"},
{"More og Romsdal","no-15"},
{"Sor-Trondelag","no-16"},
{"Nord-Trondelag","no-17"},
{"Nordland","no-18"},
{"Troms","no-19"},
{"Finnmark","no-20"},
{"Bagmati","np-ba"},
{"Bheri","np-bh"},
{"Dhawalagiri","np-dh"},
{"Gandaki","np-ga"},
{"Janakpur","np-ja"},
{"Karnali","np-ka"},
{"Kosi","np-ko"},
{"Lumbini","np-lu"},
{"Mahakali","np-ma"},
{"Mechi","np-me"},
{"Narayani","np-na"},
{"Rapti","np-ra"},
{"Sagarmatha","np-sa"},
{"Seti","np-se"},
{"Yaren","nr-14"},
{"Niue","nu"},
{"Auckland","nz-auk"},
{"Bay of Plenty","nz-bop"},
{"Canterbury","nz-can"},
{"Chatham Islands","nz-cit"},
{"Gisborne","nz-gis"},
{"Hawke's Bay","nz-hkb"},
{"Marlborough","nz-mbh"},
{"Manawatu-Wanganui","nz-mwt"},
{"Nelson","nz-nsn"},
{"Northland","nz-ntl"},
{"Otago","nz-ota"},
{"Southland","nz-stl"},
{"Tasman","nz-tas"},
{"Taranaki","nz-tki"},
{"Wellington","nz-wgn"},
{"Waikato","nz-wko"},
{"West Coast","nz-wtc"},
{"Shamal al Batinah","om-bj"},
{"Janub al Batinah","om-bs"},
{"Al Buraymi","om-bu"},
{"Ad Dakhiliyah","om-da"},
{"Masqat","om-ma"},
{"Musandam","om-mu"},
{"Shamal ash Sharqiyah","om-sj"},
{"Janub ash Sharqiyah","om-ss"},
{"Az Zahirah","om-za"},
{"Zufar","om-zu"},
{"San Blas","pa-0"},
{"Bocas del Toro","pa-1"},
{"Cocle","pa-2"},
{"Chiriqui","pa-4"},
{"Darien","pa-5"},
{"Herrera","pa-6"},
{"Los Santos","pa-7"},
{"Panama","pa-8"},
{"Veraguas","pa-9"},
{"Ancash","pe-anc"},
{"Apurimac","pe-apu"},
{"Arequipa","pe-are"},
{"Ayacucho","pe-aya"},
{"Cajamarca","pe-caj"},
{"Callao","pe-cal"},
{"Cusco","pe-cus"},
{"Huanuco","pe-huc"},
{"Huancavelica","pe-huv"},
{"Ica","pe-ica"},
{"Junin","pe-jun"},
{"La Libertad","pe-lal"},
{"Lambayeque","pe-lam"},
{"Lima","pe-lim"},
{"Loreto","pe-lor"},
{"Madre de Dios","pe-mdd"},
{"Moquegua","pe-moq"},
{"Pasco","pe-pas"},
{"Piura","pe-piu"},
{"Puno","pe-pun"},
{"San Martin","pe-sam"},
{"Tacna","pe-tac"},
{"Tumbes","pe-tum"},
{"Ucayali","pe-uca"},
{"Chimbu","pg-cpk"},
{"East New Britain","pg-ebr"},
{"Eastern Highlands","pg-ehg"},
{"Enga","pg-epw"},
{"East Sepik","pg-esw"},
{"Gulf","pg-gpk"},
{"Milne Bay","pg-mba"},
{"Morobe","pg-mpl"},
{"Madang","pg-mpm"},
{"Manus","pg-mrl"},
{"National Capital District","pg-ncd"},
{"New Ireland","pg-nik"},
{"Bougainville","pg-nsb"},
{"West Sepik","pg-san"},
{"Southern Highlands","pg-shm"},
{"West New Britain","pg-wbk"},
{"Western Highlands","pg-whm"},
{"National Capital Region","ph-00"},
{"Abra","ph-abr"},
{"Agusan del Norte","ph-agn"},
{"Agusan del Sur","ph-ags"},
{"Aklan","ph-akl"},
{"Albay","ph-alb"},
{"Antique","ph-ant"},
{"Apayao","ph-apa"},
{"Aurora","ph-aur"},
{"Bataan","ph-ban"},
{"Basilan","ph-bas"},
{"Benguet","ph-ben"},
{"Bohol","ph-boh"},
{"Batangas","ph-btg"},
{"Batanes","ph-btn"},
{"Bukidnon","ph-buk"},
{"Bulacan","ph-bul"},
{"Cagayan","ph-cag"},
{"Camiguin","ph-cam"},
{"Camarines Norte","ph-can"},
{"Capiz","ph-cap"},
{"Camarines Sur","ph-cas"},
{"Catanduanes","ph-cat"},
{"Cavite","ph-cav"},
{"Cebu","ph-ceb"},
{"Davao Oriental","ph-dao"},
{"Davao del Sur","ph-das"},
{"Eastern Samar","ph-eas"},
{"Ifugao","ph-ifu"},
{"Iloilo","ph-ili"},
{"Ilocos Norte","ph-iln"},
{"Ilocos Sur","ph-ils"},
{"Isabela","ph-isa"},
{"Kalinga","ph-kal"},
{"Laguna","ph-lag"},
{"Lanao del Norte","ph-lan"},
{"Lanao del Sur","ph-las"},
{"Leyte","ph-ley"},
{"La Union","ph-lun"},
{"Marinduque","ph-mad"},
{"Maguindanao","ph-mag"},
{"Masbate","ph-mas"},
{"Mindoro Occidental","ph-mdc"},
{"Mindoro Oriental","ph-mdr"},
{"Mountain Province","ph-mou"},
{"Misamis Occidental","ph-msc"},
{"Misamis Oriental","ph-msr"},
{"Cotabato","ph-nco"},
{"Negros Occidental","ph-nec"},
{"Negros Oriental","ph-ner"},
{"Northern Samar","ph-nsa"},
{"Nueva Ecija","ph-nue"},
{"Nueva Vizcaya","ph-nuv"},
{"Pampanga","ph-pam"},
{"Pangasinan","ph-pan"},
{"Palawan","ph-plw"},
{"Quezon","ph-que"},
{"Quirino","ph-qui"},
{"Rizal","ph-riz"},
{"Romblon","ph-rom"},
{"South Cotabato","ph-sco"},
{"Siquijor","ph-sig"},
{"Southern Leyte","ph-sle"},
{"Sulu","ph-slu"},
{"Sorsogon","ph-sor"},
{"Sultan Kudarat","ph-suk"},
{"Surigao del Norte","ph-sun"},
{"Surigao del Sur","ph-sur"},
{"Tarlac","ph-tar"},
{"Tawi-Tawi","ph-taw"},
{"Samar (Western Samar)","ph-wsa"},
{"Zamboanga del Norte","ph-zan"},
{"Zamboanga del Sur","ph-zas"},
{"Zambales","ph-zmb"},
{"Balochistan","pk-ba"},
{"Gilgit-Baltistan","pk-gb"},
{"Islamabad","pk-is"},
{"Azad Kashmir","pk-jk"},
{"Khyber Pakhtunkhwa","pk-kp"},
{"Sindh","pk-sd"},
{"Federally Administered Tribal Areas","pk-ta"},
{"Dolnoslaskie","pl-ds"},
{"Kujawsko-Pomorskie","pl-kp"},
{"Lubuskie","pl-lb"},
{"Lodzkie","pl-ld"},
{"Lubelskie","pl-lu"},
{"Malopolskie","pl-ma"},
{"Mazowieckie","pl-mz"},
{"Opolskie","pl-op"},
{"Podlaskie","pl-pd"},
{"Podkarpackie","pl-pk"},
{"Pomorskie","pl-pm"},
{"Swietokrzyskie","pl-sk"},
{"Slaskie","pl-sl"},
{"Warminsko-Mazurskie","pl-wn"},
{"Wielkopolskie","pl-wp"},
{"Zachodniopomorskie","pl-zp"},
{"Saint Pierre and Miquelon","pm"},
{"Aveiro","pt-01"},
{"Beja","pt-02"},
{"Braga","pt-03"},
{"Braganca","pt-04"},
{"Castelo Branco","pt-05"},
{"Coimbra","pt-06"},
{"Evora","pt-07"},
{"Faro","pt-08"},
{"Guarda","pt-09"},
{"Leiria","pt-10"},
{"Lisboa","pt-11"},
{"Portalegre","pt-12"},
{"Porto","pt-13"},
{"Santarem","pt-14"},
{"Setubal","pt-15"},
{"Viana do Castelo","pt-16"},
{"Vila Real","pt-17"},
{"Viseu","pt-18"},
{"Regiao Autonoma dos Acores","pt-20"},
{"Regiao Autonoma da Madeira","pt-30"},
{"Aimeliik","pw-002"},
{"Airai","pw-004"},
{"Angaur","pw-010"},
{"Kayangel","pw-100"},
{"Koror","pw-150"},
{"Melekeok","pw-212"},
{"Ngaraard","pw-214"},
{"Ngarchelong","pw-218"},
{"Ngardmau","pw-222"},
{"Ngatpang","pw-224"},
{"Ngiwal","pw-228"},
{"Peleliu","pw-350"},
{"Concepcion","py-1"},
{"Alto Parana","py-10"},
{"Neembucu","py-12"},
{"Amambay","py-13"},
{"Canindeyu","py-14"},
{"Presidente Hayes","py-15"},
{"Alto Paraguay","py-16"},
{"Boqueron","py-19"},
{"San Pedro","py-2"},
{"Cordillera","py-3"},
{"Guaira","py-4"},
{"Caaguazu","py-5"},
{"Caazapa","py-6"},
{"Itapua","py-7"},
{"Paraguari","py-9"},
{"Asuncion","py-asu"},
{"Ad Dawhah","qa-da"},
{"Al Khawr wa adh Dhakhirah","qa-kh"},
{"Ash Shamal","qa-ms"},
{"Ar Rayyan","qa-ra"},
{"Umm Salal","qa-us"},
{"Al Wakrah","qa-wa"},
{"Az Za'ayin","qa-za"},
{"Reunion","re"},
{"Alba","ro-ab"},
{"Arges","ro-ag"},
{"Arad","ro-ar"},
{"Bucuresti","ro-b"},
{"Bacau","ro-bc"},
{"Bihor","ro-bh"},
{"Bistrita-Nasaud","ro-bn"},
{"Braila","ro-br"},
{"Botosani","ro-bt"},
{"Brasov","ro-bv"},
{"Buzau","ro-bz"},
{"Cluj","ro-cj"},
{"Caras-Severin","ro-cs"},
{"Constanta","ro-ct"},
{"Covasna","ro-cv"},
{"Dambovita","ro-db"},
{"Dolj","ro-dj"},
{"Gorj","ro-gj"},
{"Galati","ro-gl"},
{"Giurgiu","ro-gr"},
{"Hunedoara","ro-hd"},
{"Harghita","ro-hr"},
{"Ilfov","ro-if"},
{"Ialomita","ro-il"},
{"Iasi","ro-is"},
{"Mehedinti","ro-mh"},
{"Maramures","ro-mm"},
{"Mures","ro-ms"},
{"Neamt","ro-nt"},
{"Olt","ro-ot"},
{"Prahova","ro-ph"},
{"Sibiu","ro-sb"},
{"Salaj","ro-sj"},
{"Satu Mare","ro-sm"},
{"Suceava","ro-sv"},
{"Tulcea","ro-tl"},
{"Timis","ro-tm"},
{"Teleorman","ro-tr"},
{"Valcea","ro-vl"},
{"Vrancea","ro-vn"},
{"Vaslui","ro-vs"},
{"Adygeya, Respublika","ru-ad"},
{"Altay, Respublika","ru-al"},
{"Altayskiy kray","ru-alt"},
{"Amurskaya oblast'","ru-amu"},
{"Arkhangel'skaya oblast'","ru-ark"},
{"Astrakhanskaya oblast'","ru-ast"},
{"Bashkortostan, Respublika","ru-ba"},
{"Belgorodskaya oblast'","ru-bel"},
{"Bryanskaya oblast'","ru-bry"},
{"Buryatiya, Respublika","ru-bu"},
{"Chechenskaya Respublika","ru-ce"},
{"Chuvashskaya Respublika","ru-cu"},
{"Dagestan, Respublika","ru-da"},
{"Chelyabinskaya oblast'","ru-che"},
{"Chukotskiy avtonomnyy okrug","ru-chu"},
{"Ingushetiya, Respublika","ru-in"},
{"Irkutskaya oblast'","ru-irk"},
{"Ivanovskaya oblast'","ru-iva"},
{"Kamchatskiy kray","ru-kam"},
{"Kabardino-Balkarskaya Respublika","ru-kb"},
{"Karachayevo-Cherkesskaya Respublika","ru-kc"},
{"Krasnodarskiy kray","ru-kda"},
{"Kemerovskaya oblast'","ru-kem"},
{"Kaliningradskaya oblast'","ru-kgd"},
{"Kurganskaya oblast'","ru-kgn"},
{"Khabarovskiy kray","ru-kha"},
{"Khanty-Mansiyskiy avtonomnyy okrug-Yugra","ru-khm"},
{"Kirovskaya oblast'","ru-kir"},
{"Khakasiya, Respublika","ru-kk"},
{"Kalmykiya, Respublika","ru-kl"},
{"Kaluzhskaya oblast'","ru-klu"},
{"Komi, Respublika","ru-ko"},
{"Kostromskaya oblast'","ru-kos"},
{"Kareliya, Respublika","ru-kr"},
{"Kurskaya oblast'","ru-krs"},
{"Krasnoyarskiy kray","ru-kya"},
{"Leningradskaya oblast'","ru-len"},
{"Lipetskaya oblast'","ru-lip"},
{"Magadanskaya oblast'","ru-mag"},
{"Mariy El, Respublika","ru-me"},
{"Mordoviya, Respublika","ru-mo"},
{"Moskovskaya oblast'","ru-mos"},
{"Moskva","ru-mow"},
{"Murmanskaya oblast'","ru-mur"},
{"Nenetskiy avtonomnyy okrug","ru-nen"},
{"Novgorodskaya oblast'","ru-ngr"},
{"Nizhegorodskaya oblast'","ru-niz"},
{"Novosibirskaya oblast'","ru-nvs"},
{"Omskaya oblast'","ru-oms"},
{"Orenburgskaya oblast'","ru-ore"},
{"Orlovskaya oblast'","ru-orl"},
{"Permskiy kray","ru-per"},
{"Penzenskaya oblast'","ru-pnz"},
{"Primorskiy kray","ru-pri"},
{"Pskovskaya oblast'","ru-psk"},
{"Rostovskaya oblast'","ru-ros"},
{"Ryazanskaya oblast'","ru-rya"},
{"Sakha, Respublika","ru-sa"},
{"Sakhalinskaya oblast'","ru-sak"},
{"Samarskaya oblast'","ru-sam"},
{"Saratovskaya oblast'","ru-sar"},
{"Severnaya Osetiya-Alaniya, Respublika","ru-se"},
{"Smolenskaya oblast'","ru-smo"},
{"Sankt-Peterburg","ru-spe"},
{"Stavropol'skiy kray","ru-sta"},
{"Sverdlovskaya oblast'","ru-sve"},
{"Tatarstan, Respublika","ru-ta"},
{"Tambovskaya oblast'","ru-tam"},
{"Tomskaya oblast'","ru-tom"},
{"Tul'skaya oblast'","ru-tul"},
{"Tverskaya oblast'","ru-tve"},
{"Tyva, Respublika","ru-ty"},
{"Tyumenskaya oblast'","ru-tyu"},
{"Udmurtskaya Respublika","ru-ud"},
{"Ul'yanovskaya oblast'","ru-uly"},
{"Volgogradskaya oblast'","ru-vgg"},
{"Vladimirskaya oblast'","ru-vla"},
{"Vologodskaya oblast'","ru-vlg"},
{"Voronezhskaya oblast'","ru-vor"},
{"Yamalo-Nenetskiy avtonomnyy okrug","ru-yan"},
{"Yaroslavskaya oblast'","ru-yar"},
{"Yevreyskaya avtonomnaya oblast'","ru-yev"},
{"Zabaykal'skiy kray","ru-zab"},
{"Ville de Kigali","rw-01"},
{"Ar Riyad","sa-01"},
{"Makkah al Mukarramah","sa-02"},
{"Al Madinah al Munawwarah","sa-03"},
{"Al Qasim","sa-05"},
{"Ha'il","sa-06"},
{"Tabuk","sa-07"},
{"Al Hudud ash Shamaliyah","sa-08"},
{"Jazan","sa-09"},
{"Najran","sa-10"},
{"Al Bahah","sa-11"},
{"Al Jawf","sa-12"},
{"'Asir","sa-14"},
{"Guadalcanal","sb-gu"},
{"Isabel","sb-is"},
{"Makira","sb-mk"},
{"Malaita","sb-ml"},
{"English River","sc-16"},
{"North Darfur","sd-dn"},
{"South Darfur","sd-ds"},
{"West Darfur","sd-dw"},
{"Gedaref","sd-gd"},
{"Gezira","sd-gz"},
{"Kassala","sd-ka"},
{"Khartoum","sd-kh"},
{"North Kordofan","sd-kn"},
{"South Kordofan","sd-ks"},
{"Blue Nile","sd-nb"},
{"River Nile","sd-nr"},
{"White Nile","sd-nw"},
{"Red Sea","sd-rs"},
{"Sennar","sd-si"},
{"Stockholms Lan","se-ab"},
{"Vasterbottens Lan","se-ac"},
{"Norrbottens Lan","se-bd"},
{"Uppsala Lan","se-c"},
{"Sodermanlands Lan","se-d"},
{"Ostergotlands Lan","se-e"},
{"Jonkopings Lan","se-f"},
{"Kronobergs Lan","se-g"},
{"Kalmar Lan","se-h"},
{"Gotlands Lan","se-i"},
{"Blekinge Lan","se-k"},
{"Skane Lan","se-m"},
{"Hallands Lan","se-n"},
{"Vastra Gotaland","se-o"},
{"Varmlands Lan","se-s"},
{"Orebro Lan","se-t"},
{"Vastmanlands Lan","se-u"},
{"Dalarnas Lan","se-w"},
{"Gavleborgs Lan","se-x"},
{"Vasternorrlands Lan","se-y"},
{"Jamtlands Lan","se-z"},
{"Singapore","sg-01"},
{"Ascension","sh-ac"},
{"Saint Helena","sh-hl"},
{"Tristan da Cunha","sh-ta"},
{"Ajdovscina","si-001"},
{"Bled","si-003"},
{"Bohinj","si-004"},
{"Borovnica","si-005"},
{"Bovec","si-006"},
{"Brezovica","si-008"},
{"Brezice","si-009"},
{"Celje","si-011"},
{"Cerknica","si-013"},
{"Cerkno","si-014"},
{"Crensovci","si-015"},
{"Crnomelj","si-017"},
{"Destrnik","si-018"},
{"Divaca","si-019"},
{"Domzale","si-023"},
{"Dravograd","si-025"},
{"Gornja Radgona","si-029"},
{"Grosuplje","si-032"},
{"Hrastnik","si-034"},
{"Idrija","si-036"},
{"Ig","si-037"},
{"Ilirska Bistrica","si-038"},
{"Ivancna Gorica","si-039"},
{"Izola-Isola","si-040"},
{"Jesenice","si-041"},
{"Kamnik","si-043"},
{"Kanal","si-044"},
{"Kidricevo","si-045"},
{"Kobarid","si-046"},
{"Kocevje","si-048"},
{"Koper-Capodistria","si-050"},
{"Kranj","si-052"},
{"Kranjska Gora","si-053"},
{"Krsko","si-054"},
{"Lasko","si-057"},
{"Lenart","si-058"},
{"Lendava","si-059"},
{"Litija","si-060"},
{"Ljubljana","si-061"},
{"Ljutomer","si-063"},
{"Logatec","si-064"},
{"Maribor","si-070"},
{"Medvode","si-071"},
{"Menges","si-072"},
{"Metlika","si-073"},
{"Mezica","si-074"},
{"Miren-Kostanjevica","si-075"},
{"Mislinja","si-076"},
{"Mozirje","si-079"},
{"Murska Sobota","si-080"},
{"Muta","si-081"},
{"Nova Gorica","si-084"},
{"Novo Mesto","si-085"},
{"Odranci","si-086"},
{"Ormoz","si-087"},
{"Piran","si-090"},
{"Pivka","si-091"},
{"Postojna","si-094"},
{"Ptuj","si-096"},
{"Racam","si-098"},
{"Radece","si-099"},
{"Radenci","si-100"},
{"Radlje ob Dravi","si-101"},
{"Radovljica","si-102"},
{"Ravne na Koroskem","si-103"},
{"Ribnica","si-104"},
{"Rogaska Slatina","si-106"},
{"Sevnica","si-110"},
{"Sezana","si-111"},
{"Slovenj Gradec","si-112"},
{"Slovenska Bistrica","si-113"},
{"Slovenske Konjice","si-114"},
{"Sencur","si-117"},
{"Sentilj","si-118"},
{"Sentjur pri Celju","si-120"},
{"Skofja Loka","si-122"},
{"Skofljica","si-123"},
{"Sostanj","si-126"},
{"Store","si-127"},
{"Tolmin","si-128"},
{"Trbovlje","si-129"},
{"Trebnje","si-130"},
{"Trzic","si-131"},
{"Turnisce","si-132"},
{"Velenje","si-133"},
{"Vipava","si-136"},
{"Vodice","si-138"},
{"Vojnik","si-139"},
{"Vrhnika","si-140"},
{"Vuzenica","si-141"},
{"Zagorje ob Savi","si-142"},
{"Zrece","si-144"},
{"Zelezniki","si-146"},
{"Ziri","si-147"},
{"Hoce-Slivnica","si-160"},
{"Horjul","si-162"},
{"Lovrenc na Pohorju","si-167"},
{"Miklavz na Dravskem Polju","si-169"},
{"Oplotnica","si-171"},
{"Polzela","si-173"},
{"Prebold","si-174"},
{"Prevalje","si-175"},
{"Sempeter-Vrtojba","si-183"},
{"Trzin","si-186"},
{"Zalec","si-190"},
{"Zuzemberk","si-193"},
{"Poljcane","si-200"},
{"Straza","si-203"},
{"Log-Dragomer","si-208"},
{"Svalbard and Jan Mayen","sj"},
{"Banskobystricky kraj","sk-bc"},
{"Bratislavsky kraj","sk-bl"},
{"Kosicky kraj","sk-ki"},
{"Nitriansky kraj","sk-ni"},
{"Presovsky kraj","sk-pv"},
{"Trnavsky kraj","sk-ta"},
{"Trenciansky kraj","sk-tc"},
{"Zilinsky kraj","sk-zi"},
{"Western Area","sl-w"},
{"Acquaviva","sm-01"},
{"Chiesanuova","sm-02"},
{"San Marino","sm-07"},
{"Serravalle","sm-09"},
{"Diourbel","sn-db"},
{"Dakar","sn-dk"},
{"Fatick","sn-fk"},
{"Kaffrine","sn-ka"},
{"Kolda","sn-kd"},
{"Kedougou","sn-ke"},
{"Kaolack","sn-kl"},
{"Louga","sn-lg"},
{"Matam","sn-mt"},
{"Sedhiou","sn-se"},
{"Saint-Louis","sn-sl"},
{"Tambacounda","sn-tc"},
{"Thies","sn-th"},
{"Ziguinchor","sn-zg"},
{"Awdal","so-aw"},
{"Bakool","so-bk"},
{"Banaadir","so-bn"},
{"Bari","so-br"},
{"Bay","so-by"},
{"Galguduud","so-ga"},
{"Gedo","so-ge"},
{"Hiiraan","so-hi"},
{"Jubbada Dhexe","so-jd"},
{"Jubbada Hoose","so-jh"},
{"Mudug","so-mu"},
{"Nugaal","so-nu"},
{"Sanaag","so-sa"},
{"Shabeellaha Dhexe","so-sd"},
{"Shabeellaha Hoose","so-sh"},
{"Sool","so-so"},
{"Togdheer","so-to"},
{"Woqooyi Galbeed","so-wo"},
{"Brokopondo","sr-br"},
{"Commewijne","sr-cm"},
{"Coronie","sr-cr"},
{"Marowijne","sr-ma"},
{"Nickerie","sr-ni"},
{"Paramaribo","sr-pm"},
{"Saramacca","sr-sa"},
{"Wanica","sr-wa"},
{"Northern Bahr el Ghazal","ss-bn"},
{"Western Bahr el Ghazal","ss-bw"},
{"Central Equatoria","ss-ec"},
{"Eastern Equatoria","ss-ee"},
{"Western Equatoria","ss-ew"},
{"Jonglei","ss-jg"},
{"Lakes","ss-lk"},
{"Upper Nile","ss-nu"},
{"Unity","ss-uy"},
{"Warrap","ss-wr"},
{"Principe","st-p"},
{"Sao Tome","st-s"},
{"Ahuachapan","sv-ah"},
{"Cabanas","sv-ca"},
{"Cuscatlan","sv-cu"},
{"Chalatenango","sv-ch"},
{"Morazan","sv-mo"},
{"Santa Ana","sv-sa"},
{"San Miguel","sv-sm"},
{"Sonsonate","sv-so"},
{"San Salvador","sv-ss"},
{"San Vicente","sv-sv"},
{"Usulutan","sv-us"},
{"Dimashq","sy-di"},
{"Dar'a","sy-dr"},
{"Dayr az Zawr","sy-dy"},
{"Al Hasakah","sy-ha"},
{"Hims","sy-hi"},
{"Halab","sy-hl"},
{"Hamah","sy-hm"},
{"Idlib","sy-id"},
{"Al Ladhiqiyah","sy-la"},
{"Al Qunaytirah","sy-qu"},
{"Ar Raqqah","sy-ra"},
{"Rif Dimashq","sy-rd"},
{"As Suwayda'","sy-su"},
{"Tartus","sy-ta"},
{"Hhohho","sz-hh"},
{"Lubombo","sz-lu"},
{"Manzini","sz-ma"},
{"Shiselweni","sz-sh"},
{"Turks and Caicos Islands","tc"},
{"Batha","td-ba"},
{"Bahr el Gazel","td-bg"},
{"Borkou","td-bo"},
{"Chari-Baguirmi","td-cb"},
{"Guera","td-gr"},
{"Hadjer Lamis","td-hl"},
{"Kanem","td-ka"},
{"Lac","td-lc"},
{"Logone-Occidental","td-lo"},
{"Logone-Oriental","td-lr"},
{"Mandoul","td-ma"},
{"Moyen-Chari","td-mc"},
{"Mayo-Kebbi-Est","td-me"},
{"Mayo-Kebbi-Ouest","td-mo"},
{"Ouaddai","td-od"},
{"Salamat","td-sa"},
{"Tandjile","td-ta"},
{"Tibesti","td-ti"},
{"Wadi Fira","td-wf"},
{"Kara","tg-k"},
{"Maritime","tg-m"},
{"Savannes","tg-s"},
{"Krung Thep Maha Nakhon","th-10"},
{"Samut Prakan","th-11"},
{"Nonthaburi","th-12"},
{"Pathum Thani","th-13"},
{"Phra Nakhon Si Ayutthaya","th-14"},
{"Ang Thong","th-15"},
{"Lop Buri","th-16"},
{"Sing Buri","th-17"},
{"Chai Nat","th-18"},
{"Saraburi","th-19"},
{"Chon Buri","th-20"},
{"Rayong","th-21"},
{"Chanthaburi","th-22"},
{"Trat","th-23"},
{"Chachoengsao","th-24"},
{"Prachin Buri","th-25"},
{"Nakhon Nayok","th-26"},
{"Sa Kaeo","th-27"},
{"Nakhon Ratchasima","th-30"},
{"Buri Ram","th-31"},
{"Surin","th-32"},
{"Si Sa Ket","th-33"},
{"Ubon Ratchathani","th-34"},
{"Yasothon","th-35"},
{"Chaiyaphum","th-36"},
{"Amnat Charoen","th-37"},
{"Nong Bua Lam Phu","th-39"},
{"Khon Kaen","th-40"},
{"Udon Thani","th-41"},
{"Loei","th-42"},
{"Nong Khai","th-43"},
{"Maha Sarakham","th-44"},
{"Roi Et","th-45"},
{"Kalasin","th-46"},
{"Sakon Nakhon","th-47"},
{"Nakhon Phanom","th-48"},
{"Mukdahan","th-49"},
{"Chiang Mai","th-50"},
{"Lamphun","th-51"},
{"Lampang","th-52"},
{"Uttaradit","th-53"},
{"Phrae","th-54"},
{"Nan","th-55"},
{"Phayao","th-56"},
{"Chiang Rai","th-57"},
{"Mae Hong Son","th-58"},
{"Nakhon Sawan","th-60"},
{"Uthai Thani","th-61"},
{"Kamphaeng Phet","th-62"},
{"Tak","th-63"},
{"Sukhothai","th-64"},
{"Phitsanulok","th-65"},
{"Phichit","th-66"},
{"Phetchabun","th-67"},
{"Ratchaburi","th-70"},
{"Kanchanaburi","th-71"},
{"Suphan Buri","th-72"},
{"Nakhon Pathom","th-73"},
{"Samut Sakhon","th-74"},
{"Samut Songkhram","th-75"},
{"Phetchaburi","th-76"},
{"Prachuap Khiri Khan","th-77"},
{"Nakhon Si Thammarat","th-80"},
{"Krabi","th-81"},
{"Phangnga","th-82"},
{"Phuket","th-83"},
{"Surat Thani","th-84"},
{"Ranong","th-85"},
{"Chumphon","th-86"},
{"Songkhla","th-90"},
{"Satun","th-91"},
{"Trang","th-92"},
{"Phatthalung","th-93"},
{"Pattani","th-94"},
{"Yala","th-95"},
{"Narathiwat","th-96"},
{"Tajikistan","tj"},
{"Kuhistoni Badakhshon","tj-gb"},
{"Khatlon","tj-kt"},
{"Regions of Republican Subordination","tj-rr"},
{"Sughd","tj-su"},
{"Tokelau","tk"},
{"Dili","tl-di"},
{"Ahal","tm-a"},
{"Balkan","tm-b"},
{"Dashoguz","tm-d"},
{"Lebap","tm-l"},
{"Mary","tm-m"},
{"Tunis","tn-11"},
{"Aiana","tn-12"},
{"Ben Arous","tn-13"},
{"Manouba","tn-14"},
{"Nabeul","tn-21"},
{"Zaghouan","tn-22"},
{"Bizerte","tn-23"},
{"Bajah","tn-31"},
{"Jendouba","tn-32"},
{"El Kef","tn-33"},
{"Siliana","tn-34"},
{"Kairouan","tn-41"},
{"Kasserine","tn-42"},
{"Sidi Bou Zid","tn-43"},
{"Sousse","tn-51"},
{"Al Munastir","tn-52"},
{"Al Mahdia","tn-53"},
{"Sfax","tn-61"},
{"Gafsa","tn-71"},
{"Tozeur","tn-72"},
{"Kebili","tn-73"},
{"Gabes","tn-81"},
{"Madanin","tn-82"},
{"Tataouine","tn-83"},
{"Ha'apai","to-02"},
{"Tongatapu","to-04"},
{"Vava'u","to-05"},
{"Adana","tr-01"},
{"Adiyaman","tr-02"},
{"Afyonkarahisar","tr-03"},
{"Agri","tr-04"},
{"Amasya","tr-05"},
{"Ankara","tr-06"},
{"Antalya","tr-07"},
{"Artvin","tr-08"},
{"Aydin","tr-09"},
{"Balikesir","tr-10"},
{"Bilecik","tr-11"},
{"Bingol","tr-12"},
{"Bitlis","tr-13"},
{"Bolu","tr-14"},
{"Burdur","tr-15"},
{"Bursa","tr-16"},
{"Canakkale","tr-17"},
{"Cankiri","tr-18"},
{"Corum","tr-19"},
{"Denizli","tr-20"},
{"Diyarbakir","tr-21"},
{"Edirne","tr-22"},
{"Elazig","tr-23"},
{"Erzincan","tr-24"},
{"Erzurum","tr-25"},
{"Eskisehir","tr-26"},
{"Gaziantep","tr-27"},
{"Giresun","tr-28"},
{"Gumushane","tr-29"},
{"Hakkari","tr-30"},
{"Hatay","tr-31"},
{"Isparta","tr-32"},
{"Mersin","tr-33"},
{"Istanbul","tr-34"},
{"Izmir","tr-35"},
{"Kars","tr-36"},
{"Kastamonu","tr-37"},
{"Kayseri","tr-38"},
{"Kirklareli","tr-39"},
{"Kirsehir","tr-40"},
{"Kocaeli","tr-41"},
{"Konya","tr-42"},
{"Kutahya","tr-43"},
{"Malatya","tr-44"},
{"Manisa","tr-45"},
{"Kahramanmaras","tr-46"},
{"Mardin","tr-47"},
{"Mugla","tr-48"},
{"Mus","tr-49"},
{"Nevsehir","tr-50"},
{"Nigde","tr-51"},
{"Ordu","tr-52"},
{"Rize","tr-53"},
{"Sakarya","tr-54"},
{"Samsun","tr-55"},
{"Siirt","tr-56"},
{"Sinop","tr-57"},
{"Sivas","tr-58"},
{"Tekirdag","tr-59"},
{"Tokat","tr-60"},
{"Trabzon","tr-61"},
{"Tunceli","tr-62"},
{"Sanliurfa","tr-63"},
{"Usak","tr-64"},
{"Van","tr-65"},
{"Yozgat","tr-66"},
{"Zonguldak","tr-67"},
{"Aksaray","tr-68"},
{"Bayburt","tr-69"},
{"Karaman","tr-70"},
{"Kirikkale","tr-71"},
{"Batman","tr-72"},
{"Sirnak","tr-73"},
{"Bartin","tr-74"},
{"Ardahan","tr-75"},
{"Igdir","tr-76"},
{"Yalova","tr-77"},
{"Karabuk","tr-78"},
{"Kilis","tr-79"},
{"Osmaniye","tr-80"},
{"Duzce","tr-81"},
{"Arima","tt-ari"},
{"Mayaro","tt-mrc"},
{"Port-of-Spain","tt-pos"},
{"San Fernando","tt-sfo"},
{"Tobago","tt-tob"},
{"Tuvalu","tv"},
{"T'ai-wan","tw"},
{"Kao-hsiung","tw-khh"},
{"T'ai-pei","tw-tpe"},
{"Arusha","tz-01"},
{"Dar es Salaam","tz-02"},
{"Dodoma","tz-03"},
{"Iringa","tz-04"},
{"Kagera","tz-05"},
{"Kaskazini Pemba","tz-06"},
{"Kaskazini Unguja","tz-07"},
{"Kigoma","tz-08"},
{"Kilimanjaro","tz-09"},
{"Kusini Pemba","tz-10"},
{"Kusini Unguja","tz-11"},
{"Lindi","tz-12"},
{"Mara","tz-13"},
{"Mbeya","tz-14"},
{"Mjini Magharibi","tz-15"},
{"Morogoro","tz-16"},
{"Mtwara","tz-17"},
{"Pwani","tz-19"},
{"Rukwa","tz-20"},
{"Ruvuma","tz-21"},
{"Shinyanga","tz-22"},
{"Singida","tz-23"},
{"Tabora","tz-24"},
{"Tanga","tz-25"},
{"Manyara","tz-26"},
{"Vinnyts'ka Oblast'","ua-05"},
{"Volyns'ka Oblast'","ua-07"},
{"Luhans'ka Oblast'","ua-09"},
{"Dnipropetrovs'ka Oblast'","ua-12"},
{"Donets'ka Oblast'","ua-14"},
{"Zhytomyrs'ka Oblast'","ua-18"},
{"Zakarpats'ka Oblast'","ua-21"},
{"Zaporiz'ka Oblast'","ua-23"},
{"Ivano-Frankivs'ka Oblast'","ua-26"},
{"Kyiv","ua-30"},
{"Kyivs'ka Oblast'","ua-32"},
{"Kirovohrads'ka Oblast'","ua-35"},
{"Sevastopol'","ua-40"},
{"Avtonomna Respublika Krym","ua-43"},
{"L'vivs'ka Oblast'","ua-46"},
{"Mykolaivs'ka Oblast'","ua-48"},
{"Odes'ka Oblast'","ua-51"},
{"Poltavs'ka Oblast'","ua-53"},
{"Rivnens'ka Oblast'","ua-56"},
{"Sums'ka Oblast'","ua-59"},
{"Ternopil's'ka Oblast'","ua-61"},
{"Kharkivs'ka Oblast'","ua-63"},
{"Khersons'ka Oblast'","ua-65"},
{"Khmel'nyts'ka Oblast'","ua-68"},
{"Cherkas'ka Oblast'","ua-71"},
{"Chernihivs'ka Oblast'","ua-74"},
{"Chernivets'ka Oblast'","ua-77"},
{"Kalangala","ug-101"},
{"Kampala","ug-102"},
{"Kiboga","ug-103"},
{"Luwero","ug-104"},
{"Masaka","ug-105"},
{"Mpigi","ug-106"},
{"Mubende","ug-107"},
{"Mukono","ug-108"},
{"Nakasongola","ug-109"},
{"Rakai","ug-110"},
{"Sembabule","ug-111"},
{"Kayunga","ug-112"},
{"Wakiso","ug-113"},
{"Mityana","ug-114"},
{"Nakaseke","ug-115"},
{"Lyantonde","ug-116"},
{"Buikwe","ug-117"},
{"Bukomansibi","ug-118"},
{"Buvuma","ug-120"},
{"Gomba","ug-121"},
{"Kyankwanzi","ug-123"},
{"Lwengo","ug-124"},
{"Bugiri","ug-201"},
{"Busia","ug-202"},
{"Iganga","ug-203"},
{"Jinja","ug-204"},
{"Kamuli","ug-205"},
{"Kapchorwa","ug-206"},
{"Katakwi","ug-207"},
{"Kumi","ug-208"},
{"Mbale","ug-209"},
{"Pallisa","ug-210"},
{"Soroti","ug-211"},
{"Tororo","ug-212"},
{"Kaberamaido","ug-213"},
{"Mayuge","ug-214"},
{"Sironko","ug-215"},
{"Amuria","ug-216"},
{"Budaka","ug-217"},
{"Bukwa","ug-218"},
{"Butaleja","ug-219"},
{"Kaliro","ug-220"},
{"Manafwa","ug-221"},
{"Namutumba","ug-222"},
{"Bududa","ug-223"},
{"Bukedea","ug-224"},
{"Bulambuli","ug-225"},
{"Buyende","ug-226"},
{"Kibuku","ug-227"},
{"Kween","ug-228"},
{"Luuka","ug-229"},
{"Namayingo","ug-230"},
{"Ngora","ug-231"},
{"Serere","ug-232"},
{"Adjumani","ug-301"},
{"Apac","ug-302"},
{"Arua","ug-303"},
{"Gulu","ug-304"},
{"Kitgum","ug-305"},
{"Kotido","ug-306"},
{"Lira","ug-307"},
{"Moroto","ug-308"},
{"Moyo","ug-309"},
{"Nebbi","ug-310"},
{"Nakapiripirit","ug-311"},
{"Pader","ug-312"},
{"Yumbe","ug-313"},
{"Amolatar","ug-314"},
{"Kaabong","ug-315"},
{"Koboko","ug-316"},
{"Abim","ug-317"},
{"Dokolo","ug-318"},
{"Amuru","ug-319"},
{"Maracha","ug-320"},
{"Oyam","ug-321"},
{"Agago","ug-322"},
{"Alebtong","ug-323"},
{"Amudat","ug-324"},
{"Kole","ug-326"},
{"Napak","ug-328"},
{"Otuke","ug-330"},
{"Zombo","ug-331"},
{"Bundibugyo","ug-401"},
{"Bushenyi","ug-402"},
{"Hoima","ug-403"},
{"Kabale","ug-404"},
{"Kabarole","ug-405"},
{"Kasese","ug-406"},
{"Kibaale","ug-407"},
{"Kisoro","ug-408"},
{"Masindi","ug-409"},
{"Mbarara","ug-410"},
{"Ntungamo","ug-411"},
{"Rukungiri","ug-412"},
{"Kamwenge","ug-413"},
{"Kanungu","ug-414"},
{"Kyenjojo","ug-415"},
{"Isingiro","ug-417"},
{"Buliisa","ug-419"},
{"Kiryandongo","ug-420"},
{"Kyegegwa","ug-421"},
{"Mitooma","ug-422"},
{"Ntoroko","ug-423"},
{"Rubirizi","ug-424"},
{"Sheema","ug-425"},
{"Palmyra Atoll","um-95"},
{"Alaska","us-ak"},
{"Alabama","us-al"},
{"Arkansas","us-ar"},
{"Arizona","us-az"},
{"California","us-ca"},
{"Colorado","us-co"},
{"Connecticut","us-ct"},
{"District Of Columbia","us-dc"},
{"Delaware","us-de"},
{"Florida","us-fl"},
{"Georgia","us-ga"},
{"Hawaii","us-hi"},
{"Iowa","us-ia"},
{"Idaho","us-id"},
{"Illinois","us-il"},
{"Indiana","us-in"},
{"Kansas","us-ks"},
{"Kentucky","us-ky"},
{"Louisiana","us-la"},
{"Massachusetts","us-ma"},
{"Maine","us-me"},
{"Michigan","us-mi"},
{"Minnesota","us-mn"},
{"Missouri","us-mo"},
{"Mississippi","us-ms"},
{"North Carolina","us-nc"},
{"North Dakota","us-nd"},
{"Nebraska","us-ne"},
{"New Hampshire","us-nh"},
{"New Jersey","us-nj"},
{"New Mexico","us-nm"},
{"Nevada","us-nv"},
{"New York","us-ny"},
{"Ohio","us-oh"},
{"Oklahoma","us-ok"},
{"Oregon","us-or"},
{"Pennsylvania","us-pa"},
{"Rhode Island","us-ri"},
{"South Carolina","us-sc"},
{"South Dakota","us-sd"},
{"Tennessee","us-tn"},
{"Texas","us-tx"},
{"Utah","us-ut"},
{"Virginia","us-va"},
{"Vermont","us-vt"},
{"Washington","us-wa"},
{"Wisconsin","us-wi"},
{"West Virginia","us-wv"},
{"Wyoming","us-wy"},
{"Artigas","uy-ar"},
{"Canelones","uy-ca"},
{"Cerro Largo","uy-cl"},
{"Colonia","uy-co"},
{"Durazno","uy-du"},
{"Flores","uy-fs"},
{"Lavalleja","uy-la"},
{"Maldonado","uy-ma"},
{"Montevideo","uy-mo"},
{"Paysandu","uy-pa"},
{"Rocha","uy-ro"},
{"Rivera","uy-rv"},
{"Salto","uy-sa"},
{"Soriano","uy-so"},
{"Tacuarembo","uy-ta"},
{"Treinta y Tres","uy-tt"},
{"Andijon","uz-an"},
{"Buxoro","uz-bu"},
{"Farg'ona","uz-fa"},
{"Jizzax","uz-ji"},
{"Namangan","uz-ng"},
{"Navoiy","uz-nw"},
{"Qashqadaryo","uz-qa"},
{"Qoraqalpog'iston Respublikasi","uz-qr"},
{"Samarqand","uz-sa"},
{"Sirdaryo","uz-si"},
{"Surxondaryo","uz-su"},
{"Toshkent","uz-to"},
{"Xorazm","uz-xo"},
{"Charlotte","vc-01"},
{"Anzoategui","ve-b"},
{"Apure","ve-c"},
{"Aragua","ve-d"},
{"Barinas","ve-e"},
{"Carabobo","ve-g"},
{"Cojedes","ve-h"},
{"Falcon","ve-i"},
{"Guarico","ve-j"},
{"Lara","ve-k"},
{"Merida","ve-l"},
{"Miranda","ve-m"},
{"Monagas","ve-n"},
{"Nueva Esparta","ve-o"},
{"Portuguesa","ve-p"},
{"Tachira","ve-s"},
{"Trujillo","ve-t"},
{"Yaracuy","ve-u"},
{"Zulia","ve-v"},
{"Vargas","ve-x"},
{"Delta Amacuro","ve-y"},
{"Lai Chau","vn-01"},
{"Lao Cai","vn-02"},
{"Ha Giang","vn-03"},
{"Cao Bang","vn-04"},
{"Son La","vn-05"},
{"Yen Bai","vn-06"},
{"Tuyen Quang","vn-07"},
{"Lang Son","vn-09"},
{"Quang Ninh","vn-13"},
{"Hoa Binh","vn-14"},
{"Ninh Binh","vn-18"},
{"Thai Binh","vn-20"},
{"Thanh Hoa","vn-21"},
{"Nghe An","vn-22"},
{"Ha Tinh","vn-23"},
{"Quang Binh","vn-24"},
{"Quang Tri","vn-25"},
{"Thua Thien-Hue","vn-26"},
{"Quang Nam","vn-27"},
{"Quang Ngai","vn-29"},
{"Gia Lai","vn-30"},
{"Binh Dinh","vn-31"},
{"Phu Yen","vn-32"},
{"Dak Lak","vn-33"},
{"Khanh Hoa","vn-34"},
{"Lam Dong","vn-35"},
{"Ninh Thuan","vn-36"},
{"Tay Ninh","vn-37"},
{"Dong Nai","vn-39"},
{"Binh Thuan","vn-40"},
{"Long An","vn-41"},
{"An Giang","vn-44"},
{"Dong Thap","vn-45"},
{"Tien Giang","vn-46"},
{"Kien Giang","vn-47"},
{"Vinh Long","vn-49"},
{"Ben Tre","vn-50"},
{"Tra Vinh","vn-51"},
{"Soc Trang","vn-52"},
{"Bac Kan","vn-53"},
{"Bac Giang","vn-54"},
{"Bac Lieu","vn-55"},
{"Bac Ninh","vn-56"},
{"Binh Duong","vn-57"},
{"Binh Phuoc","vn-58"},
{"Ca Mau","vn-59"},
{"Hai Duong","vn-61"},
{"Ha Nam","vn-63"},
{"Hung Yen","vn-66"},
{"Nam Dinh","vn-67"},
{"Phu Tho","vn-68"},
{"Thai Nguyen","vn-69"},
{"Vinh Phuc","vn-70"},
{"Dien Bien","vn-71"},
{"Can Tho","vn-ct"},
{"Da Nang","vn-dn"},
{"Ha Noi","vn-hn"},
{"Hai Phong","vn-hp"},
{"Ho Chi Minh","vn-sg"},
{"Malampa","vu-map"},
{"Sanma","vu-sam"},
{"Shefa","vu-see"},
{"Tafea","vu-tae"},
{"Torba","vu-tob"},
{"Wallis and Futuna Islands","wf"},
{"A'ana","ws-aa"},
{"Atua","ws-at"},
{"Gagaifomauga","ws-gi"},
{"Palauli","ws-pa"},
{"Tuamasaga","ws-tu"},
{"Abyan","ye-ab"},
{"'Adan","ye-ad"},
{"'Amran","ye-am"},
{"Al Bayda'","ye-ba"},
{"Ad Dali","ye-da"},
{"Dhamar","ye-dh"},
{"Hadramawt","ye-hd"},
{"Hajjah","ye-hj"},
{"Al Hudaydah","ye-hu"},
{"Ibb","ye-ib"},
{"Lahij","ye-la"},
{"Ma'rib","ye-ma"},
{"Al Mahrah","ye-mr"},
{"Al Mahwit","ye-mw"},
{"Raymah","ye-ra"},
{"Amanat al 'Asimah","ye-sa"},
{"Sa'dah","ye-sd"},
{"Shabwah","ye-sh"},
{"San'a'","ye-sn"},
{"Ta'izz","ye-ta"},
{"Eastern Cape","za-ec"},
{"Free State","za-fs"},
{"Gauteng","za-gt"},
{"Limpopo","za-lp"},
{"Mpumalanga","za-mp"},
{"Northern Cape","za-nc"},
{"KwaZulu-Natal","za-nl"},
{"Western Cape","za-wc"},
{"Luapula","zm-04"},
{"North-Western","zm-06"},
{"Copperbelt","zm-08"},
{"Lusaka","zm-09"},
{"Bulawayo","zw-bu"},
{"Harare","zw-ha"},
{"Manicaland","zw-ma"},
{"Mashonaland Central","zw-mc"},
{"Mashonaland East","zw-me"},
{"Midlands","zw-mi"},
{"Matabeleland North","zw-mn"},
{"Matabeleland South","zw-ms"},
{"Masvingo","zw-mv"},
{"Mashonaland West","zw-mw"},
		};

		#endregion ISO 3166-2
	}
}